### ISSUE TITLE
Compilation on Linux Ubuntu 12.04 and 14.04 

### ISSUE THREAD

**Issue by colindaven** [gpertea/stringtie#1]
Hi,

which dependencies are required? I am having problems with compilation.

cd stringtie-master
make release

I am guessing:
g++

I receive following error (apologies for the german).

Any ideas ? 

Thanks,
Colin

bam_reheader.c:11:16: Warnung: Variable »old« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. kprobaln.c -o kprobaln.o
kprobaln.c: In Funktion »kpa_glocal«:
kprobaln.c:78:21: Warnung: Variable »is_diff« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_cat.c -o bam_cat.o
ar -csru libbam.a bgzf.o kstring.o bam_aux.o bam.o bam_import.o sam.o bam_index.o bam_pileup.o bam_lpileup.o bam_md.o razf.o faidx.o bedidx.o bam_sort.o sam_header.o bam_reheader.o kprobal
n.o bam_cat.o
make[1]: Verlasse Verzeichnis '/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18'
g++ -g -L./samtools-0.1.18  -o stringtie gclib/GBase.o gclib/GArgs.o gclib/GStr.o gclib/GBam.o gclib/gdna.o gclib/codons.o gclib/GFaSeqGet.o gclib/gff.o gclib/GThreads.o rlink.o tablemaker
.o stringtie.o -lz -lbam -lpthread
./samtools-0.1.18/libbam.a(bam_import.o): In function `ks_getuntil2':
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bam_import.c:17: undefined reference to `gzread'
./samtools-0.1.18/libbam.a(bam_import.o): In function `__bam_get_lines':
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bam_import.c:76: undefined reference to `gzdopen'
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bam_import.c:92: undefined reference to `gzclose'
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bam_import.c:76: undefined reference to `gzopen64'
./samtools-0.1.18/libbam.a(bam_import.o): In function `sam_header_read2':
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bam_import.c:126: undefined reference to `gzdopen'
./samtools-0.1.18/libbam.a(bam_import.o): In function `ks_getc': 
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bam_import.c:17: undefined reference to `gzread'
./samtools-0.1.18/libbam.a(bam_import.o): In function `sam_header_read2':
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bam_import.c:147: undefined reference to `gzclose'
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bam_import.c:126: undefined reference to `gzopen64'
./samtools-0.1.18/libbam.a(bam_import.o): In function `sam_open':
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bam_import.c:468: undefined reference to `gzdopen'
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bam_import.c:468: undefined reference to `gzopen64'
./samtools-0.1.18/libbam.a(bam_import.o): In function `sam_close':
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bam_import.c:481: undefined reference to `gzclose'
./samtools-0.1.18/libbam.a(bgzf.o): In function `deflate_block': 
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bgzf.c:311: undefined reference to `deflate'
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bgzf.c:313: undefined reference to `deflateEnd'
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bgzf.c:305: undefined reference to `deflateInit2_'
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bgzf.c:329: undefined reference to `deflateEnd'
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bgzf.c:345: undefined reference to `crc32'
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bgzf.c:346: undefined reference to `crc32'
./samtools-0.1.18/libbam.a(bgzf.o): In function `inflate_block': 
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bgzf.c:380: undefined reference to `inflateInit2_'
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bgzf.c:385: undefined reference to `inflate'
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bgzf.c:391: undefined reference to `inflateEnd'
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/bgzf.c:387: undefined reference to `inflateEnd'
./samtools-0.1.18/libbam.a(razf.o): In function `_razf_write':   
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/razf.c:197: undefined reference to `deflate'
./samtools-0.1.18/libbam.a(razf.o): In function `razf_open_w':   
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/razf.c:170: undefined reference to `deflateInit2_'
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/razf.c:186: undefined reference to `deflateSetHeader'
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/razf.c:389: undefined reference to `inflateInit2_'
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/razf.c:390: undefined reference to `inflateEnd'
./samtools-0.1.18/libbam.a(razf.o): In function `_razf_read':
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/razf.c:602: undefined reference to `inflate'
./samtools-0.1.18/libbam.a(razf.o): In function `razf_flush':
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/razf.c:230: undefined reference to `deflate'
./samtools-0.1.18/libbam.a(razf.o): In function `_razf_reset_read':
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/razf.c:709: undefined reference to `inflateReset'
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/razf.c:709: undefined reference to `inflateReset'
./samtools-0.1.18/libbam.a(razf.o): In function `razf_close':
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/razf.c:826: undefined reference to `inflateEnd'
./samtools-0.1.18/libbam.a(razf.o): In function `razf_end_flush':
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/razf.c:254: undefined reference to `deflate'
./samtools-0.1.18/libbam.a(razf.o): In function `razf_close':
/home/bioinformatics/programs/stringtie/stringtie-master/samtools-0.1.18/razf.c:800: undefined reference to `deflateEnd'
collect2: ld gab 1 als Ende-Status zurück
make: *** [stringtie] Fehler 1

**Comment by gpertea** [comment]
Indeed my assumption was that zlib (libz) library and headers are already installed on the system, but obviously not everybody is building this on a development system.. I think for ubuntu this would be the zlib1g-dev package (not sure, I don't use ubuntu). Another dependency might be 'libpthread-stubs0-dev' package from what I read about ubuntu. 
However it looks like you already had those installed, as the compilation works OK, only at linking stage you get those libz errors.. So this seems to be a linking order issue - I had no idea that gcc on Ubuntu still cares about the order of libraries there.. I just submitted a patched Makefile with the silly change needed, please let me know if it works for you like this.

**Comment by colindaven** [comment]
Hi,

thanks for this. I did already have these packages installed afaik.

Compilation ran fine - thanks - and Stringtie now appears to be running properly.
