### ISSUE TITLE
Map super-reads and unassembled reads to genome

### ISSUE THREAD

**Issue by tiramisutes** [gpertea/stringtie#10]
When i runing StringTie addition program <superreads.pl> produce super-reads and two unassembled paired reads,But i don't know how to used this results map to genome，like HISAT（http://ccb.jhu.edu/software/hisat/manual.shtml ）  It seem not have appropriate selectable parameters.Can you help me?Thank you very much.

**Comment by gpertea** [comment]
You can use HISAT (using the -U option) to align the LongReads.fq as single (unpaired) reads. Then you can run HISAT again using the  -1 and -2 options to align the two files with paired unassembled reads that have the extension .notAssembled.fq.gz. (please check the HISAT manual about how to perform HISAT searches).  After both these HISAT searches are performed, it's important to *sort* the resulting SAM files by converting them to BAM and sorting each BAM file, then *merge* the 2 sorted BAM files into one sorted BAM file, which you can finally give to StringTie for assembly (please check the samtools documentation about how to convert SAM to BAM, sort each BAM and merge sorted BAMs).

**Comment by tiramisutes** [comment]
Ok,thanks
