### ISSUE TITLE
Stringtie still considers GENCODE gene annotation as 1 exon transcript

### ISSUE THREAD

**Issue by apexamodi** [gpertea/stringtie#103]
Hi,

Im using StringTie v1.3.3 and gencode.v19.annotation.gtf. In my merged sample gtf file, I am noticing that Stringtie still has the issue of calling genes as one exon transcript. I know this was resolved for gencode v20 so not sure why it would be doing this for v19. Can I just use Stringtie using a gencode v19 annotation with the gene lines removed? 

Example of merged gtf (one exon per gene is true for all the genes) 
chr1	StringTie	transcript	11869	14412	1000	+	.	gene_id "MSTRG.1"; transcript_id "ENSG00000223972.4"; gene_name "DDX11L1"; ref_gene_id "ENSG00000223972.4"; 
chr1	StringTie	exon	11869	14412	1000	+	.	gene_id "MSTRG.1"; transcript_id "ENSG00000223972.4"; exon_number "1"; gene_name "DDX11L1"; ref_gene_id "ENSG00000223972.4"; 
chr1	StringTie	transcript	11869	14409	1000	+	.	gene_id "MSTRG.1"; transcript_id "ENST00000456328.2"; gene_name "DDX11L1"; ref_gene_id "ENSG00000223972.4"; 
chr1	StringTie	exon	11869	12227	1000	+	.	gene_id "MSTRG.1"; transcript_id "ENST00000456328.2"; exon_number "1"; gene_name "DDX11L1"; ref_gene_id "ENSG00000223972.4"; 
chr1	StringTie	exon	12613	12721	1000	+	.	gene_id "MSTRG.1"; transcript_id "ENST00000456328.2"; exon_number "2"; gene_name "DDX11L1"; ref_gene_id "ENSG00000223972.4"; 
chr1	StringTie	exon	13221	14409	1000	+	.	gene_id "MSTRG.1"; transcript_id "ENST00000456328.2"; exon_number "3"; gene_name "DDX11L1"; ref_gene_id "ENSG00000223972.4"; 
chr1	StringTie	transcript	11872	14412	1000	+	.	gene_id "MSTRG.1"; transcript_id "ENST00000515242.2"; gene_name "DDX11L1"; ref_gene_id "ENSG00000223972.4"; 
chr1	StringTie	exon	11872	12227	1000	+	.	gene_id "MSTRG.1"; transcript_id "ENST00000515242.2"; exon_number "1"; gene_name "DDX11L1"; ref_gene_id "ENSG00000223972.4"; 
chr1	StringTie	exon	12613	12721	1000	+	.	gene_id "MSTRG.1"; transcript_id "ENST00000515242.2"; exon_number "2"; gene_name "DDX11L1"; ref_gene_id "ENSG00000223972.4"; 
chr1	StringTie	exon	13225	14412	1000	+	.	gene_id "MSTRG.1"; transcript_id "ENST00000515242.2"; exon_number "3"; gene_name "DDX11L1"; ref_gene_id "ENSG00000223972.4";

**Comment by gpertea** [comment]
Ouch, you're correct, and unfortunately this seems to be a dumb regression bug -- even gencode.v20 is affected, again..
Yes, a quick workaround for now is to simply discard all those "gene" features from the file, their IDs are preserved in the gene_id for the transcripts anyway.

**Comment by gpertea** [comment]
Release v1.3.3b should took care of this.
