### ISSUE TITLE
How to extract longest isoform per transcripts

### ISSUE THREAD

**Issue by yogeshgupt** [gpertea/stringtie#107]
Please suggest how I can extract longest isoform or merge all isofrom into single transcripts from StringTie assembly.

**Comment by gpertea** [comment]
Sure. You could follow the easy steps of a precious recipe that goes like this:

**Step 1**. Learn Perl or Python, or other scripting/programming language
**Step 2.** Write a script/program using the skills acquired in Step 1
**Step 3.** Profit! (this step is highly unlikely, thus optional)

Now seriously, for getting the longest isoform I would probably write a script, as I don't know of any tool/script which does this -- but there may very well be something like this out there. As for merging all isoforms into single transcripts.. no, I have no idea if a tool/script doing this would even have a reason to exist.
