### ISSUE TITLE
Gene abundance estimates contain duplicate gene entries

### ISSUE THREAD

**Issue by AHPool** [gpertea/stringtie#111]
I'm using Stringtie version 1.3.3b and encountered the following issue. Namely I am trying to get gene abundance estimates from a mouse RNA-seq dataset that I have aligned to the mouse genome/transcriptome with Hisat2. However upon transcript assembly with Stringtie I get duplicate/multiple entries for several genes in the gene abundance estimates tab file (parameter -A). These entries have identical Ensembl ID-s and names but interestingly different expression estimates and slightly different genomic locations. Why wouldn't Stringtie aggregate that to a single gene expression estimate?

![image](https://cloud.githubusercontent.com/assets/26987722/24781581/89a3a840-1af5-11e7-9976-1fea7b6c7e30.png)

A few more details for background:
* The command I ran is as follows: stringtie sample1_sorted.bam -p 4 -G Mus_musculus.GRCm38.84.gtf -e -o stringtie_output/stdout.gtf -A stringtie_output/gene_abundance.tab -B
* Prior to running transcript assembly I used Hisat2 to align my sequencing reads to the mouse genome using pre-built Hisat2 mouse indexes (mouse genome_tran indexes downloaded from: https://ccb.jhu.edu/software/hisat2/index.shtml). For the hisat2 read alignment I used the following command: hisat2 -p 4 --dta --phred33 --met-file metrics -x genome_tran -U sample1_processed.fastq -S ./sample1_processed.sam

Any help would be much appreciated. Thanks ahead!

**Comment by gpertea** [comment]
StringTie defines a *gene locus* as a region where transcripts' exons actually overlap (transitively), on the same strand. If you look at ENSMUSG00000100826's transcripts in that GRCm38.84 file you'll see that they do not overlap to span such a single *contiguous* region. Now perhaps there is a good reason those non-overlapping transcripts are still considered as part of the same gene/locus, but nevertheless StringTie cannot afford to trust those gene_id labels given in the reference annotation (as we know they can be sometimes meaningless (UCSC gtf), or even perhaps careless duplicates etc.) and instead StringTie determines gene loci based solely on the "evidence",  i.e. exonic overlaps,  and it then estimates the abundance for each such *well defined* region.

In that file generated by -A, the expression is given by gene loci *uniquely identified* by the combination between the gene_id *and* the start-end coordinates, not just the gene_id, for the reasons presented above. If you really trust that those gene loci are/should be identified by just the gene_id, you can write a script to simply sum up the expression values for all the rows with the same gene_id.

**Comment by AHPool** [comment]
Excellent, thank you for the quick reply! I'll just sum the expression estimates as this should be fine for my purposes.
