### ISSUE TITLE
Stringtie does not always add gene_name?

### ISSUE THREAD

**Issue by sytrobertson** [gpertea/stringtie#113]
I have added gene_name s to the original Refseq genome annotation file from UCSC, but when I run Stringtie and Ballgown, there are some genes/transcripts that don't have their gene_name added and only MSTRG id is there. This includes genes that I know are highly expressed - when I go into the UCSC browser and input the chromosome locations of the MSTRG, it brings the gene I expected, but Stringtie did not add the gene_name. I expect this is because there are a few bases off on the 5' or 3' ends in the aligned reads (which I get from HISAT2). Is there a way that I can ensure that Stringtie will assign the gene_name to the MSTRG without having to go through the Ballgown files and manually add the missing gene names?

**Comment by sekang2** [comment]
I'm having the same issue. The reference gtf file has all the gene names and ID, but when I run it through Stringtie-Ballgown I only get MSTRG id. After running the Stringtie assembly step the output gtf file labels gene_name and ID as follows: gene_id "50C3.1"; transcript_id "50C3.1.1" 50C3 is the label.

This is using stringtie/1.3.3b where I thought the issue had been fixed.

**Comment by akesarwani** [comment]
Similar issue stays with me. I assembled multiple file using gencode GTF with -G option, and then merged the all assemblies to get a master GTF. I also don't see the ref gene names and id, rather MSTG id.

**Comment by gpertea** [comment]
An "obvious overlap" by itself might not be enough to safely transfer the ref gene names to StringTie output. But I do agree that we should still expose the ref gene name if there is there is no ambiguity about it (i.e. if there is only one ref gene overlapping that merged transcript).

**Comment by akesarwani** [comment]
if any novel transcript is falling within the annotated gene region on the same strand, then it should be assigned to that, which is not the case with stringtie at the moment.

**Comment by sytrobertson** [comment]
I ended up writing a Python script to add the gene name to the output from Ballgown, though it does require that at least one transcript be labeled with the gene name so that the MSTRG identifier still connects with a gene name. It's not perfect and not good with identifying a transcript, but it works for the gene level.

My guess is stringtie doesn't add the name in case it identifies a fusion gene or novel exon/transcript/etc?

**Comment by akesarwani** [comment]
I am using master.gft as input for splicing analysis. So, I am not sure how your script could be useful for my purpose.

**Comment by xxz19900** [comment]
Have anyone resolved this issue?

**Comment by sytrobertson** [comment]
I ended up writing a python script to go back and add the gene name based
on the MSTRG identifier. It does require that at least 1 transcript has the
gene name added by stringtie.

**Comment by gpertea** [comment]
Until I add more annotation functionality to stringtie's output (i.e. to show reference gene info for any assemblies overlapping them), there are some post-processing options that could be used to attach more meaning to the dreaded MSTRG gene IDs, before performing further analysis using the "merged" GTF file.
In a similar manner to the python script suggested above, one can also make use of the small perl script I suggested in issue #179 : 
https://gist.github.com/gpertea/b83f1b32435e166afa92a2d388527f4b

The downside of that script (besides the caveat @sytrobertson already mentioned) is that it should be run on the *merged.gtf* file (obtained after running the `stringtie --merge` step) __before__ launching the round of `stringtie -e` runs for each sample -- because those runs should be using the "processed" merged.gtf generated by the script above, instead of the original *merged.gtf* file. All that script does is simply appending to the MSTRG gene_id any *ref_gene_id* identifiers found for that gene/locus (as sometimes it could be more than one reference gene id getting entangled in there). See the 2nd comment there in #179 for more details about that mini script -- it may not help your particular case..

**Comment by WilsonBioinfo** [comment]
I am having this exact issue. Would you be willing to share your python script here, sytrobertson?

**Comment by gpertea** [comment]
Just curious, the above perl script does not work for you? Or perl scripts have really fallen into disgrace nowadays in the world of python domination ? :)

**Comment by WilsonBioinfo** [comment]
@gpertea, I have very little experience with perl, so interpreting that script and how/what to modify is daunting lol.

**Comment by gpertea** [comment]
I wrote a rough python translation of the above perl script:
https://gist.github.com/gpertea/4207fa9cb30fe7fec0eb52bd29b9a976#file-mstrg_prep-py

**Comment by sytrobertson** [comment]
I think @gpertea 's script is cleaner, I brute force-d my way through my
code but it does the trick. It takes a csv file exported from ballgown and
a file with just MSTRG, accession #, and gene names I generated separately
by using regex functions similar to what gpertea has. See the comments in
the script.

https://gist.github.com/sytrobertson/773ba0d37c9f8acfa377baa6a34cf4d0

**Comment by gpertea** [comment]
Just a quick note:  found that my script generated inconsistent gene_id entries in some cases (yeah, exactly what's needed here!) so I updated my gists above to correct that (both perl and python versions).

**Comment by WilsonBioinfo** [comment]
@gpertea, great thanks! I'm trying your updated python script now and I continue to receive errors. It looks like my python skills are less robust than I thought (I'm very new to computational biology). All of your help has been greatly appreciated.

**Comment by WilsonBioinfo** [comment]
@gpertea I hate to continue to bother you, but with your above python script, what exactly must the user add/modify? Is the input file simply modified, or is there a new output file after running the script?

**Comment by gpertea** [comment]
As explained in https://github.com/gpertea/stringtie/issues/179#issuecomment-395860049 , the idea was to use the script on the output of `stringtie --merge`, which is a GTF file (let's call it _merged.gtf_)  and from it generate a "processed" gtf output (at stdout) which transforms the 'gene_id' attribute to include one or more reference gene_ids (or gene_name, if the script), if any were found to match any of the transcripts assembled there. There is a "usage" comment as the 2nd line of that gist suggesting the command line:
    
    mstrg_prep.py merged.gtf > merged_prep.gtf

The input file is not directly modified -- a new gtf file is produced at stdout (captured as *merged_prep.gtf* in the example above), and that's the one that should be used with `-G` option for the subsequent runs of `stringtie -e` for each sample.

**Comment by WilsonBioinfo** [comment]
@gpertea, after successfully running your python script on a PC, the original issue still persists. Is the user supposed to modify anything in your script?

**Comment by gpertea** [comment]
If you are specifically after *gene_name*, you could comment out this line:
`mrn = re.search('ref_gene_id "([^"]+)', t[8])`
and uncomment the regex match below, like this:
`mrn = re.search('gene_name "([^"]+)', t[8])`

However this might still not capture the *gene_name* for cases where there is no exact match between a StringTie transcript and any reference transcripts of that gene..  The quickest way for me to fully address this at this point, without complicating StringTie's code and potentially slowing it down unnecessarily, I will add a couple of new output options to [gffcompare](http://ccb.jhu.edu/software/stringtie/gffcompare.shtml)'s "annotation" mode as to assign proper reference `gene_name` values when they are missing and optionally append them (or ref_gene_ids) to each transcript's gene_id attribute, so those can show up in any downstream gene abundance analysis..

**Comment by HaleDM** [comment]
@gpertea, I have a similar issue that was partly remedied by your perl script -- I can run the perl script on the .GTF output that results from the 2nd pass assembly (with merged.gtf), and it will append "ref_gene_name", if present, onto the end of MSTRG identifiers. But manually inspecting the output shows that for some transcripts, the information to append is actually listed under "gene_name" and thus doesn't get added. Is there a way to add both/either? And is there a substantive different between the two, "ref_gene_name" and "gene_name", or is this just a semantic difference? These annotations are coming from RefSeq.

**Comment by swiddison** [comment]
When running an unstranded RNA-seq protocol you often get novel Stringtie genes on the opposite strand to a gene from a provided gtf file gene (class codes s and x). These get the corresponding gene from the reference gtf file as 'gene_name' in the merged.annotated.gtf. However. the script above (issue #179 :https://gist.github.com/gpertea/b83f1b32435e166afa92a2d388527f4b) only annotates Stringtie genes which are on the same strand with the reference id but not those that appear on the opposite strand. For unstranded RNA-Seq it would be good to be able to transfer reference ids to the genes on the opposite strand too but I guess we would have to do that manually?

**Comment by Mithil15** [comment]
> Until I add more annotation functionality to stringtie's output (i.e. to show reference gene info for any assemblies overlapping them), there are some post-processing options that could be used to attach more meaning to the dreaded MSTRG gene IDs, before performing further analysis using the "merged" GTF file.
> In a similar manner to the python script suggested above, one can also make use of the small perl script I suggested in issue #179 :
> https://gist.github.com/gpertea/b83f1b32435e166afa92a2d388527f4b
> 
> The downside of that script (besides the caveat @sytrobertson already mentioned) is that it should be run on the _merged.gtf_ file (obtained after running the `stringtie --merge` step) **before** launching the round of `stringtie -e` runs for each sample -- because those runs should be using the "processed" merged.gtf generated by the script above, instead of the original _merged.gtf_ file. All that script does is simply appending to the MSTRG gene_id any _ref_gene_id_ identifiers found for that gene/locus (as sometimes it could be more than one reference gene id getting entangled in there). See the 2nd comment there in #179 for more details about that mini script -- it may not help your particular case..

I am unable to run this perl script successfully, It is entering into an infinite loop, Perhaps, because I am mising some important modification in the script, could you please suggest any modifications,if any? Except the inputfilename( in the Usage line), i haven't modified anything here. Any help in this regard is deeply appreciated.

**Comment by Stemanz** [comment]
> All that script does is simply appending to the MSTRG gene_id any _ref_gene_id_ identifiers found for that gene/locus (as sometimes it could be more than one reference gene id getting entangled in there).

While I was myself dealing with the issue of pulling the gene_names form the stringtie_merged.gtf file, I realized that in my case 412 MSTRG ids (out of 20k+) clashed against multiple gene ids (abridged):

![Screenshot 2019-05-22 at 14 35 38](https://user-images.githubusercontent.com/7668172/58174856-1fff9a80-7c9f-11e9-848e-f7569ddc650a.png)

My simple question is: is this normal/expected? Should I be worried? How is this issue generally managed?

I have very old, short and non paired-end reads, that's probably the origin of the problem.

Thanks for any reply!

**Comment by NDUFB11** [comment]
Did the script worked for you? 
I tried but didn't changed compared before ..

**Comment by chahatupreti** [comment]
> The quickest way for me to fully address this at this point, without complicating StringTie's code and potentially slowing it down unnecessarily, I will add a couple of new output options to [gffcompare](http://ccb.jhu.edu/software/stringtie/gffcompare.shtml)'s "annotation" mode as to assign proper reference `gene_name` values when they are missing and optionally append them (or ref_gene_ids) to each transcript's gene_id attribute, so those can show up in any downstream gene abundance analysis..

Hi @gpertea , were you able to add this functionality to gffcomapre, and if so, would you recommend we go for that option rather than using the above Python code, for the case where merged.gtf doesn't have gene_names?

For me, NONE  of the rows in stringtie_merged.gtf has gene_name. Not sure why this is happening.

**Comment by sumageb** [comment]
Hello,
I am new in computational biology and using STAR for the alignment and Stringtie for the assembly. I want to compare the gene expression pattern between samples. I used the following command:
$ stringtie sample.sorted.bam -p 8 -G annotation_file.gtf -o sample.gtf -A sample_expr.tsv
I didn't receive any gene names in my tsv file. I am wondering how I can add the gene name in this file?
Any help would be highly appreciated.

**Comment by shnmunk** [comment]
Dear @gpertea, it appears that this issue can be fixed now by running GffCompare in annotation mode on the StringTie (merged) assembled transcriptome. 

From the GffCompare v0.11.5 update (8 Oct 2019), it looks like GffCompare from thereon adds `gene_name` and `ref_gene_id` from the reference annotation if missing (source: https://github.com/gpertea/gffcompare/commit/baaa2c0b2033e2c923d195ae830544a3d2f754c3).

Is this correct?

**Comment by gpertea** [comment]
Indeed that was the intent of that change, but I do not think it addresses all the issue raised in this topic (as the quantification of some transcripts is still problematic). 

That's because there are still cases where the `gene_name` cannot be uniquely determined (as a transfrag may overlap multiple reference genes). In such cases the `gene_name` assigned there by gffcompare is the one corresponding to the reference transcript that was found to have the _highest structural similarity_ to the transfrag being annotated. 

That "structural similarity" assessment can be quite complex (as explained in https://github.com/gpertea/gffcompare/issues/58#issuecomment-752968020). As seen there, the "best reference" does not always mean the highest base overlap, which does have implications for transcript->gene quantification based on such gene assignment.

**Comment by gpertea** [comment]
I realize now that the topic of quantification was never actually raised in _this_ thread -- in my mind somehow this was linked to other similar issues with Stringtie's output (especially with `--merge`) which were related to gene labeling and quantification downstream. I suppose just for assigning a `gene_name` to a (assembled) transcript, gffcompare is doing the job indeed, so I'll close this for now to avoid further confusion.
