### ISSUE TITLE
Support TPM

### ISSUE THREAD

**Issue by schelhorn** [gpertea/stringtie#14]
Are there any plans to support TPM in addition to FPKM as an estimator of relative abundance? I'd appreciate any single value that is comparable between samples - it doesn't have to be TPM, just free of scaling issues that depend on sequencing depth. I know that for differential expression analysis the consensus is to use raw counts and a discrete negative binomial model, but we often would like to quickly cluster samples for QC and hypothesis generation, and doing that directly from the stringtie output would be great.

**Comment by mpertea** [comment]
I am adding TPMs to our 'to do' list for the next version of StringTie.

**Comment by schelhorn** [comment]
Great, Thanks!

**Comment by mpertea** [comment]
TPMs are now added to transcript and gene estimations.

**Comment by schelhorn** [comment]
Sweet, thanks.
