### ISSUE TITLE
gene_count_matrix with short and long protocol of stringtie

### ISSUE THREAD

**Issue by zoewardnz** [gpertea/stringtie#147]
Hi,

I have ran StringTie with just the StringTie -eB pipeline and also the StringTie, StringTie merge and StringTie -eB pipeline on the same data and used the prepDE.py script to pull out the gene_count_matrix.csv.

When I compare the two matrices it looks as though StringTie is giving an MSTRG id erroneously?
For example a highly expressed gene from my sample.gtf for the short protocol is:
```
chrM    StringTie       transcript      1671    3229    1000    +       .       gene_id "ENSG00000210082.2"; transcript_id "ENST00000387347.2"; ref_gene_name "MT-RNR2"; cov "28.485565"; FPKM "7811.345703"; TPM "22528.871094";
chrM    StringTie       exon    1671    3229    1000    +       .       gene_id "ENSG00000210082.2"; transcript_id "ENST00000387347.2"; exon_number "1"; ref_gene_name "MT-RNR2"; cov "28.485565";
```
and after the longer protocol:
```
chrM    StringTie       transcript      1671    3229    1000    +       .       gene_id "MSTRG.13636"; transcript_id "ENST00000387347.2"; ref_gene_name "MT-RNR2"; cov "28.485565"; FPKM "6810.876465"; TPM "11890.248047";
chrM    StringTie       exon    1671    3229    1000    +       .       gene_id "MSTRG.13636"; transcript_id "ENST00000387347.2"; exon_number "1"; ref_gene_name "MT-RNR2"; cov "28.485565";

```
Therefore it is assigning the same transcript as a 'novel' transcript with the longer protocol when in fact it is the MT-RNR2 transcript??

**Comment by gpertea** [comment]
MSTRG.# is the ID assigned by StringTie in the ``merge`` step of the "long" protocol.  In that step there is an automatic assignment of such *unique IDs* to clusters of overlapping transcripts as these are discovered and processed by "assembling"/"merging" transcripts in that genomic region. Since we cannot simply go by the assumption that the user-provided gene IDs are unique and correctly identify a gene locus (i.e. uniquely identify such a cluster of overlapping transcripts in that region), we have to assign our own automatic gene (cluster) IDs.

**Comment by zoewardnz** [comment]
My issue is is that for some transcripts it gives the MSTRG ID, for others it retains the Ensembl ID. Eg
StringTie -eB gene count matrix:
```
chr11   StringTie       transcript      2608328 2699994 1000    -       .       gene_id "ENSG00000269821.1"; transcript_id "ENST00000597346.1"; ref_gene_name "KCNQ1OT1"; cov "0.029094"; FPKM "7.978192"; TPM "23.010075";
chr11   StringTie       exon    2608328 2699994 1000    -       .       gene_id "ENSG00000269821.1"; transcript_id "ENST00000597346.1"; exon_number "1"; ref_gene_name "KCNQ1OT1"; cov "0.029094";
chrM    StringTie       transcript      1671    3229    1000    +       .       gene_id "ENSG00000210082.2"; transcript_id "ENST00000387347.2"; ref_gene_name "MT-RNR2"; cov "28.485565"; FPKM "7811.345703"; TPM "22528.871094";
chrM    StringTie       exon    1671    3229    1000    +       .       gene_id "ENSG00000210082.2"; transcript_id "ENST00000387347.2"; exon_number "1"; ref_gene_name "MT-RNR2"; cov "28.485565";
```

StringTie, StringTie merge and StringTie -eB gene count matrix:
```
chr11   StringTie       transcript      2608328 2699994 1000    -       .       gene_id "ENSG00000269821.1"; transcript_id "ENST00000597346.1"; ref_gene_name "KCNQ1OT1"; cov "0.029094"; FPKM "6.956353"; TPM "12.144217";
chr11   StringTie       exon    2608328 2699994 1000    -       .       gene_id "ENSG00000269821.1"; transcript_id "ENST00000597346.1"; exon_number "1"; ref_gene_name "KCNQ1OT1"; cov "0.029094";
chrM    StringTie       transcript      1671    3229    1000    +       .       gene_id "MSTRG.13636"; transcript_id "ENST00000387347.2"; ref_gene_name "MT-RNR2"; cov "28.485565"; FPKM "6810.876465"; TPM "11890.248047";
chrM    StringTie       exon    1671    3229    1000    +       .       gene_id "MSTRG.13636"; transcript_id "ENST00000387347.2"; exon_number "1"; ref_gene_name "MT-RNR2"; cov "28.485565";
```

**Comment by zoewardnz** [comment]
My issue is is that for some transcripts it gives the MSTRG ID, for others it retains the Ensembl ID. Eg
StringTie -eB gene count matrix:

chr11   StringTie       transcript      2608328 2699994 1000    -       .       gene_id "ENSG00000269821.1"; transcript_id "ENST00000597346.1"; ref_gene_name "KCNQ1OT1"; cov "0.029094"; FPKM "7.978192"; TPM "23.010075";
chr11   StringTie       exon    2608328 2699994 1000    -       .       gene_id "ENSG00000269821.1"; transcript_id "ENST00000597346.1"; exon_number "1"; ref_gene_name "KCNQ1OT1"; cov "0.029094";
chrM    StringTie       transcript      1671    3229    1000    +       .       gene_id "ENSG00000210082.2"; transcript_id "ENST00000387347.2"; ref_gene_name "MT-RNR2"; cov "28.485565"; FPKM "7811.345703"; TPM "22528.871094";
chrM    StringTie       exon    1671    3229    1000    +       .       gene_id "ENSG00000210082.2"; transcript_id "ENST00000387347.2"; exon_number "1"; ref_gene_name "MT-RNR2"; cov "28.485565";
StringTie, StringTie merge and StringTie -eB gene count matrix:

chr11   StringTie       transcript      2608328 2699994 1000    -       .       gene_id "ENSG00000269821.1"; transcript_id "ENST00000597346.1"; ref_gene_name "KCNQ1OT1"; cov "0.029094"; FPKM "6.956353"; TPM "12.144217";
chr11   StringTie       exon    2608328 2699994 1000    -       .       gene_id "ENSG00000269821.1"; transcript_id "ENST00000597346.1"; exon_number "1"; ref_gene_name "KCNQ1OT1"; cov "0.029094";
chrM    StringTie       transcript      1671    3229    1000    +       .       gene_id "MSTRG.13636"; transcript_id "ENST00000387347.2"; ref_gene_name "MT-RNR2"; cov "28.485565"; FPKM "6810.876465"; TPM "11890.248047";
chrM    StringTie       exon    1671    3229    1000    +       .       gene_id "MSTRG.13636"; transcript_id "ENST00000387347.2";
