### ISSUE TITLE
What is the best way to extract fasta formatted transcript sequences?

### ISSUE THREAD

**Issue by lakhujanivijay** [gpertea/stringtie#151]
After assembling the transcriptome using `string-tie.` What is the best approach to extract fasta formatted sequences of the assembled transcripts from the output `GTF` files? 

I know there are a couple of external tools available which can extract the sequences provided the reference fasta file and a `bed` or `GTF` file. Just wanted to know if you recommend anything specific?

**Comment by gpertea** [comment]
I don't know about the *best* way, we just use the [gffread](http://ccb.jhu.edu/software/stringtie/gff.shtml#gffread) utility for stuff like this -- there is a "Extracting transcript sequences" paragraph there showing an example of command line options for that feature.

**Comment by spriyar** [comment]
> After assembling the transcriptome using `string-tie.` What is the best approach to extract fasta formatted sequences of the assembled transcripts from the output `GTF` files?
> 
> I know there are a couple of external tools available which can extract the sequences provided the reference fasta file and a `bed` or `GTF` file. Just wanted to know if you recommend anything specific?

Hi,
Please let me know if you were able to extract the fasta sequences using gffread.
Thanks

**Comment by lakhujanivijay** [comment]
Indeed I was able to do that.

**Comment by spriyar** [comment]
I tried to run use gff, but I run into the following error. Does this error look familiar?

Error (GFaSeqGet): subsequence cannot be larger than 465
Error getting subseq for gene1 (465..1503)!
