### ISSUE TITLE
Error: segmentation using string tie --merge

### ISSUE THREAD

**Issue by manuelsmendoza** [gpertea/stringtie#154]
Hi! 

I am trying to follow all "new tuxedo", now I want to make the transcripts poll (merging transcripts from all samples) but the output is the following:
```
$ head mergelist.txt 
/path_to/condA_sample01.gtf
/path_to/condA_sample02.gtf
/path_to/condB_sample01.gtf
/path_to/condB_sample02.gtf
...
```
```
$ stringtie --merge -p 12 -G /path_to/genome_annotation.gtf -o stringtie_merged.gtf mergelist.txt
79324 Segmentation fault      stringtie --merge -p 12 -G /path_to/genome_annotation.gtf -o stringtie_merged.gtf mergelist.txt
```

I have tried to do it in our cluster, first in interactive-mode and following in remote queue with the following sbatch config:
```
#SBATCH --nodes=1
#SBATCH --ntasks=12
#SBATCH --cpus-per-task=1
#SBATCH --mem=250G
#SBATCH --time=9:00:00
```

**Comment by gpertea** [comment]
Could you please provide details about this, how you fixed it/found out the cause? Was it related to the grid options used, or intrinsic to stringtie?
