### ISSUE TITLE
255 or 60 for uniquely mapped reads

### ISSUE THREAD

**Issue by roryk** [gpertea/stringtie#155]
Hi Geo,

Hope all is well-- I poked around and couldn't find the answer to this anywhere, is StringTie using the Cufflinks-style MAPQ 255 value for calling uniquely mapped reads, or 60 or neither? Thanks!

**Comment by gpertea** [comment]
StringTie doesn't use MAPQ at all, instead it uses the NH tag to determine if a read is multi-mapped (and in how many places..). So if NH is 0 (i.e. not present), unique mapping is assumed -- and now that you mentioned it, this seems like a potential problem.. as we're really counting on the aligner to provide this info (the NH tag). Hence the strong dependency on "healthy" aligners like HISAT2.

**Comment by roryk** [comment]
Thanks Geo! That is super helpful. Huh-- there aligners that don't spit out the NH tag?

**Comment by shreygandhi1990** [comment]
Hey Geo, 

I was curious to know that how does StringTie deal with read pairs mapping to different chromosomes? If StringTie doesn't take into account the MAPQ scores, then do you recommend to pre-filter such reads(or in any case reads of bad quality)?

**Comment by gpertea** [comment]
These are currently treated as separated mappings -- i.e. as single read mappings, no pairing link is considered between them.
Filtering of bad/dubious/low quality mappings is always recommended.. However in this case, assuming there is no actual chromosomal fusion going on, I think the impact of such unlikely mappings would be minimal (considering that they are treated as independent mappings by StringTie).

**Comment by shreygandhi1990** [comment]
Thanks :)
