### ISSUE TITLE
How to deal with multi-mapped hits for FPKM using Guided annotation

### ISSUE THREAD

**Issue by vsmalladi** [gpertea/stringtie#160]
There is a discrepancy of the number of read counts between featureCounts and stringTie based on multimapping reads. Can you describe how -M option is used for Guided annotation?

**Comment by gpertea** [comment]
I think these are two separate issues. First let's get ```-M``` out of the way: that's a simple filtering option which tells StringTie to simply ignore (discard) bundles that are mostly multi-mapped reads (default: over 95% of reads are multimapped). It doesn't matter if those bundles are "guided" or not.  If the percentage of multi-mapped reads is below or equal to the ```-M``` value, then the "coverage" estimates are going to be generated -- but keep in mind that for StringTie the coverage contribution of a multimapped read is a fractional value, as the "coverage" is split between (i.e. divided by the number of) the places where the read was mapped.

Getting back to the first issue you raised: not sure what StringTie read counts you are looking at (those generated by the prepDE script I presume?). The coverage and FPKM values found in the GTF output (which is what prepDE uses as well) are indeed *estimates* based on the flow network model employed by StringTie and as such it's expected that they are not going to match the values of simple raw counting programs like ```featureCounts``` (or the raw counts produced by the -B option currently), especially in the case of genes with alternative isoforms. Additionally, as I explained above, multimapped read counts are only counted as a fraction (their coverage contribution is divided by the number of places they are mapped). I do not know if ```featureCounts``` applies the same "correction" for multimapped reads.
