### ISSUE TITLE
Probable issue in script prepDE.py

### ISSUE THREAD

**Issue by ag1805x** [gpertea/stringtie#167]
I am trying to execute [prepDE.py](http://ccb.jhu.edu/software/stringtie/dl/prepDE.py) script but I am getting the following errors:

**- On using Python 3.5.2**

```
$python3 prepDE.py --help
  File "prepDE.py", line 29
    print "Error: Text file with sample ID and path invalid (%s)" % (line.strip())
                                                                ^
SyntaxError: invalid syntax
```

**- On using Python 2.5.6** 
```
$python prepDE.py --help
prepDE.py:130: Warning: 'with' will become a reserved keyword in Python 2.6
  File "prepDE.py", line 130
    with open(s[1]) as f:
            ^
SyntaxError: invalid syntax
```
Both says syntax error but I am unable to identify the actual source. 

Edit: I tried running as root and it worked well.

```
$ sudo python prepDE.py -i sample.txt
0 SRR3084933
1 SRR3084934
2 SRR3084953
3 SRR3084954
```

**Comment by gpertea** [comment]
prepDE.py is a Python 2 script (the first line in the script strongly suggests that, as it's looking for the python2 executable), so indeed it is not meant to work with python 3.
Version 2.5 is rather an useless relic these days, while version 2.7 has been the mainstream Python 2 version for several years now. I think even legacy systems like RedHat/CentOS 5 have some package builds for it.  I just added a few lines in the `prepDE.py` script do enforce the 2.7 requirement. (It might actually work on 2.6 too but we've only tested it on 2.7)
