### ISSUE TITLE
MIR tag, what does it mean?

### ISSUE THREAD

**Issue by hsinyenwu** [gpertea/stringtie#168]
Hi,
From stringtie merge output gtf, the column 9 of most genes are like **gene_id MSTRG.17; transcript_id MSTRG.17.2;** and fewer others are like **gene_id MSTRG.76; transcript_id MIR2112; ref_gene_id MIR2112;**. I believe they all new transcripts, but could you please let me know what is the difference between MIR and MSTRG in transcript_id? Thanks!!!
Hsinyen

**Comment by gpertea** [comment]
I am pretty sure that is a transcript ID coming from the reference annotation file you used in the merge. That is likely a reference transcript that wasn't found to merge with any other transcripts so StringtTie just copied it over (obviously preserving the transcript ID). MIR# usually suggests a micro-RNA (http://www.mirbase.org/cgi-bin/mirna_summary.pl?fam=MIPF0001195 in this case, I guess)

**Comment by hsinyenwu** [comment]
You are correct. These are the miRNA genes. I don't know why they named it differently in the genome reference. Normally it should be something like "AT1G01010". Many thanks for your help!!!
