### ISSUE TITLE
error with -eA and merged_gtf file

### ISSUE THREAD

**Issue by ChiWPak** [gpertea/stringtie#171]
Hi:
Sorry if this was posted previously - I merged Stringtie GTF files into a merged GTF file - using

`stringtie --merge -i -G $gtf -o $merged $input`

I then tried to count abundances with

`stringtie -eA -G $merged -o $counts $input`

but this fails. Using `-eB` works fine however. Is there a reason `-A` is not supported, but `-B` (Ballgown) is?

**Comment by gpertea** [comment]
Ah, I see that the usage message is confusing about this option, as it looks like a flag, but in fact the -A option must be followed by a file name which would be created by StringTie and the gene abundances table will be written to that file. So the correct usage would be:

`
stringtie -e -A genes_expr.tab -G $merged -o transcripts_expr.gtf $input
`

Sorry for the confusion in the usage message. The online manual makes the usage of this option much clearer and explains the format of that optional output file.
