### ISSUE TITLE
running with --dta did not produce XS tag

### ISSUE THREAD

**Issue by tenger-github** [gpertea/stringtie#181]
Dear , When I ran Hisat2 (version: 2.1.0) with --dta ( --downstream-transcriptome-assembly OR --dta-cufflinks), there was no XS tag in output file.  I did not know how to fix it.
Thank you very much!

**Comment by gpertea** [comment]
This seems very unlikely -- though I guess it's possible to happen if there were no spliced alignments at all (which would be strange). In any case, this seems to be an aligner (or aligner usage) issue (HISAT2), not a StringTie issue..
