### ISSUE TITLE
Coverage inaccuracy from samtools

### ISSUE THREAD

**Issue by jupiler55** [gpertea/stringtie#187]
The coverage reported by stringtie seems to be generated from "samtools depth", which by default only considers up to 8,000 reads at each position.  We have regions with much higher coverage and are thus getting inaccurate count.  StringTie doesn't seem to have an option to pass a parameter to "samtools depth -d", which sets the max coverage.  Requesting such option.

**Comment by jupiler55** [comment]
Also, does this mean FPKM and TPM are also currently wrong - if they are based on coverage - for positions >8k reads?

**Comment by mpertea** [comment]
The coverage reported by StringTie is not generated from samtools depth.

**Comment by jupiler55** [comment]
it matches the numbers generated by samtools depth with default setting capped at 8k.    samtools depth -d 99999999 shows the actual coverage.

**Comment by jupiler55** [comment]
oops, I goofed.  I was comparing one transcript reported by StringTie against reads for multiple transcripts.  The numbers just happen to resemble the various aforementioned options.  Sorry!
