### ISSUE TITLE
StringTie not observing key transcripts

### ISSUE THREAD

**Issue by hhg7** [gpertea/stringtie#191]
Hello,

I've been using StringTie on single-end RNA-Seq data run like `stringtie $bam -G $gtf -A $tab -o $out -c 1 -B 2> $err` but no matter what minimum coverage I use, important marker transcripts all have a coverage of 0.  These transcripts are key, as they show up as differentially expressed when I use featureCounts & EdgeR.  What can I do so stringtie detects these transcripts?

thanks

**Comment by gpertea** [comment]
Are those 'marker transcripts' in the  `$gtf` file passed with the `-G` option ? If so, it is possible that a novel alternative transcript (isoform) was found as a better "owner" of those alignments.. (possible isoform switching?). Can you take a look in such a region with IGV or something to see what other transcripts have been generated in that region? 
 
But if the target transcript is not in the `-G` file and it is also missing from the output of stringtie (yet somehow you know it should be there), this can happen when most of the reads mapped in that region are multi-mapped (i.e. also mapped in other places on the genome.. which can happen for duplicate genes or if that gene is also on one of the "alternative" contigs in the genome file). In this case running with option `-M 1`  it should force stringtie to assemble such transcripts, so they should appear in the output. Coverage estimates produced by StringTie in such cases will be lower than expected, but this should not be an issue if you are going to use EdgeR or other feature counting methods for that. 
So I am a bit confused about the title suggesting that Stringtie is "not observing" a transcript, but after that you write that stringtie produces an estimated coverage of 0 for that transcript. So is that transcript in the output but with 0 coverage? (and you did *not* use the `-e` option, right?).

**Comment by hhg7** [comment]
thanks Geo, it appears that "-e" was the key here.
