### ISSUE TITLE
stringtie not recognizing gff or gtf

### ISSUE THREAD

**Issue by vin6** [gpertea/stringtie#194]
Hello,
I'm trying to run stringtie with a reference genome, and I'm getting the following error:

WARNING: no reference transcripts were found for the genomic sequences where reads were mapped!
Please make sure the -G annotation file uses the same naming convention for the genome sequences.

Similar posts indicate that there is some inconsistency between the reference genome fasta file that was used in the hisat2 step and the gff3 or gtf file that is used for stringtie. I can't see any inconsistency in my case. I'm stumped. I've remade the hisat2 index files and redone the alignment, but unsurprisingly that didn't change anything. When I run stringtie without the reference genome flag and look at that output, I can see that mapped reads do in fact occur within annotated transcripts.

My stringtie command:
`stringtie 585_10CR_1.bam -p 8 -B -G Mlong585_v3.01.gff -o 585_10CR_1.gtf 
`
The reference genome fasta headers look like this:
```
>scaffold_1_length_46699537
>scaffold_2_length_45526029
>scaffold_3_length_45460755
>scaffold_4_length_44284954
>scaffold_5_length_43231337
```
   

The first few lines of the gff look like this:
```
##gff-version 3
scaffold1_length_46699537       .       contig  1       46699537        .       .       .       ID=scaffold1_length_46699537;Name=scaffold1_length_46699537
scaffold1_length_46699537       maker   gene    1701    4304    .       -       .       ID=Mlong585_00001;Name=Mlong585_00001;Alias=augustus-scaffold1_length_46699537-processed-gene-0.17;
scaffold1_length_46699537       maker   mRNA    1701    4304    .       -       .       ID=Mlong585_00001-RA;Parent=Mlong585_00001;Name=Mlong585_00001-RA;Alias=augustus-scaffold1_length_46699537-processed-gene-0.17-mRNA-1;_AED=1.00
scaffold1_length_46699537       maker   exon    1701    3837    .       -       .       ID=Mlong585_00001-RA:exon:78;Parent=Mlong585_00001-RA;
scaffold1_length_46699537       maker   CDS     1701    3837    .       -       1       ID=Mlong585_00001-RA:cds;Parent=Mlong585_00001-RA;
scaffold1_length_46699537       maker   exon    4012    4097    .       -       .       ID=Mlong585_00001-RA:exon:79;Parent=Mlong585_00001-RA;
scaffold1_length_46699537       maker   CDS     4012    4097    .       -       0       ID=Mlong585_00001-RA:cds;Parent=Mlong585_00001-RA;
scaffold1_length_46699537       maker   CDS     4173    4304    .       -       0       ID=Mlong585_00001-RA:cds;Parent=Mlong585_00001-RA;
scaffold1_length_46699537       maker   exon    4173    4304    .       -       .       ID=Mlong585_00001-RA:exon:80;Parent=Mlong585_00001-RA;
scaffold1_length_46699537       maker   gene    4819    8990    .       +       .       ID=Mlong585_00002;Name=Mlong585_00002;Alias=snap-scaffold1_length_46699537-processed-gene-0.25;
scaffold1_length_46699537       maker   mRNA    4819    8990    .       +       .       ID=Mlong585_00002-RA;Parent=Mlong585_00002;Name=Mlong585_00002-RA;Alias=snap-scaffold1_length_46699537-processed-gene-0.25-mRNA-1;_AED=1.00;_QI
scaffold1_length_46699537       maker   exon    4819    6558    .       +       .       ID=Mlong585_00002-RA:exon:48;Parent=Mlong585_00002-RA;
scaffold1_length_46699537       maker   CDS     4819    6558    .       +       0       ID=Mlong585_00002-RA:cds;Parent=Mlong585_00002-RA;
scaffold1_length_46699537       maker   CDS     7278    7432    .       +       0       ID=Mlong585_00002-RA:cds;Parent=Mlong585_00002-RA;
scaffold1_length_46699537       maker   exon    7278    7432    .       +       .       ID=Mlong585_00002-RA:exon:49;Parent=Mlong585_00002-RA;
scaffold1_length_46699537       maker   CDS     7462    7531    .       +       1       ID=Mlong585_00002-RA:cds;Parent=Mlong585_00002-RA;
scaffold1_length_46699537       maker   exon    7462    7531    .       +       .       ID=Mlong585_00002-RA:exon:50;Parent=Mlong585_00002-RA;
scaffold1_length_46699537       maker   CDS     7567    7629    .       +       0       ID=Mlong585_00002-RA:cds;Parent=Mlong585_00002-RA;
scaffold1_length_46699537       maker   exon    7567    7629    .       +       .       ID=Mlong585_00002-RA:exon:51;Parent=Mlong585_00002-RA;
scaffold1_length_46699537       maker   CDS     7639    7974    .       +       0       ID=Mlong585_00002-RA:cds;Parent=Mlong585_00002-RA;
scaffold1_length_46699537       maker   exon    7639    7974    .       +       .       ID=Mlong585_00002-RA:exon:52;Parent=Mlong585_00002-RA;
scaffold1_length_46699537       maker   CDS     8000    8056    .       +       0       ID=Mlong585_00002-RA:cds;Parent=Mlong585_00002-RA;
scaffold1_length_46699537       maker   exon    8000    8056    .       +       .       ID=Mlong585_00002-RA:exon:53;Parent=Mlong585_00002-RA;
scaffold1_length_46699537       maker   CDS     8800    8856    .       +       0       ID=Mlong585_00002-RA:cds;Parent=Mlong585_00002-RA;
scaffold1_length_46699537       maker   exon    8800    8856    .       +       .       ID=Mlong585_00002-RA:exon:54;Parent=Mlong585_00002-RA;
scaffold1_length_46699537       maker   CDS     8958    8990    .       +       0       ID=Mlong585_00002-RA:cds;Parent=Mlong585_00002-RA;
scaffold1_length_46699537       maker   exon    8958    8990    .       +       .       ID=Mlong585_00002-RA:exon:55;Parent=Mlong585_00002-RA
```

**Comment by jerryguintivano** [comment]
Hello,

I am having a similar issue to the one above. My apologies if this should be a new issue.

I am using reference fasta and GTFs from ensembl build grch37.87 for all histat2/stringtie steps. I have checked to ensure that naming conventions are the same throughout. However, I still get these repeated warnings:

> WARNING: no reference transcripts found for genomic sequence "ENST00000590737.1"! (mismatched reference names?)
> WARNING: no reference transcripts found for genomic sequence "ENST00000575999.1"! (mismatched reference names?)
> WARNING: no reference transcripts were found for the genomic sequences where reads were mapped!
> Please make sure the -G annotation file uses the same naming convention for the genome sequences.

Is this typical behavior? Or is there something I have missed?

Thanks for the help!

**Comment by gpertea** [comment]
ENST00000590737.1 is a Ensembl transcript name.. Have you by any chance used their transcriptome FASTA file (with the sequences of all transcripts) instead of the genome sequence (sequences of all chromosomes)? I agree that aligning reads to the transcriptome is a good idea -- but you should use TopHat for that, or another program that can convert the transcriptome mappings into genome alignments.. Stringtie can only be used with read **alignments to the genome**.

**Comment by jerryguintivano** [comment]
I see what I did now. Just used the wrong FASTA files at the start. Thank you for this!

**Comment by Akashanil-akh** [comment]
i was trying to get transcript file using stringtie then error occured
stringtie output_sorted_bam -o transcripts_gtf -G Piper_nigrum.gff3 -A assembly.txt
WARNING: no reference transcripts were found for the genomic sequences where reads were mapped!
Please make sure the -G annotation file uses the same naming convention for the genome sequences.

these are first few lines of my annotation file
##gff-version 3
##sequence-region Pn1 10842 48451839
##sequence-region Pn10 22 31230699
##sequence-region Pn11 16692 29812213
##sequence-region Pn12 6065 29594990
##sequence-region Pn13 59489 29413843
##sequence-region Pn14 9 29032505
##sequence-region Pn15 36 28679057
##sequence-region Pn16 88635 27941856
##sequence-region Pn17 349 25719581
##sequence-region Pn18 3990 25553251
##sequence-region Pn19 49417 24747179
##sequence-region Pn2 6080 43094291
##sequence-region Pn20 20749 24277803
##sequence-region Pn21 6512 22245691
##sequence-region Pn22 10059 22164280
##sequence-region Pn23 553 20429441
##sequence-region Pn24 19792 19852818
##sequence-region Pn25 19625 18169662
##sequence-region Pn26 2028 14905565
##sequence-region Pn27 24450 29100
##sequence-region Pn28 10251 30138
##sequence-region Pn29 23182 23388
##sequence-region Pn3 2076 39384549
##sequence-region Pn30 7548 45795
##sequence-region Pn31 2285 44841
##sequence-region Pn32 42295 44975
##sequence-region Pn33 32 39541
##sequence-region Pn34 3251 37613
##sequence-region Pn35 30082 30705
##sequence-region Pn36 8072 17617
##sequence-region Pn37 2184 2625
##sequence-region Pn38 28595 29943
##sequence-region Pn39 398 28143
##sequence-region Pn4 8302 37185481
##sequence-region Pn40 16554 17240
##sequence-region Pn41 5430 14288
##sequence-region Pn42 10727 14243
##sequence-region Pn43 22260 22871
##sequence-region Pn44 3390 9887
##sequence-region Pn45 7058 30162
##sequence-region Pn5 157 36774355
##sequence-region Pn6 6382 33605596
##sequence-region Pn7 2534 32736002
##sequence-region Pn8 44 32719039
##sequence-region Pn9 128 32482198
Pn1 EVM mRNA 10842 11267 . + . ID=evm.model.Pn1.1
Pn1 EVM exon 10842 11267 . + . ID=evm.model.Pn1.1.exon1;Parent=evm.model.Pn1.1
Pn1 EVM CDS 10842 11267 . + 0 ID=cds.evm.model.Pn1.1;Parent=evm.model.Pn1.1

Pn1 EVM mRNA 19952 20188 . + . ID=evm.model.Pn1.2
Pn1 EVM exon 19952 20188 . + . ID=evm.model.Pn1.2.exon1;Parent=evm.model.Pn1.2
Pn1 EVM CDS 19952 20188 . + 0 ID=cds.evm.model.Pn1.2;Parent=evm.model.Pn1.2

Pn1 EVM mRNA 67496 68035 . - . ID=evm.model.Pn1.3
Pn1 EVM exon 67496 68035 . - . ID=evm.model.Pn1.3.exon1;Parent=evm.model.Pn1.3
Pn1 EVM CDS 67496 68035 . - 0 ID=cds.evm.model.Pn1.3;Parent=evm.model.Pn1.3

Pn1 EVM mRNA 68921 69345 . - . ID=evm.model.Pn1.4
Pn1 EVM exon 68921 69087 . - . ID=evm.model.Pn1.4.exon2;Parent=evm.model.Pn1.4
Pn1 EVM CDS 68921 69087 . - 2 ID=cds.evm.model.Pn1.4;Parent=evm.model.Pn1.4
Pn1 EVM exon 69249 69345 . - . ID=evm.model.Pn1.4.exon1;Parent=evm.model.Pn1.4
Pn1 EVM CDS 69249 69345 . - 0 ID=cds.evm.model.Pn1.4;Parent=evm.model.Pn1.4

Pn1 EVM mRNA 73564 74589 . - . ID=evm.model.Pn1.5
Pn1 EVM exon 73564 74589 . - . ID=evm.model.Pn1.5.exon1;Parent=evm.model.Pn1.5
Pn1 EVM CDS 73564 74589 . - 0 ID=cds.evm.model.Pn1.5;Parent=evm.model.Pn1.5

Pn1 EVM mRNA 76279 78348 . - . ID=evm.model.Pn1.6
Pn1 EVM exon 76279 77882 . - . ID=evm.model.Pn1.6.exon3;Parent=evm.model.Pn1.6
Pn1 EVM CDS 76279 77882 . - 2 ID=cds.evm.model.Pn1.6;Parent=evm.model.Pn1.6
Pn1 EVM exon 77981 78152 . - . ID=evm.model.Pn1.6.exon2;Parent=evm.model.Pn1.6
Pn1 EVM CDS 77981 78152 . - 0 ID=cds.evm.model.Pn1.6;Parent=evm.model.Pn1.6
Pn1 EVM exon 78241 78348 . - . ID=evm.model.Pn1.6.exon1;Parent=evm.model.Pn1.6
Pn1 EVM CDS 78241 78348 . - 0 ID=cds.evm.model.Pn1.6;Parent=evm.model.Pn1.6

Pn1 EVM mRNA 78599 80899 . + . ID=evm.model.Pn1.7
Pn1 EVM exon 78599 80899 . + . ID=evm.model.Pn1.7.exon1;Parent=evm.model.Pn1.7
Pn1 EVM CDS 78599 80899 . + 0 ID=cds.evm.model.Pn1.7;Parent=evm.model.Pn1.7

Pn1 EVM mRNA 94000 97630 . - . ID=evm.model.Pn1.8
Pn1 EVM exon 94000 94039 . - . ID=evm.model.Pn1.8.exon6;Parent=evm.model.Pn1.8
Pn1 EVM CDS 94000 94039 . - 1 ID=cds.evm.model.Pn1.8;Parent=evm.model.Pn1.8
Pn1 EVM exon 94111 94173 . - . ID=evm.model.Pn1.8.exon5;Parent=evm.model.Pn1.8
Pn1 EVM CDS 94111 94173 . - 1 ID=cds.evm.model.Pn1.8;Parent=evm.model.Pn1.8
Pn1 EVM exon 95257 95328 . - . ID=evm.model.Pn1.8.exon4;Parent=evm.model.Pn1.8
Pn1 EVM CDS 95257 95328 . - 1 ID=cds.evm.model.Pn1.8;Parent=evm.model.Pn1.8
Pn1 EVM exon 95706 95782 . - . ID=evm.model.Pn1.8.exon3;Parent=evm.model.Pn1.8
Pn1 EVM CDS 95706 95782 . - 0 ID=cds.evm.model.Pn1.8;Parent=evm.model.Pn1.8
Pn1 EVM exon 97358 97453 . - . ID=evm.model.Pn1.8.exon2;Parent=evm.model.Pn1.8
Pn1 EVM CDS 97358 97453 . - 0 ID=cds.evm.model.Pn1.8;Parent=evm.model.Pn1.8
Pn1 EVM exon 97568 97630 . - . ID=evm.model.Pn1.8.exon1;Parent=evm.model.Pn1.8
Pn1 EVM CDS 97568 97630 . - 0 ID=cds.evm.model.Pn1.8;Parent=evm.model.Pn1.8

Pn1 EVM mRNA 99324 103009 . - . ID=evm.model.Pn1.9
Pn1 EVM exon 99324 99436 . - . ID=evm.model.Pn1.9.exon3;Parent=evm.model.Pn1.9
Pn1 EVM CDS 99324 99436 . - 1 ID=cds.evm.model.Pn1.9;Parent=evm.model.Pn1.9
Pn1 EVM exon 100641 100687 . - . ID=evm.model.Pn1.9.exon2;Parent=evm.model.Pn1.9
Pn1 EVM CDS 100641 100687 . - 0 ID=cds.evm.model.Pn1.9;Parent=evm.model.Pn1.9
Pn1 EVM exon 102917 103009 . - . ID=evm.model.Pn1.9.exon1;Parent=evm.model.Pn1.9
Pn1 EVM CDS 102917 103009 . - 0 ID=cds.evm.model.Pn1.9;Parent=evm.model.Pn1.9

Pn1 EVM mRNA 115756 116324 . - . ID=evm.model.Pn1.10
Pn1 EVM exon 115756 115776 . - . ID=evm.model.Pn1.10.exon2;Parent=evm.model.Pn1.10
Pn1 EVM CDS 115756 115776 . - 0 ID=cds.evm.model.Pn1.10;Parent=evm.model.Pn1.10
Pn1 EVM exon 116115 116324 . - . ID=evm.model.Pn1.10.exon1;Parent=evm.model.Pn1.10
Pn1 EVM CDS 116115 116324 . - 0 ID=cds.evm.model.Pn1.10;Parent=evm.model.Pn1.10
