### ISSUE TITLE
Inconsistent number of significant digits from gene abundance output

### ISSUE THREAD

**Issue by wpoehlm** [gpertea/stringtie#199]
Hi,

I am using Stringtie version 1.3.4d .  When I use the -A option to produce a gene abundance output file, I get an inconsistent number of significant digits from unexpressed genes.  Some of the genes have TPM/FPKM values of '0.0' while others have '0.000000'.  For example:

[wpoehlm@node0004 GSM2493788]$ head -1 GSM2493788-Gene_abundances.txt ; grep -w '0.0' GSM2493788-Gene_abundances.txt | head -1

Gene ID Gene Name       Reference       Strand  Start   End     Coverage        FPKM    TPM
AT1G23724.TAIR10        AT1G23724       Chr1    +       8393187 8393330 0.0     0.0     0.0

[wpoehlm@node0004 GSM2493788]$ head -1 GSM2493788-Gene_abundances.txt ; grep -w '0.000000' GSM2493788-Gene_abundances.txt | head -1

Gene ID Gene Name       Reference       Strand  Start   End     Coverage        FPKM    TPM
AT1G02670.TAIR10        AT1G02670       Chr1    +       576046  580299  0.000000        0.000000        0.000000

Here are my full command line arguments:

stringtie SRA-accepted_hits.filtered.sorted.bam -G *gff3 -eB -o ./SRA.hisat2.StringTie.hits.bam.gtf -v -A SRA-Gene_abundances.txt 

I have noticed this consistently using three different reference genomes (human, arabidopsis, and medicago).  

I am hoping that this is something minor since there don't appear to be reads aligning to these genes in either situation, but do you have any idea what could be causing this?

Thanks,

Will

**Comment by gpertea** [comment]
Phew, if it's just about the 0s, that is indeed a minor output quirk (sorry for the confusion): 
- the "0.0" printouts are coming from a totally separate part of the code, which only applies to those genes for which there is no coverage estimation to be performed. It's after the actual coverage estimation was finished, I just gather and list all those genes that were not found to be overlapping any of the read alignment bundles, and they are simply listed with no coverage, at the end there, for the sake of completeness. I lazily chose to print these "no coverage" values as "0.0" as a constant part of the formatting string (simply saving some bytes there, which was silly and, now I see, misleading, if one takes it as rounding precision).
- the " 0.000000" values are coming directly from the coverage estimation function applied to the bundles, as those genes were found to be overlapping some read alignments bundles yet the coverage estimated for them has actually a zero (or insignificant) value, so those are actually printed using the same floating point format/template which is used for all the other coverage value estimations..

So they do technically mean the same thing: zero/insignificant coverage. The "0.0" was just a printing shortcut I used there for those genes/transcripts which had no chance of any read alignment coverage..

**Comment by wpoehlm** [comment]
@gpertea , thank you for the explanation!  I’m all good here
