### ISSUE TITLE
Missing strand information on single exon transcripts

### ISSUE THREAD

**Issue by fcarelli** [gpertea/stringtie#20]
Hello,

I just started running StringTie recently using strand-specific RNA-Seq data aligned using GSNAP, and I noticed that the assembled monoexonic transcripts lack the strand information. Since GSNAP output provides the XS tag info only on the spiced alignments, I would like to know if the issue is due to the lack of this flag also in the unspliced reads.

It would be great if you can tell me if this can be fixed by manually adding the XS tag also on the unspliced reads or if I need to do anything else.

Thanks a lot!

**Comment by mpertea** [comment]
Yes, adding the XS tag manually for the unspliced reads should fix this problem.

**Comment by fcarelli** [comment]
Thank you very much, I'll try it!
