### ISSUE TITLE
Strand of single exon transcripts ?

### ISSUE THREAD

**Issue by john-bio01** [gpertea/stringtie#200]
I am using HISAT, stringtie and gffcompare to analyze some unstranded RNAseq reads.   I notice that the merged transcripts often have a strand assigned to them.  I understand how this can be achieved for transcripts with 2 or more exons, but I don't understand how this is done for single exon transcripts.  

Can you provide me with a pointer to a place which might provide a brief explanation?

Thanks!

**Comment by john-bio01** [comment]
Received feedback from Mihaela.

**Comment by ZHIDIHUAYUAN** [comment]
Hi,
 I am also confused about it. Where can I find the answer?
Thank you.
