### ISSUE TITLE
strand information is missed in GTF output

### ISSUE THREAD

**Issue by xinbindai** [gpertea/stringtie#22]
I notice there are some transcript/exon rows without strand information in GTF output. I can only see a dot in column #7. This problem make it failed to pass RSEM program. It is caused by uncertain strand or just a bug?

**Comment by mpertea** [comment]
If the BAM alignment file does not contain a strand for any of the assembled reads into a transcript, StringTie will have no way to know the strand. This should only happen for single exon transcripts.

**Comment by Jinjie-Duan** [comment]
I met the similar issue. The output gtf from stringtie contains 3630 gene models with "." strand (i.e. unstranded). So I followed @mpertea suggestion and checked my BAM file. I found the reads aligned to the unstranded gene model do have strand information, either "+" or "-". but I still got the unstranded gene model. Could anyone shed the light on this?

One more question, the feature of my output gtf file from stringtie contains only "exon" and "transcript", no "CDS"," start_codon" and "stop_codon".  Is that normal? Does anyone have this experience before?

**Comment by gpertea** [comment]
Could you please clarify -- did this happen to you with the latest available version of StringTie ? 

To answer your other question: yes, that's normal, the output GTF only shows assembled transcripts (which are defined by their exon-intron structure), StringTie is a RNA-Seq assembler, it does not handle (or care about) CDS info, which may or may not be available for some (coding) transcripts -- that's a different topic.
