### ISSUE TITLE
Stringtie2 segmentation fault

### ISSUE THREAD

**Issue by knewl** [gpertea/stringtie#227]
Hello,

Thank you very much for writing Stringtie2 - I have been eager to try it out on my ONT cDNA long reads. I have used Minimap2 v2.17 to align reads from 12 samples to the Xenopus tropicalis genome. I ran the following command to produce some very good transcriptomes:

> stringtie ../../genome_alignments/BC$i.to.genome.sorted.bam -L -c 10 -j 10 -p 8 -G ../../reference/GCF_000004195.3_Xenopus_tropicalis_v9.1_genomic.gtf -o BC$i.stringtie2.gtf

However, this worked perfectly in only 11 of 12 samples - one sample exited with a segmentation fault. I have tried re-running it with 128GB memory, but no difference. I've also tried splitting up the bam file by chromosome and narrowed the error to chromosome NC_030680.1. The bam file for this chromosome is only 45Mb. 

Running the same command without the gtf file option produces no error.

Please let me know if you have any ideas about what's causing this and what I can do next.

Best wishes,

Katherine

**Comment by gpertea** [comment]
We'd really like to look into this and fix it -- can you please share the smallest dataset (BAM + GTF) which triggers the error ? From what you are describing it sounds like that 45MB BAM file for NC_030680.1 and the corresponding annotation file should be enough to investigate this glitch. Thank you!

**Comment by knewl** [comment]
Thanks for getting back to me so quickly. I've uploaded the files to:

https://drive.google.com/drive/folders/1l2qj7GiTkKgP1AwVxi0dXXCkMfNzc8T8?usp=sharing

Please let me know if there is anything else you need.

**Comment by knewl** [comment]
Hi,

I've had another look at this and it seems to be a single read causing the problem: 
```
Read name = 1d57bf65-181e-4ef9-9980-4cda5a3c34f6
Read length = 523bp
----------------------
Mapping = Primary @ MAPQ 60
Reference span = NC_030680.1:72,716,837-72,727,276 (-) = 10,440bp
Cigar = 16S8M9964N18M1I64M4D1M1I37M1I...10M3D17M1D4M10D27M1I9M2D8M74S
Clipping = Left 16 soft; Right 74 soft
----------------------
s1 = 156
s2 = 0
NM = 103
AS = 163
cm = 30
nn = 0
tp = P
ms = 195
dv = 0.1082<hr>Location = NC_030680.1:72,716,842
Base = T @ QV 30

Alignment start position = NC_030680.1:72716837
TAATGTGGCCTGGTGATTTTTTTTTTTCTTCCTCATTCCTACTCAAAGACATTTAACTTATGTGAATTGATCACTGTGCTTTTTTTTATGGTGCTGAGTTTTTTTTTGCCAATTTCAAATTGTTCCCATTTTATTCTTCTGAAATGTATGTATAACTGTCTGTTTCAGATTTGCAAGTTTTGCATTCACATTGTGCCAAATGGAATGCTGAAGTCTTCCCTCACTCCCCCACAAAGCCTGGGTTAATCAAGGCTTTTTACTTGAAAATTAACCAAATTCTGTGTATTTGTTAATGGTACAAGTCCCTGTATATCGGAAATGGTTTGTTGTTCTTTATTGATTTATTTATTCTGTTTTATTTATGAAGGTTATTTTGTCATGCAGAACCCTGAAGTGAAGTACCGTTTTTTTTTTATATAAAGTAATGGAAACAAAACAACTAAACAGCAGAAAAAAAAAATAAAAAGAAGATGACAGCAAGCAGACGACTATGCGTCTGAATCGAGTCATTTAATCATAACTG

```
I removed it from the bam file and it now works fine. 

Best wishes,

Katherine

**Comment by gpertea** [comment]
Sorry, we've been away and did not get to take a closer look, but once again thank you for sharing this problem case with us. It looks like that read had an unusual alignment that confused StringTie, we'll make sure to detect these situations in the code and deal with them appropriately.

**Comment by knewl** [comment]
No worries! I'll let you know if any other problems arise with other datasets.
Thanks,
Katherine

**Comment by nhartwic** [comment]
I assume by the lack of update and the fact that this is pinned that this issue hasn't been resolved? Any advice on identifying the problematic read/reads?

I seem to be encountering the same issue. I have 13 ONT cdna read sets. Stringtie works fine for all but three of them. I'm currently trying to run them in "-e -G some.gff" mode. I can run stringtie on these without issue when I run them without -G. When I run them with -G (either with or without -e) I hit a seg fault.

**Comment by knewl** [comment]
Yes, I had the same problem. There were no issues running without the gtf file. I'm afraid my approach to finding the problematic read was brute force - I iteratively chopped the bam file into bits and found which bit was causing the seg fault. Eventually the problematic bam was so small that I could identify the read by looking in IGV.

**Comment by mpertea** [comment]
Sorry for the delay in fixing this issue. We have identified the problem, and we are working on correcting it. It's indeed only appearing when the reference annotation is used. We hope to have a new release by the end of next week.

**Comment by gpertea** [comment]
Version 2.0.1 was just released and it should fix this issue (and #235) as well.

**Comment by gpertea** [comment]
Please use v2.0.2, just released (instead of v2.0.1) as we found that the original v2.0.1 fix had some issues (and stringtie was still crashing but in different situations). 
This fixed 2.0.2 version can be now downloaded from https://github.com/gpertea/stringtie/releases or http://ccb.jhu.edu/software/stringtie/#install

**Comment by goeckeritz** [comment]
Hi there, 

I am using v2.1.2, and I am getting a similar error - Segmentation fault - but I am not using the -G flag. I keep getting a .gtf.tmp file that always ends in the exact same place:

unanchored2502	StringTie	transcript	9718	10217	1000	-	.	gene_id "Pcera.61912"; transcript_id "Pcera.61912.1"; cov "16.191000";
unanchored2502	StringTie	exon	9718	10217	1000	-	.	gene_id "Pcera.61912"; transcript_id "Pcera.61912.1"; exon_number "

Should I remove all of the alignments in this region and try again? My .bam file is only 2.4G.. so I don't think this is a memory issue. 

Thanks so much in advance!!

Kindly, 
Charity

**Comment by goeckeritz** [comment]
(update) switching to v2.1.3 fixed the issue, and I'm not sure why...

**Comment by gpertea** [comment]
@goeckeritz  can you please clarify if it was v2.1.2 or v2.2.1 (the latest release version) that caused the segmentation fault before ?

**Comment by goeckeritz** [comment]
Hi @gpertea,

Yes, it was definitely v2.1.2 and NOT the latest version! :)

**Comment by YIGUIz** [comment]
> Hi,
> 
> I've had another look at this and it seems to be a single read causing the problem:
> 
> ```
> Read name = 1d57bf65-181e-4ef9-9980-4cda5a3c34f6
> Read length = 523bp
> ----------------------
> Mapping = Primary @ MAPQ 60
> Reference span = NC_030680.1:72,716,837-72,727,276 (-) = 10,440bp
> Cigar = 16S8M9964N18M1I64M4D1M1I37M1I...10M3D17M1D4M10D27M1I9M2D8M74S
> Clipping = Left 16 soft; Right 74 soft
> ----------------------
> s1 = 156
> s2 = 0
> NM = 103
> AS = 163
> cm = 30
> nn = 0
> tp = P
> ms = 195
> dv = 0.1082<hr>Location = NC_030680.1:72,716,842
> Base = T @ QV 30
> 
> Alignment start position = NC_030680.1:72716837
> TAATGTGGCCTGGTGATTTTTTTTTTTCTTCCTCATTCCTACTCAAAGACATTTAACTTATGTGAATTGATCACTGTGCTTTTTTTTATGGTGCTGAGTTTTTTTTTGCCAATTTCAAATTGTTCCCATTTTATTCTTCTGAAATGTATGTATAACTGTCTGTTTCAGATTTGCAAGTTTTGCATTCACATTGTGCCAAATGGAATGCTGAAGTCTTCCCTCACTCCCCCACAAAGCCTGGGTTAATCAAGGCTTTTTACTTGAAAATTAACCAAATTCTGTGTATTTGTTAATGGTACAAGTCCCTGTATATCGGAAATGGTTTGTTGTTCTTTATTGATTTATTTATTCTGTTTTATTTATGAAGGTTATTTTGTCATGCAGAACCCTGAAGTGAAGTACCGTTTTTTTTTTATATAAAGTAATGGAAACAAAACAACTAAACAGCAGAAAAAAAAAATAAAAAGAAGATGACAGCAAGCAGACGACTATGCGTCTGAATCGAGTCATTTAATCATAACTG
> ```
> 
> I removed it from the bam file and it now works fine.
> 
> Best wishes,
> 
> Katherine

Hi Katherine, I have the same problem as you. I also found the error in the exact chromosome. Can you tell me how to find the exact read?

Best wishes,

Qi

**Comment by nanoniki** [comment]
> Hi,
> 
> I've had another look at this and it seems to be a single read causing the problem:
> 
> ```
> Read name = 1d57bf65-181e-4ef9-9980-4cda5a3c34f6
> Read length = 523bp
> ----------------------
> Mapping = Primary @ MAPQ 60
> Reference span = NC_030680.1:72,716,837-72,727,276 (-) = 10,440bp
> Cigar = 16S8M9964N18M1I64M4D1M1I37M1I...10M3D17M1D4M10D27M1I9M2D8M74S
> Clipping = Left 16 soft; Right 74 soft
> ----------------------
> s1 = 156
> s2 = 0
> NM = 103
> AS = 163
> cm = 30
> nn = 0
> tp = P
> ms = 195
> dv = 0.1082<hr>Location = NC_030680.1:72,716,842
> Base = T @ QV 30
> 
> Alignment start position = NC_030680.1:72716837
> TAATGTGGCCTGGTGATTTTTTTTTTTCTTCCTCATTCCTACTCAAAGACATTTAACTTATGTGAATTGATCACTGTGCTTTTTTTTATGGTGCTGAGTTTTTTTTTGCCAATTTCAAATTGTTCCCATTTTATTCTTCTGAAATGTATGTATAACTGTCTGTTTCAGATTTGCAAGTTTTGCATTCACATTGTGCCAAATGGAATGCTGAAGTCTTCCCTCACTCCCCCACAAAGCCTGGGTTAATCAAGGCTTTTTACTTGAAAATTAACCAAATTCTGTGTATTTGTTAATGGTACAAGTCCCTGTATATCGGAAATGGTTTGTTGTTCTTTATTGATTTATTTATTCTGTTTTATTTATGAAGGTTATTTTGTCATGCAGAACCCTGAAGTGAAGTACCGTTTTTTTTTTATATAAAGTAATGGAAACAAAACAACTAAACAGCAGAAAAAAAAAATAAAAAGAAGATGACAGCAAGCAGACGACTATGCGTCTGAATCGAGTCATTTAATCATAACTG
> ```
> 
> I removed it from the bam file and it now works fine.
> 
> Best wishes,
> 
> Katherine

Hello. I'm using stringtie2 version 3.0.0 and getting a "Segmentation fault" issue when I try to run stringtie on data derived from Nanopore RNA004 DRS runs. Can you say more about how you determined which reads were problems?

**Comment by knewl** [comment]
Hi @nanoniki .Apologies, this was many years ago so I don’t remember fully, but I think I simply tried splitting the bam into smaller parts and then re-running on each bam to narrow down the pool of reads. I would probably have done this many times until the bam had only a handful of reads and I could see which read was causing the problem.
