### ISSUE TITLE
prepDE.py error - line 255 - gene ID related

### ISSUE THREAD

**Issue by pratibha-bioinfo** [gpertea/stringtie#229]
Hi,

I have been using the script provided by StringTie named 'prepDE.py' for getting gene and transcript abundances. It was working fine with another set of mouse samples but failing now with these set of human samples.

```
/Softwares/prepDE.py -i grouping-info.txt
0 Sample1
1 Sample2
Traceback (most recent call last):
  File "/Softwares/prepDE.py", line 255, in <module>
    geneDict.setdefault(geneIDs[i],{}) #gene_id
KeyError: 'Sample2.101064.1'
```
It seems there is some issue with the Gene ID - 101064.1. I checked for this name in the gtf files, but only 101064 is found. I tried removing a few samples as well but still it fails after the first sample run.
Please help. I am using python version 3.5. I have cross-posted in Biostars as well.
Thanks!

**Comment by astrophys** [comment]
What was the solution to this?

**Comment by pratibha-bioinfo** [comment]
Hi astrophys, I thought it would show the reason why I closed my query as it had requested while I was trying to! Apparently, it was due to a very silly mistake of giving the wrong path of the GTF files in the input file you provide for running prepDE.py. Wish the error could tell me that rather than give this error. I could not find a way to delete this query.

**Comment by lelesama** [comment]
sorry ,I can't understand the error ,can you tell me how to solve  it,thanks!
