### ISSUE TITLE
--help returns exit code 1

### ISSUE THREAD

**Issue by roryk** [gpertea/stringtie#23]
It's tough to write an installer that checks to see if stringtie is installed correctly because there isn't a way to check without returning a non-zero exit code. Do you think --help could be swapped to return 0?

**Comment by gpertea** [comment]
Definitely! And as a follow up to this request I also added the ``--version`` option, which along with ``-h`` and ``--help`` now sends the output to stdout instead of stderr and then simply exit(0). 
I'll update the 1.1.0 packages and post a quick release update in a minute.

**Comment by roryk** [comment]
Thanks @gpertea, that is super helpful. Thanks for the `--version` option too, I wanted to ask for that but didn't want to press my luck.
