### ISSUE TITLE
Stringtie: the input alignment file is not sorted!

### ISSUE THREAD

**Issue by realgc** [gpertea/stringtie#240]
Hi,
I'm trying to assemble a transcriptome by RNA seq raw reads in FASTQ with STAR and StringTie. The input BAM file of StringTie was sorted by coordinate, and even sorted again by samtools sort, but the error 'the input alignment file is not sorted!' shows up still. I'm only using the -o and -p options.
Could you please help me with this?
Thanks in advance!

**Comment by gpertea** [comment]
Is it possible this is a situation similar to #196 ? If the reference genome has non-unique names for its chromosomes/contigs (or duplicate entries), both STAR and samtools have no problems with that, but StringTie does not work with such a redundant/malformed data.

**Comment by realgc** [comment]
I wonder what is 'non-unique name'? They are named as 'Linkage_group_1', 'Linkage_group_2', etc., does this work?

**Comment by realgc** [comment]
I wonder what is 'non-unique name'? They are named as 'Linkage_group_1', 'Linkage_group_2', etc., does this work?

**Comment by gpertea** [comment]
"non-unique" in this context means identical names used for two or more separate entries (or duplicate entries) in the genome FASTA file which was used for the RNA-Seq alignments. Sometimes users might pull the same contig sequence more than once into the genome FASTA file that is then used for RNA-Seq alignments (that seemed to have been the case with #196).

You can use the following command to check if you have any such duplicates in your BAM file:
```
samtools view -H sorted.bam  | grep '^@SQ' | cut -f2 -d: | cut -f1 | sort | uniq -d
```

(where of course *sorted.bam* should be replaced by your sorted BAM file name)

**Comment by realgc** [comment]
I've checked all the files and there are no duplicate entries. Are there any other possibilities causing this problem?

**Comment by gpertea** [comment]
No,  except for the coordinates being in the wrong order (which shouldn't be the case since you mentioned that the BAM file was sorted with samtools sort). 
Could you share a .bam file which makes StringTie fail with the error message you mentioned? (the smaller the easier, of course).

**Comment by realgc** [comment]
body is a short cut, and header is the header part.
Thanks!
[sample_stringtie.zip](https://github.com/gpertea/stringtie/files/3673090/sample_stringtie.zip)

**Comment by gpertea** [comment]
Do you get the error for the data you sent? Because I don't - so there is nothing for me there to debug, sorry.
But if you do get the error on this small data set (20 alignments), please send me the command line you used (assuming you concatenated the 'header' and the 'body files' you sent into a file called t.sam or something like that).

**Comment by realgc** [comment]
Thanks for your help!! If I get it correct, StringTie could only transfer one bam file into gtf file at a time, and I need to merge multiple gtf files into one single file with the merge option, right? Because I found that with each file the command works well, but with multiple files the error above would appear. 
Thanks for your time, and if my understanding is right please close this issue so I would know it.

**Comment by gpertea** [comment]
Right, you're supposed to assemble each .bam file separately and then merge the output .gtf files somehow (either using stringtie with the --merge option or with gffcompare etc.).

Before I close this, can you please clarify how did you run stringtie "with multiple files" ? Did you merge them before hand (concatenated them?) or did you just specify multiple .bam files in the stringtie command line ?
If you had merged the sorted .bam files using `samtools merge` and then used stringtie on the resulting .bam file (or SAM stream) that should have technically worked OK, but it is not recommended to multiplex alignments from multiple samples like that -- the correct way is indeed to assemble each sample separately and then analyze/combine the resulting assembled transcripts (the .gtf files).

**Comment by realgc** [comment]
I specified multiple .bam files, divided by ' '. 
Thanks!

**Comment by dujuanhua6308** [comment]
Hi, I met the similar problem when I use stringtie: "Error: the input alignment file is not sorted! Alignments (965520) already found for chr1_1 !". I was working with the genome of Pinus tabliformis for mapping, which was more than 20GB and each chromosome was more than 2GB. My colleague deal with this problem by dividing each chromsome into two parts and no error again. But since the genome she worked with, was small and each chromsome was about 1GB, my chromesome was so big, if should I follow her method to dividing the chromsome into at least four parts? Hope to get your response and if there are other methods?
