### ISSUE TITLE
Error in prepDE.py

### ISSUE THREAD

**Issue by nourelislam** [gpertea/stringtie#245]
Hi,

I am using prepDE.py for getting an estimation matrix with Deseq2 but I encounter this error:
(0, 'RNAseq_33-C')
(1, 'RNAseq_33-S')
Traceback (most recent call last):
  File "/home/nourelislam/anaconda3/envs/ngs/bin/prepDE.py", line 255, in <module>
    geneDict.setdefault(geneIDs[i],{}) #gene_id
KeyError: '33-S.28019.1'

Please Help @gpertea

**Comment by gpertea** [comment]
This seems to be the same issue with #234 and #232, so it should be fixed by v2.0.4 release.
