### ISSUE TITLE
cuffmerge replacement (--merge option?)

### ISSUE THREAD

**Issue by gpertea** [gpertea/stringtie#25]
We should implement a "transcript merge" mode of stringtie where it would use the splice graph to simply assemble compatible isoforms loaded from multiple GTF files -- as a functional replacement of Cuffmerge. In this mode of operation stringtie would no longer expect an input BAM file but instead will take a list of GTF/GFF files and "assemble" the transcripts from those (without any attempt of abundance estimation of course).

**Comment by filicado** [comment]
Absolutely needed! In the HISAT2 -> Stringtie -> Cuffmerge -> Stringtie -B -> Ballgown pipeline it is without fail the cuffmerge step that exclusively produces the problems.

**Comment by gpertea** [comment]
StringTie v1.2.0 was released with the new ``--merge`` option which implements this "transcript merge" functionality. The manual has been updated on the website to depict the new work flow (http://ccb.jhu.edu/software/stringtie/index.shtml?t=manual#de)
