### ISSUE TITLE
error while installing stringTie

### ISSUE THREAD

**Issue by asmitagpta** [gpertea/stringtie#251]
Hi,

I would like to use stringTie for subsequent transcript-level quantification from my RNA-Seq data. I am following the instructions to install the program after cloning the repo - 

git clone https://github.com/gpertea/stringtie
cd stringtie
make release

However, the make step is terminating with the following error - 

----------------------------------------------------------
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++0x -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/GBase.cpp -o gclib/GBase.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++0x -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/GArgs.cpp -o gclib/GArgs.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++0x -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/GStr.cpp -o gclib/GStr.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++0x -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/GBam.cpp -o gclib/GBam.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++0x -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/gdna.cpp -o gclib/gdna.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++0x -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/codons.cpp -o gclib/codons.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++0x -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/GFastaIndex.cpp -o gclib/GFastaIndex.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++0x -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/GFaSeqGet.cpp -o gclib/GFaSeqGet.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++0x -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/gff.cpp -o gclib/gff.o
gclib/gff.cpp: In member function ‘bool GffObj::processGeneSegments(GffReader*)’:
gclib/gff.cpp:1988: error: template argument for ‘template<class OBJ> class GVec’ uses local type ‘GffObj::processGeneSegments(GffReader*)::GeneCDS’
gclib/gff.cpp:1988: error:   trying to instantiate ‘template<class OBJ> class GVec’
gclib/gff.cpp:1989: error: template argument for ‘template<class OBJ> class GArray’ uses local type ‘GffObj::processGeneSegments(GffReader*)::GSegMatch’
gclib/gff.cpp:1989: error:   trying to instantiate ‘template<class OBJ> class GArray’
gclib/gff.cpp: In member function ‘void GffObj::processGeneSegments(GffReader*)::GeneCDSChain::addCDS(int, uint, uint)’:
gclib/gff.cpp:1998: error: request for member ‘Add’ in ‘((GffObj::processGeneSegments(GffReader*)::GeneCDSChain*)this)->GffObj::processGeneSegments(GffReader*)::GeneCDSChain::cdsList’, which is of non-class type ‘int’
gclib/gff.cpp: In member function ‘void GffObj::processGeneSegments(GffReader*)::GeneCDSChain::addMatch(int, int, int)’:
gclib/gff.cpp:2003: error: request for member ‘Add’ in ‘((GffObj::processGeneSegments(GffReader*)::GeneCDSChain*)this)->GffObj::processGeneSegments(GffReader*)::GeneCDSChain::mxs’, which is of non-class type ‘int’
gclib/gff.cpp: In member function ‘bool GffObj::processGeneSegments(GffReader*)::GeneCDSChain::singleExonCDSMatch(uint, uint, int&)’:
gclib/gff.cpp:2009: error: request for member ‘Count’ in ‘((GffObj::processGeneSegments(GffReader*)::GeneCDSChain*)this)->GffObj::processGeneSegments(GffReader*)::GeneCDSChain::cdsList’, which is of non-class type ‘int’
gclib/gff.cpp:2011: error: request for member ‘Count’ in ‘((GffObj::processGeneSegments(GffReader*)::GeneCDSChain*)this)->GffObj::processGeneSegments(GffReader*)::GeneCDSChain::cdsList’, which is of non-class type ‘int’
gclib/gff.cpp:2012: error: invalid types ‘int[int]’ for array subscript
gclib/gff.cpp:2012: error: invalid types ‘int[int]’ for array subscript
gclib/gff.cpp: In member function ‘bool GffObj::processGeneSegments(GffReader*)::GeneCDSChain::singleCDStoExon(GffObj&, int&)’:
gclib/gff.cpp:2022: error: invalid types ‘int[int]’ for array subscript
gclib/gff.cpp:2023: error: invalid types ‘int[int]’ for array subscript
gclib/gff.cpp:2024: error: invalid types ‘int[int]’ for array subscript
gclib/gff.cpp:2026: error: invalid types ‘int[int]’ for array subscript
gclib/gff.cpp:2026: error: invalid types ‘int[int]’ for array subscript
gclib/gff.cpp: In member function ‘bool GffObj::processGeneSegments(GffReader*)::GeneCDSChain::multiCDStoExon(GffObj&, int&)’:
gclib/gff.cpp:2043: error: request for member ‘Count’ in ‘((GffObj::processGeneSegments(GffReader*)::GeneCDSChain*)this)->GffObj::processGeneSegments(GffReader*)::GeneCDSChain::cdsList’, which is of non-class type ‘int’
gclib/gff.cpp:2047: error: invalid types ‘int[int]’ for array subscript
gclib/gff.cpp:2048: error: invalid types ‘int[int]’ for array subscript
gclib/gff.cpp:2050: error: invalid types ‘int[int]’ for array subscript
gclib/gff.cpp:2050: error: invalid types ‘int[int]’ for array subscript
gclib/gff.cpp:2063: error: invalid types ‘int[int]’ for array subscript
gclib/gff.cpp:2064: error: invalid types ‘int[int]’ for array subscript
gclib/gff.cpp:2074: error: request for member ‘Count’ in ‘((GffObj::processGeneSegments(GffReader*)::GeneCDSChain*)this)->GffObj::processGeneSegments(GffReader*)::GeneCDSChain::cdsList’, which is of non-class type ‘int’
gclib/gff.cpp:2076: error: invalid types ‘int[int]’ for array subscript
gclib/gff.cpp: In member function ‘bool GffObj::processGeneSegments(GffReader*)::GeneCDSChain::containedBy(GffObj&, int&)’:
gclib/gff.cpp:2097: error: request for member ‘Count’ in ‘((GffObj::processGeneSegments(GffReader*)::GeneCDSChain*)this)->GffObj::processGeneSegments(GffReader*)::GeneCDSChain::cdsList’, which is of non-class type ‘int’
gclib/gff.cpp: In member function ‘bool GffObj::processGeneSegments(GffReader*)’:
gclib/gff.cpp:2105: error: template argument for ‘template<class OBJ> class GHash’ uses local type ‘GffObj::processGeneSegments(GffReader*)::GeneCDSChain’
gclib/gff.cpp:2105: error:   trying to instantiate ‘template<class OBJ> class GHash’
gclib/gff.cpp:2105: error: invalid type in declaration before ‘(’ token
gclib/gff.cpp:2106: error: template argument for ‘template<class OBJ> class GPVec’ uses local type ‘GffObj::processGeneSegments(GffReader*)::GeneCDSChain’
gclib/gff.cpp:2106: error:   trying to instantiate ‘template<class OBJ> class GPVec’
gclib/gff.cpp:2106: error: invalid type in declaration before ‘;’ token
gclib/gff.cpp:2128: error: request for member ‘Find’ in ‘cdsChainById’, which is of non-class type ‘int’
gclib/gff.cpp:2133: error: request for member ‘Add’ in ‘cdsChains’, which is of non-class type ‘int’
gclib/gff.cpp:2134: error: request for member ‘shkAdd’ in ‘cdsChainById’, which is of non-class type ‘int’
gclib/gff.cpp:2143: error: request for member ‘Count’ in ‘cdsChains’, which is of non-class type ‘int’
gclib/gff.cpp:2144: error: invalid types ‘int[int]’ for array subscript
gclib/gff.cpp:2153: error: request for member ‘Count’ in ‘gc->GffObj::processGeneSegments(GffReader*)::GeneCDSChain::mxs’, which is of non-class type ‘int’
gclib/gff.cpp:2158: error: request for member ‘First’ in ‘gc->GffObj::processGeneSegments(GffReader*)::GeneCDSChain::mxs’, which is of non-class type ‘int’
gclib/gff.cpp:2159: error: request for member ‘Count’ in ‘gc->GffObj::processGeneSegments(GffReader*)::GeneCDSChain::cdsList’, which is of non-class type ‘int’
gclib/gff.cpp:2160: error: invalid types ‘int[int]’ for array subscript
gclib/gff.cpp:2161: error: invalid types ‘int[int]’ for array subscript
gclib/gff.cpp:2165: error: request for member ‘First’ in ‘gc->GffObj::processGeneSegments(GffReader*)::GeneCDSChain::mxs’, which is of non-class type ‘int’
make: *** [gclib/gff.o] Error 1
-----------------------------------------------------------------------

I also tried to run the precompiled binaries, but running ./stringtie after downloading and unpacking the tarball, gives following error - 

----------------------------------------------
./stringtie: /lib64/libz.so.1: version `ZLIB_1.2.3.3' not found (required by ./stringtie)
./stringtie: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./stringtie)
----------------------------------------------

I am doing the entire installation from my home directory, since I don't have root privileges. The OS  is - 
CentOS release 6.9 (Final)

I checked the available version of zlib and glibc libraries via rpm -qa | grep zlib (glibc) and this is the result - 

---------------------------------------------
jzlib-1.0.7-7.5.el6.x86_64
zlib-1.2.3-29.el6.x86_64
zlib-devel-1.2.3-29.el6.x86_64

glibc-2.12-1.209.el6_9.2.i686
glibc-devel-2.12-1.209.el6_9.2.x86_64
glibc-utils-2.12-1.209.el6_9.2.x86_64
compat-glibc-headers-2.5-46.2.x86_64
glibc-headers-2.12-1.209.el6_9.2.x86_64
glibc-common-2.12-1.209.el6_9.2.x86_64
compat-glibc-2.5-46.2.x86_64
glibc-2.12-1.209.el6_9.2.x86_64
---------------------------------------------

Can you please suggest how can I sort this issue?

Thanks,

**Comment by gpertea** [comment]
Thank you for your report, I see now that there are problems with the current StringTie distribution on RHEL 6 and I am looking into fixing those, I really want to continue supporting that older distribution (currently I'm building StringTie on a RHEL 7 compatible system). I'll be providing a working solution soon.

**Comment by gpertea** [comment]
Commit 29a72ed should allow building stringtie on a CentOS 6 (gcc 4.4). I guess you know that you can use `git pull` in the previously cloned directory to fetch this update or clone into a new directory like you did the first time. Please let me know if you still cannot build stringtie now on your system.
I am still working on getting a statically linked binary compatible with older systems.

**Comment by gpertea** [comment]
Besides the earlier change which should allow compiling stringtie on RHEL/CentOS 6, starting with the v2.0.5 release the included linux precompiled package should now work even with RHEL 5/CentOS 5.
