### ISSUE TITLE
Stringtie: *** Error in `stringtie': corrupted double-linked list: 0x00000000020c4910 ***

### ISSUE THREAD

**Issue by zhang919** [gpertea/stringtie#256]
Hi,
I'm trying to assemble a transcriptome by RNA seq raw reads in FASTQ with  HISAT and StringTie .The input BAM file of StringTie was sorted by coordinate (by samtools).Regrettably，I have this problem：
`*** Error in `stringtie': corrupted double-linked list: 0x00000000020c4910 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fa8906897e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x82970)[0x7fa890694970]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7fa890696184]
stringtie[0x4a703d]
stringtie[0x4a70b9]
stringtie[0x414774]
stringtie[0x413bdb]
stringtie[0x48ea36]
stringtie[0x403df2]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fa890632830]
stringtie[0x4063d9]
======= Memory map: ========
00400000-004db000 r-xp 00000000 08:01 780820                             /home/zhangjiayu616/bin/sratoolkit/bin/stringtie
006db000-006de000 rw-p 000db000 08:01 780820                             /home/zhangjiayu616/bin/sratoolkit/bin/stringtie
006de000-006f8000 rw-p 00000000 00:00 0 
012f3000-1187c000 rw-p 00000000 00:00 0                                  [heap]
7fa864000000-7fa864021000 rw-p 00000000 00:00 0 
7fa864021000-7fa868000000 ---p 00000000 00:00 0 
7fa86c000000-7fa86d720000 rw-p 00000000 00:00 0 
7fa86d720000-7fa870000000 ---p 00000000 00:00 0 
7fa870000000-7fa87112f000 rw-p 00000000 00:00 0 
7fa87112f000-7fa874000000 ---p 00000000 00:00 0 
7fa874000000-7fa8750f8000 rw-p 00000000 00:00 0 
7fa8750f8000-7fa878000000 ---p 00000000 00:00 0 
7fa878000000-7fa879027000 rw-p 00000000 00:00 0 
7fa879027000-7fa87c000000 ---p 00000000 00:00 0 
7fa87c000000-7fa87d97c000 rw-p 00000000 00:00 0 
7fa87d97c000-7fa880000000 ---p 00000000 00:00 0 
7fa880000000-7fa88169d000 rw-p 00000000 00:00 0 
7fa88169d000-7fa884000000 ---p 00000000 00:00 0 
7fa884000000-7fa88512e000 rw-p 00000000 00:00 0 
7fa88512e000-7fa888000000 ---p 00000000 00:00 0 
7fa888000000-7fa88976c000 rw-p 00000000 00:00 0 
7fa88976c000-7fa88c000000 ---p 00000000 00:00 0 
7fa88c3f4000-7fa88c40a000 r-xp 00000000 08:01 2007                       /lib/x86_64-linux-gnu/libgcc_s.so.1
7fa88c40a000-7fa88c609000 ---p 00016000 08:01 2007                       /lib/x86_64-linux-gnu/libgcc_s.so.1
7fa88c609000-7fa88c60a000 rw-p 00015000 08:01 2007                       /lib/x86_64-linux-gnu/libgcc_s.so.1
7fa88c60a000-7fa88c60b000 ---p 00000000 00:00 0 
7fa88c60b000-7fa88ce0b000 rw-p 00000000 00:00 0 
7fa88ce0b000-7fa88ce0c000 ---p 00000000 00:00 0 
7fa88ce0c000-7fa88d60c000 rw-p 00000000 00:00 0 
7fa88d60c000-7fa88d60d000 ---p 00000000 00:00 0 
7fa88d60d000-7fa88de0d000 rw-p 00000000 00:00 0 
7fa88de0d000-7fa88de0e000 ---p 00000000 00:00 0 
7fa88de0e000-7fa88e60e000 rw-p 00000000 00:00 0 
7fa88e60e000-7fa88e60f000 ---p 00000000 00:00 0 
7fa88e60f000-7fa88ee0f000 rw-p 00000000 00:00 0 
7fa88ee0f000-7fa88ee10000 ---p 00000000 00:00 0 
7fa88ee10000-7fa88f610000 rw-p 00000000 00:00 0 
7fa88f610000-7fa88f611000 ---p 00000000 00:00 0 
7fa88f611000-7fa88fe11000 rw-p 00000000 00:00 0 
7fa88fe11000-7fa88fe12000 ---p 00000000 00:00 0 
7fa88fe12000-7fa890612000 rw-p 00000000 00:00 0 
7fa890612000-7fa8907d2000 r-xp 00000000 08:01 2166                       /lib/x86_64-linux-gnu/libc-2.23.so
7fa8907d2000-7fa8909d2000 ---p 001c0000 08:01 2166                       /lib/x86_64-linux-gnu/libc-2.23.so
7fa8909d2000-7fa8909d6000 r--p 001c0000 08:01 2166                       /lib/x86_64-linux-gnu/libc-2.23.so
7fa8909d6000-7fa8909d8000 rw-p 001c4000 08:01 2166                       /lib/x86_64-linux-gnu/libc-2.23.so
7fa8909d8000-7fa8909dc000 rw-p 00000000 00:00 0 
7fa8909dc000-7fa8909f4000 r-xp 00000000 08:01 2153                       /lib/x86_64-linux-gnu/libpthread-2.23.so
7fa8909f4000-7fa890bf3000 ---p 00018000 08:01 2153                       /lib/x86_64-linux-gnu/libpthread-2.23.so
7fa890bf3000-7fa890bf4000 r--p 00017000 08:01 2153                       /lib/x86_64-linux-gnu/libpthread-2.23.so
7fa890bf4000-7fa890bf5000 rw-p 00018000 08:01 2153                       /lib/x86_64-linux-gnu/libpthread-2.23.so
7fa890bf5000-7fa890bf9000 rw-p 00000000 00:00 0 
7fa890bf9000-7fa890d01000 r-xp 00000000 08:01 2169                       /lib/x86_64-linux-gnu/libm-2.23.so
7fa890d01000-7fa890f00000 ---p 00108000 08:01 2169                       /lib/x86_64-linux-gnu/libm-2.23.so
7fa890f00000-7fa890f01000 r--p 00107000 08:01 2169                       /lib/x86_64-linux-gnu/libm-2.23.so
7fa890f01000-7fa890f02000 rw-p 00108000 08:01 2169                       /lib/x86_64-linux-gnu/libm-2.23.so
7fa890f02000-7fa890f1b000 r-xp 00000000 08:01 2097                       /lib/x86_64-linux-gnu/libz.so.1.2.8
7fa890f1b000-7fa89111a000 ---p 00019000 08:01 2097                       /lib/x86_64-linux-gnu/libz.so.1.2.8
7fa89111a000-7fa89111b000 r--p 00018000 08:01 2097                       /lib/x86_64-linux-gnu/libz.so.1.2.8
7fa89111b000-7fa89111c000 rw-p 00019000 08:01 2097                       /lib/x86_64-linux-gnu/libz.so.1.2.8
7fa89111c000-7fa891142000 r-xp 00000000 08:01 2152                       /lib/x86_64-linux-gnu/ld-2.23.so
7fa891333000-7fa891338000 rw-p 00000000 00:00 0 
7fa891340000-7fa891341000 rw-p 00000000 00:00 0 
7fa891341000-7fa891342000 r--p 00025000 08:01 2152                       /lib/x86_64-linux-gnu/ld-2.23.so
7fa891342000-7fa891343000 rw-p 00026000 08:01 2152                       /lib/x86_64-linux-gnu/ld-2.23.so
7fa891343000-7fa891344000 rw-p 00000000 00:00 0 
7ffd27785000-7ffd277a6000 rw-p 00000000 00:00 0                          [stack]
7ffd277d8000-7ffd277db000 r--p 00000000 00:00 0                          [vvar]
7ffd277db000-7ffd277dd000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)
`
the command is 

 `stringtie -p 8 -G ~/data/gtf/ref_GRCh37.p5_top_level.gff3 -o SRR8382645.gtf -l SRR8382645 SRR8382645_new_sorted.bam`

Thanks for your attention!

**Comment by gpertea** [comment]
This seems to be related to a regression bug present in the last couple of releases. I just released **v2.0.6** which should hopefully fix it -- could you please download and run v2.0.6 instead and let me know if you get any errors? ( Download it from https://github.com/gpertea/stringtie/releases or http://ccb.jhu.edu/software/stringtie/#install )

**Comment by zhang919** [comment]
Hi gpertea，
I have tied the lastest version in your link, now it looks like well. Thanks for your rapidly fix and nice work on RNA-seq analysis.
Best washes
