### ISSUE TITLE
StringTie failing with reference GTF file

### ISSUE THREAD

**Issue by asmitagpta** [gpertea/stringtie#258]
Hi,

This is in connection to [https://github.com/gpertea/stringtie/issues/251](https://github.com/gpertea/stringtie/issues/251) 'error while installing StringTie' on CentOS release 6.9 (Final).

Thanks a lot for incorporating the update. I managed to install the program successfully. 

However, I seem to encounter a new problem while running this version since some time now. The program runs fine when I don't provide any reference GTF file for assembly generating an output GTF. However, I would like to run it in a guided mode with a reference Ensemble GTF. When this file is provided with -G option, the program always crashes with a similar kind of error - 

--------------------------------------
*** glibc detected *** /apps/stringtie/stringtie: malloc(): memory corruption (fast): 0x00000000036a3501 ***
======= Backtrace: =========
/lib64/libc.so.6[0x3fd8875dee]
/lib64/libc.so.6[0x3fd887a4b8]
/lib64/libc.so.6(__libc_malloc+0x5c)[0x3fd887aaac]
/apps/stringtie/stringtie[0x404570]
/apps/stringtie/stringtie[0x428c49]
/apps/stringtie/stringtie[0x4836af]
/apps/stringtie/stringtie[0x44d832]
/apps/stringtie/stringtie[0x490b89]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x3fd881ed1d]
/apps/stringtie/stringtie[0x402c49]
======= Memory map: ========
00400000-004be000 r-xp 00000000 08:02 18877471                           /apps/stringtie/stringtie
006bd000-006bf000 rw-p 000bd000 08:02 18877471                           /apps/stringtie/stringtie
006bf000-006c7000 rw-p 00000000 00:00 0
00a38000-142ef000 rw-p 00000000 00:00 0                                  [heap]
3fd8400000-3fd8420000 r-xp 00000000 08:02 47972382                       /lib64/ld-2.12.so
3fd8620000-3fd8621000 r--p 00020000 08:02 47972382                       /lib64/ld-2.12.so
3fd8621000-3fd8622000 rw-p 00021000 08:02 47972382                       /lib64/ld-2.12.so
3fd8622000-3fd8623000 rw-p 00000000 00:00 0
3fd8800000-3fd898a000 r-xp 00000000 08:02 47972470                       /lib64/libc-2.12.so
3fd898a000-3fd8b8a000 ---p 0018a000 08:02 47972470                       /lib64/libc-2.12.so
3fd8b8a000-3fd8b8e000 r--p 0018a000 08:02 47972470                       /lib64/libc-2.12.so
3fd8b8e000-3fd8b90000 rw-p 0018e000 08:02 47972470                       /lib64/libc-2.12.so
3fd8b90000-3fd8b94000 rw-p 00000000 00:00 0
3fd8c00000-3fd8c17000 r-xp 00000000 08:02 47972915                       /lib64/libpthread-2.12.so
3fd8c17000-3fd8e17000 ---p 00017000 08:02 47972915                       /lib64/libpthread-2.12.so
3fd8e17000-3fd8e18000 r--p 00017000 08:02 47972915                       /lib64/libpthread-2.12.so
3fd8e18000-3fd8e19000 rw-p 00018000 08:02 47972915                       /lib64/libpthread-2.12.so
3fd8e19000-3fd8e1d000 rw-p 00000000 00:00 0
3fd9400000-3fd9483000 r-xp 00000000 08:02 47972491                       /lib64/libm-2.12.so
3fd9483000-3fd9682000 ---p 00083000 08:02 47972491                       /lib64/libm-2.12.so
3fd9682000-3fd9683000 r--p 00082000 08:02 47972491                       /lib64/libm-2.12.so
3fd9683000-3fd9684000 rw-p 00083000 08:02 47972491                       /lib64/libm-2.12.so
3fd9800000-3fd9815000 r-xp 00000000 08:02 47972521                       /lib64/libz.so.1.2.3
3fd9815000-3fd9a14000 ---p 00015000 08:02 47972521                       /lib64/libz.so.1.2.3
3fd9a14000-3fd9a15000 r--p 00014000 08:02 47972521                       /lib64/libz.so.1.2.3
3fd9a15000-3fd9a16000 rw-p 00015000 08:02 47972521                       /lib64/libz.so.1.2.3
3fdf000000-3fdf016000 r-xp 00000000 08:02 47972428                       /lib64/libgcc_s-4.4.7-20120601.so.1
3fdf016000-3fdf215000 ---p 00016000 08:02 47972428                       /lib64/libgcc_s-4.4.7-20120601.so.1
3fdf215000-3fdf216000 rw-p 00015000 08:02 47972428                       /lib64/libgcc_s-4.4.7-20120601.so.1
3fdf400000-3fdf4e8000 r-xp 00000000 08:02 27527830                       /usr/lib64/libstdc++.so.6.0.13
3fdf4e8000-3fdf6e8000 ---p 000e8000 08:02 27527830                       /usr/lib64/libstdc++.so.6.0.13
3fdf6e8000-3fdf6ef000 r--p 000e8000 08:02 27527830                       /usr/lib64/libstdc++.so.6.0.13
3fdf6ef000-3fdf6f1000 rw-p 000ef000 08:02 27527830                       /usr/lib64/libstdc++.so.6.0.13
3fdf6f1000-3fdf706000 rw-p 00000000 00:00 0
7f8368000000-7f8368021000 rw-p 00000000 00:00 0
7f8368021000-7f836c000000 ---p 00000000 00:00 0
7f836ffff000-7f8370000000 rw-p 00000000 00:00 0
7f8370000000-7f8373a4f000 rw-p 00000000 00:00 0
7f8373a4f000-7f8374000000 ---p 00000000 00:00 0
7f83750e5000-7f83750e6000 ---p 00000000 00:00 0
7f83750e6000-7f8375aec000 rw-p 00000000 00:00 0
7f8375b1c000-7f8375b1f000 rw-p 00000000 00:00 0
7ffeb636e000-7ffeb6383000 rw-p 00000000 00:00 0                          [stack]
7ffeb63d7000-7ffeb63d8000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)
--------------------------------

I have tried running the program with multiple option with different -p values (1/2/4/6/8/32) with similar error message. I also played around with changing default values for -f, -a, -j and met similar fate.  

Since I am interested in finding novel isoforms, I would like to run the program with a reference GTF.  Can you please suggest if I'm going wrong somewhere or if it's the build issue?

Thanks a ton for the update again!

**Comment by gpertea** [comment]
Could you please verify if you have been running v2.0.6 when you experienced these crashes -- instead of v2.0.5 that was the first patched release that worked for CentOS 6 as per #251 ? Unfortunately that v2.0.5 release was affected by a regression bug that caused this kind of crashes (not matter the value of the -p option). Do you have v2.0.6 installed there? (`stringtie --version` should show the version).

**Comment by asmitagpta** [comment]
Ah! Yes..v2.0.5 it was.  I have installed v2.0.6 and ran few samples with it. Works fine now. 

Thanks!
