### ISSUE TITLE
stringtie-2.0.6 GBitVec: index 45 out of bounds

### ISSUE THREAD

**Issue by kylepalos** [gpertea/stringtie#259]
Hello,

Thank you for writing stringtie, it has been incredibly helpful in my research. I am assembling transcripts from Oxford Nanopore cDNA reads aligned using minimap2. For one of my assemblies, I receive the following error:

`sudo /path/to/stringtie-2.0.6.Linux_x86_64/stringtie -L -G reference.gtf -o output.gtf input.bam`
`Error at GBitVec: index 45 out of bounds (size 45)`

I had other sequencing data assemble fine with the same reference annotation.
I extracted the problem bundle and relevant reference annotation, [suggested here](https://github.com/gpertea/stringtie/wiki/Extracting-bundle-data-for-debugging).

[Here is the problem alignment and the relevant annotation.](https://drive.google.com/open?id=1vmcpZDkG6ApCDwfFnShgbokfqxpMPQkM)

Please let me know if you need any other information regarding the issue.

Thank you very much for your assistance.
Kyle Palos

**Comment by gpertea** [comment]
Thank you for the thorough report and for providing the perfect data for debugging, the bug is confirmed (reproduced it on the provided data) and debugging will start soon.
