### ISSUE TITLE
Runtime Error: Error at GBitVec 

### ISSUE THREAD

**Issue by ramberg** [gpertea/stringtie#26]
After your suggestion on Biostars regarding the Runtime Error:

    'Error at GBitVec: index 7 out of bounds (size 7)'

I updated StringTie to version 1.1.1, but the error keeps happening. After using the parameter `-v` the following lines are the last before StringTie crashes:

    [11/08 14:57:59]>bundle 6:1383650-1383656(1) (0 guides) loaded, begins processing...
    [11/08 14:57:59]Number of fragments in bundle: 1 with sum 7
    ^bundle 6:1383650-1383656(1) done (0 processed potential transcripts).
    [11/08 14:57:59]>bundle 6:1383790-1389117(31) (1 guides) loaded, begins processing...
    Error at GBitVec: index 7 out of bounds (size 7)

Maybe I misunderstand the parameter `-c`, I increased the default value to `10` but the error stays.

**Comment by gpertea** [comment]
Sorry about that, I guess we missed a particular case where such an error may still surface.
We'd really like to take a look at that particular bundle -- if possible, please extract the alignments in that bundle 6:1383790-1389117 (using samtools view -b after indexing the .bam file) and send the resulting bam file and the annotation file to us.

**Comment by ramberg** [comment]
I created the region (and removed some additional reads) and uploaded my bam file for that bundle to my google drive:
https://drive.google.com/file/d/0B4X48NnBh1acc0Z0SVpxLUowZWM/view?usp=sharing

I'm using the GTF from ensembl 80:
ftp://ftp.ensembl.org/pub/release-80/gtf/homo_sapiens/Homo_sapiens.GRCh38.80.gtf.gz

The reads never went through quality control or any other type of pre-processing. They are just a bunch of test reads straight from the sequencer into the aligner.

Thx

**Comment by gpertea** [comment]
Thank you a lot for this example, it allowed us to quickly locate and fix the problem.The fixed version is the just-released v1.1.2 of stringtie.

**Comment by ramberg** [comment]
Thank you. Works like a charm.
