### ISSUE TITLE
stringtie v2.1.0 stalls with -L option unless -t also specified

### ISSUE THREAD

**Issue by biorover** [gpertea/stringtie#260]
Hello, I'm finding that stringtie2 seems to have trouble calculating trimming for a moderate coverage of long reads. In about 7Gbp of stranded long read alignments, there are about four blocks where stringtie stalls out and cannot progress through when run with the -L option. I've thoroughly investigated one of these blocks and found that there's a 3000 record chunk in the sorted bam file that causes the stall. Interestingly, stringtie can get through the first 2000, and the last 2000, but not all 3000 at once.

Running with the -t option (disabling trimming) allows stringtie to process the whole file. I also know that too many junctions are likely not the problem (I've seen this issue while searching through the known issues) because there's only seven junctions in those 3000 records.

For know, I'll use with "-t", but I do find the coverage trimming very useful...

**Comment by gpertea** [comment]
Thank you for this report! Ouch, indeed it looks like the new trimming code in v2.1.0 might have run into a situation we haven't accounted for yet. Could you please share one of the blocks (bundles?) where that happens in your data? We're eager to correct that. Please see https://github.com/gpertea/stringtie/wiki/Extracting-bundle-data-for-debugging and if you can share data for one example bundle where that stalling occurs that would be a great help in fixing this ASAP. Thank you!

**Comment by biorover** [comment]
Absolutely! Running with -v, it seems like all the 3000 above mentioned bam records are in the same bundle ("[01/29 10:01:13]>bundle Chr1:16574017-16623814 [3000 alignments (2362 distinct), 57 junctions, 0 guides] begins processing..."). The bam file is attached.
[testPartition2a.bam.gz](https://github.com/gpertea/stringtie/files/4128735/testPartition2a.bam.gz)

**Comment by gpertea** [comment]
Got it -- thanks a lot! Wow, such a small file. It looks like the stalling (an infinite loop most likely ) happens even without any guides. The fix (and I suppose v2.1.1) should become available soon. Thanks again for that data.

**Comment by biorover** [comment]
Just made stringtie from source following your update to the master branch and it worked like a charm- thanks!!! Super appreciate the speed of your help!!!
