### ISSUE TITLE
Transcripts of only one exon

### ISSUE THREAD

**Issue by reutnuri** [gpertea/stringtie#261]
Hi, 

I used STAR for mapping short reads to genome.
I ran StringTie with the following command: 
stringtie  sorted_Aligned.out.bam -p 20  -A stringtie_run5.tab -o stringtie__5.gtf  -l new.strg -p 12 -j 2

My output GTF file contains only transcripts of a single exon. Checked it in IGV and there are adjacent exons that could be joined to transcripts.

Can anyone help me understand what went wrong in my run?

Thanks!!

**Comment by gpertea** [comment]
I do not have experience with STAR, I hope you made sure to run it with the appropriate options for RNA-Seq data and suitable for transcript assembly (there should be something in the STAR manual about what options to use for Cufflinks or transcript assembly in general).
Also, do you actually see intron-spanning read alignments in IGV ? You mentioned you see that there are adjacent exons where reads were mapped, but are there read alignments actually spanning those multiple exons, with actual intron gaps in the alignment?

**Comment by reutnuri** [comment]
Thanks for your quick response!
Yes, I see reads spanning over exons. 
However, I did not used the Cufflinks option, I will try to run it again and see if it solves the problem.
Will update if it solves the problem. 
Thanks again :)

**Comment by reutnuri** [comment]
It was indeed an issue with Star for preparing the DB for Cufflinks. 
Many thanks!
