### ISSUE TITLE
Question: Does the bam file needs indexing ?

### ISSUE THREAD

**Issue by Tdanis** [gpertea/stringtie#266]
Hello, I am taking the out sam file from my mapper and I am trying to convert it in bam format.

The command that I am using is this:

#/mnt/big/Tools/samtools-1.9/samtools view -S(b)u -@20 Aligned.out.sam  > alg.bam 
#/mnt/big/Tools/samtools-1.9/samtools sort alg.bam -@20 -o ./alg.sorted.bam 
#/mnt/big/Tools/samtools-1.9/samtools index alg.sorted.bam 
 
is it correct? or indexing step is unnecessary? 

Thank you

**Comment by gpertea** [comment]
StringTie does not need or use a BAM index.
