### ISSUE TITLE
TPMs quantified as zero or values larger than zero depending on the StringTie options

### ISSUE THREAD

**Issue by AndreVelasquez** [gpertea/stringtie#269]
Hello,

I am analyzing a bacterial transcriptome, for which I aligned single-end reads to the genome using HISAT2 (version 2.1.0; disabling the splice-aware option). I am trying to use StringTie (version 1.3.5) to quantify transcript abundance.
However, I have noticed that when I quantify the transcripts using the -e option (to not estimate predicted transcripts but only those specified in the GFF file), certain low-expressed genes have TPM (and FPKM) values of zero, while these values are larger than zero when I allowed StringTie to predict transcripts and quantify those transcripts plus those that are specified in the GFF file. Some genes with  low expression do not show this behavior, nor is the behavior exclusive to genes in which StringTie did not predict new transcripts (STRG). Certain genes do correctly have TPM values of zero irrespective of how StringTie is executed. This issue is observed in both the t_data.ctab and stringtie_abundances.tab output files. 
Genes having TPMs of zero do have reads mapped to them, as when I visualize the SAM alignment (in IGV), I can see reads mapping to those genes.
Would anyone know what could be causing this phenomenon?

Command that yields zero TPMs for certain genes:
stringtie -G Genome.gff3 Reads_sorted.bam -p 8 -e -B -o stringtie.gtf -A stringtie_abundances.tab 

Example of gene with zero TPMs:
**Gene ID	Gene Name	Reference	Strand	Start	End	Coverage	FPKM	TPM**
gene-PSPTO_0003	recF	AE016853.1	+	3039	4142	0.000000	0.000000	0.000000

Command that yields >0 TPMs for the same genes:
stringtie -G Genome.gff3 Reads_sorted.bam -p 8 -B -o stringtie.gtf -A stringtie_abundances.tab -C stringtie_cov_refs.gtf

Example of the same gene with >0 TPMs:
**Gene ID	Gene Name	Reference	Strand	Start	End	Coverage	FPKM	TPM**
gene-PSPTO_0003	recF	AE016853.1	+	3039	4142	3.493659	40.313282	29.136240

Thank you.

**Comment by gpertea** [comment]
(discussion continued by email)
