### ISSUE TITLE
Single exon genes

### ISSUE THREAD

**Issue by filicado** [gpertea/stringtie#27]
Whenever I run cuffmerge post Stringtie it gives me "GFF Error: duplicate/invalid 'mRNA' feature" for a number of loci

Seems the only thing they have in common is the fact that they have only 1 exon per gene

Is this a known bug?

**Comment by gpertea** [comment]
That's not a known bug and I'd like to understand how you got to it. That error message should only appear in the case of multiple overlapping mRNAs with the same ID, found in a single input GTF/GFF file.. That shouldn't happen, if each of the input files for cuffmerge are the unmodified output GTF as generated by StringTie. I tried to reproduce the error on a quick example here but couldn't - but if you could find and share some or one of the input files which generated the error(s) it would be great. 
I'm also curious:
 *  what versions of cuffmerge & stringtie gave you these errors?
 *  I suppose the mRNA IDs reported in those error messages are from the individual GTFs produced by StringTie, not the reference annotation file, right? If you grep one of those mRNA IDs in each of the input files, do you see anything unusual ? (e.g. multiple "transcript" lines with the same transcript_id in the same file?)

Again, if you can share one or two GTF files which trigger that error message it would be very helpful. I realize you might have a lot of files in that list for cuffmerge and the error is not helping with identifying which files are triggering the error. You could run gffread on each of them individually (simply ``gffread file.gtf`` with no other options) and you should get the same error message for the affected files.

**Comment by filicado** [comment]
So it turns out this was my bad. When my script merged the GTF files it accidentally also added the ones from the -C <cov_refs.gtf> option to the list.
Why the error happens with those at only some loci I'm not sure. So the bug may exist but in my case when I just merge the proper -o outfile.gtf files all works fine.
