### ISSUE TITLE
Stringtie --merge segfaults with pinfish input

### ISSUE THREAD

**Issue by conchoecia** [gpertea/stringtie#273]
Hi Geo and friends-

I'm trying to use stringtie --merge to make a non-redundant geneset using files from multiple programs like AUGUSTUS, GeneMark-ET, pinfish, et cetera. Not sure if you're supporting using stringtie --merge this way, but it seems to be one of the few pieces of easy-to-use software that performs transcript merging.

I tried to use stringtie --merge on the output of [pinfish](https://github.com/nanoporetech/pinfish) using the latest stringtie release (v2.1.2), and it segfaults. The error is just `7688 Segmentation fault`. I've uploaded the gzipped gtf in case you want to try to reproduce this. 

Thank you-

[pinfish_output.gtf.gz](https://github.com/gpertea/stringtie/files/4599811/pinfish_output.gtf.gz)

**Comment by gpertea** [comment]
We looked into this issue (thank you for providing the example file) and it is now fixed in version 2.1.3 of StringTie that we just released.

**Comment by conchoecia** [comment]
Wonderful. Thank you, @gpertea!
