### ISSUE TITLE
./samtools-0.1.18/bgzf.h:29:10: fatal error: zlib.h: No such file or directory

### ISSUE THREAD

**Issue by THZ34** [gpertea/stringtie#274]
Dear gpertea,
The program installation failed course of './samtools-0.1.18/bgzf.h:29:10: fatal error: zlib.h: No such file or directory'

The following is all report during installing:
make release
cd ./samtools-0.1.18 && make lib
make[1]: Entering directory '/home/tanghongzhen/software/stringtie-2.1.3/samtools-0.1.18'
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bgzf.c -o bgzf.o
bgzf.c: In function ‘bgzf_check_EOF’:
bgzf.c:677:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(buf, 1, 28, fp->file);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. kstring.c -o kstring.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_aux.c -o bam_aux.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam.c -o bam.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_import.c -o bam_import.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. sam.c -o sam.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_index.c -o bam_index.o
bam_index.c: In function ‘bam_index_load_core’:
bam_index.c:330:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(magic, 1, 4, fp);
  ^~~~~~~~~~~~~~~~~~~~~~
bam_index.c:337:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(&idx->n, 4, 1, fp);
  ^~~~~~~~~~~~~~~~~~~~~~~~
bam_index.c:350:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(&size, 4, 1, fp);
   ^~~~~~~~~~~~~~~~~~~~~~
bam_index.c:353:4: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
    fread(&key, 4, 1, fp);
    ^~~~~~~~~~~~~~~~~~~~~
bam_index.c:357:4: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
    fread(&p->n, 4, 1, fp);
    ^~~~~~~~~~~~~~~~~~~~~~
bam_index.c:361:4: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
    fread(p->list, 16, p->n, fp);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
bam_index.c:371:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(&index2->n, 4, 1, fp);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
bam_index.c:375:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(index2->offset, index2->n, 8, fp);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_pileup.c -o bam_pileup.o
bam_pileup.c: In function ‘resolve_cigar2’:
bam_pileup.c:75:9: warning: variable ‘is_head’ set but not used [-Wunused-but-set-variable]
  int k, is_head = 0;
         ^~~~~~~
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_lpileup.c -o bam_lpileup.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_md.c -o bam_md.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. razf.c -o razf.o
razf.c: In function ‘razf_flush’:
razf.c:223:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   write(rz->filedes, rz->outbuf, RZ_BUFFER_SIZE - rz->stream->avail_out);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
razf.c:236:4: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
    write(rz->filedes, rz->outbuf, RZ_BUFFER_SIZE - rz->stream->avail_out);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
razf.c: In function ‘_razf_write’:
razf.c:203:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   write(rz->filedes, rz->outbuf, RZ_BUFFER_SIZE - rz->stream->avail_out);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
razf.c: In function ‘razf_open_r’:
razf.c:422:3: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &end, sizeof(int64_t));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
razf.c:430:3: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &end, sizeof(int64_t));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
razf.c: In function ‘load_zindex’:
razf.c:124:2: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
  read(fd, &rz->index->size, sizeof(int));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
razf.c:133:2: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
  read(fd, rz->index->bin_offsets, sizeof(int64_t) * v32);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
razf.c:139:2: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
  read(fd, rz->index->cell_offsets, sizeof(int) * rz->index->size);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
razf.c: In function ‘razf_close’:
razf.c:815:4: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
    write(rz->filedes, &rz->in, sizeof(int64_t));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
razf.c:816:4: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
    write(rz->filedes, &rz->out, sizeof(int64_t));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
razf.c:819:4: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
    write(rz->filedes, &v64, sizeof(int64_t));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
razf.c:821:4: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
    write(rz->filedes, &v64, sizeof(int64_t));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
razf.c: In function ‘razf_end_flush’:
razf.c:260:4: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
    write(rz->filedes, rz->outbuf, RZ_BUFFER_SIZE - rz->stream->avail_out);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
razf.c: In function ‘save_zindex’:
razf.c:96:12: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
  if(is_be) write(fd, &rz->index->size, sizeof(int));
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
razf.c:99:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   write(fd, &v32, sizeof(uint32_t));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
razf.c:106:2: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
  write(fd, rz->index->bin_offsets, sizeof(int64_t) * v32);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
razf.c:107:2: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
  write(fd, rz->index->cell_offsets, sizeof(int32_t) * rz->index->size);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. faidx.c -o faidx.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bedidx.c -o bedidx.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_sort.c -o bam_sort.o
In file included from bam_sort.c:9:0:
bam_sort.c:309:26: warning: ‘bam1_lt’ is static but used in inline function ‘__ks_insertsort_sort’ which is not static
 KSORT_INIT(sort, bam1_p, bam1_lt)
                          ^
ksort.h:148:25: note: in definition of macro ‘KSORT_INIT’
    for (j = i; j > s && __sort_lt(*j, *(j-1)); --j) {   \
                         ^~~~~~~~~
bam_sort.c:53:27: warning: ‘heap_lt’ is static but used in inline function ‘__ks_insertsort_heap’ which is not static
 KSORT_INIT(heap, heap1_t, heap_lt)
                           ^
ksort.h:148:25: note: in definition of macro ‘KSORT_INIT’
    for (j = i; j > s && __sort_lt(*j, *(j-1)); --j) {   \
                         ^~~~~~~~~
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. sam_header.c -o sam_header.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_reheader.c -o bam_reheader.o
bam_reheader.c: In function ‘bam_reheader’:
bam_reheader.c:11:16: warning: variable ‘old’ set but not used [-Wunused-but-set-variable]
  bam_header_t *old;
                ^~~
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. kprobaln.c -o kprobaln.o
kprobaln.c: In function ‘kpa_glocal’:
kprobaln.c:78:21: warning: variable ‘is_diff’ set but not used [-Wunused-but-set-variable]
  int bw, bw2, i, k, is_diff = 0, is_backward = 1, Pr;
                     ^~~~~~~
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_cat.c -o bam_cat.o
/home/tanghongzhen/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ar -csru libbam.a bgzf.o kstring.o bam_aux.o bam.o bam_import.o sam.o bam_index.o bam_pileup.o bam_lpileup.o bam_md.o razf.o faidx.o bedidx.o bam_sort.o sam_header.o bam_reheader.o kprobaln.o bam_cat.o
make[1]: Leaving directory '/home/tanghongzhen/software/stringtie-2.1.3/samtools-0.1.18'
/home/tanghongzhen/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++0x -fno-strict-aliasing -fno-exceptions -fno-rtti -Wno-implicit-fallthrough -pthread -c gclib/GBase.cpp -o gclib/GBase.o
/home/tanghongzhen/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++0x -fno-strict-aliasing -fno-exceptions -fno-rtti -Wno-implicit-fallthrough -pthread -c gclib/GArgs.cpp -o gclib/GArgs.o
/home/tanghongzhen/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++0x -fno-strict-aliasing -fno-exceptions -fno-rtti -Wno-implicit-fallthrough -pthread -c gclib/GStr.cpp -o gclib/GStr.o
/home/tanghongzhen/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++0x -fno-strict-aliasing -fno-exceptions -fno-rtti -Wno-implicit-fallthrough -pthread -c gclib/GBam.cpp -o gclib/GBam.o
In file included from ./samtools-0.1.18/bam.h:52:0,
                 from gclib/GBam.h:5,
                 from gclib/GBam.cpp:1:
./samtools-0.1.18/bgzf.h:29:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
make: *** [Makefile:139: gclib/GBam.o] Error 1

**Comment by gpertea** [comment]
>  fatal error: zlib.h: No such file or directory

It looks like the zlib development package is not installed on your system. Depending on your Linux distribution the package to be installed can have different names (`zlib-devel` for RedHat based systems, `zlib1g-dev` for Debian based systems etc.)
