### ISSUE TITLE
Why are many Strands in my results a "."?

### ISSUE THREAD

**Issue by jmzhang1911** [gpertea/stringtie#288]
![image](https://user-images.githubusercontent.com/52552382/87785373-a21b2d00-c86a-11ea-8095-229c6b7cf7bb.png)

**Comment by daniel-spies** [comment]
Same here, I also got ~5k transcripts with a "." strand, all those are novel transcripts not found in the reference GTF file. But as they mapped back to the genome and have clear coordinates, why is the strand not denoted properly?

thanks for some feedback

**Comment by davidprince84** [comment]
I am also seeing "." in the strand column in the GTF file that StringTie2 produces when using HISAT2 aligned paired-end reads. The meaning of "." is not covered in the StringTie manual. Please could you clarify? 

Thanks
