### ISSUE TITLE
Error: could not execute cuffcompare

### ISSUE THREAD

**Issue by tiramisutes** [gpertea/stringtie#29]
Hi,
when i used stringtie output results gtf format files run cuffmerge , I have got some error, whether anyone can help me?
this is my code:
cuffmerge -g gene.gtf -s genome.fa  -o stringtie_cuffmerge  assemblies.txt
cuffmerge error:
Error (GFaSeqGet): end coordinate (65894153) cannot be larger than sequence length 65894135
Error (GFaSeqGet): end coordinate (65894153) cannot be larger than sequence length 65894135
Error (GFaSeqGet): end coordinate (65894153) cannot be larger than sequence length 65894135
Error (GFaSeqGet): end coordinate (65894153) cannot be larger than sequence length 65894135
Error (GFaSeqGet): end coordinate (511) cannot be larger than sequence length 502
Error (GFaSeqGet): end coordinate (515) cannot be larger than sequence length 498
Error (GFaSeqGet): end coordinate (495) cannot be larger than sequence length 490
Error (GFaSeqGet): subsequence cannot be larger than 484
Error getting subseq for CUFF.60225.1 (1..502)!
	[FAILED]
Error: could not execute cuffcompare
Thanks.

**Comment by gpertea** [comment]
There is not enough information to tell what was going on there (were all the assemblies in assemblies.txt generated by StringTie?). I seem to recall that Cufflinks had an alignment (CIGAR) parsing issue (soft clipping in particular) causing transfrag end coordinates to go past the end of the reference sequence -- when a bundle was extremely close to the end of the ref. seq. But we haven't encountered a similar problem with assemblies generated by StringTie..

However, we're currently working on a complete cuffmerge replacement by using a new, special option in stringtie - so there will be no more dependencies on programs from the Cufflinks package.

**Comment by roryk** [comment]
Hi Geo,

Any chance at implementing the class_codes or an equivalent from Cuffcompare into the `stringtie --merge`? It is the last thing left that is missing for a total replacement for us.

**Comment by gpertea** [comment]
I didn't realize people still cared about those classification codes (glad to hear that's the case). As that is not really necessary for the main pipeline, I'm thinking to make this an optional, separate step for those who want it -- they can run ``gffcompare`` (which is essentially the new, more generic name for ``cuffcompare``, with some new features planned), streamlined a bit as to cleanly annotate the merged GTF file with all those class codes, super-loci (XLOC* clusters), gene names etc. The current gffcompare version can be used for this already but it's unnecessarily renaming the transcripts so I will just implement a more transparent annotation mode for this in the next week or so.

The thing is, Stringtie's code is already getting a bit large so I'd rather not pile up cuffcompare's tedious transcript classification code on top of it (though I agree it would be more efficient that way..).

**Comment by roryk** [comment]
Thanks Geo, totally understand about wanting to keep the code base uncluttered. I wish I was a good enough programmer where I could casually throw out that I'd implement that in about a week. :)

**Comment by gpertea** [comment]
Late update to this -- I had released gffcompare 0.9.5 (http://ccb.jhu.edu/software/stringtie/gff.shtml#gffcompare), when run with -r and -G options (I advise using -R as well, to correct for sensitivity calculation), now generates a <prefix>.annotated.gtf file with a lot of GTF attributes (including "class_code") while keeping the original transcript_id and gene_id intact etc.

**Comment by roryk** [comment]
Thanks Geo, that is awesome.

**Comment by gpertea** [comment]
Just discovered there was a terribly silly but fatally crippling bug in v0.9.5 which caused gffcompare to just hang there on (some?) machines, with zero size output files and never finishing! It was a double fclose()/locking bug which I fixed yesterday and released v0.9.6, in case anyone was having the same problem with v0.9.5 -- sorry about that.
