### ISSUE TITLE
create_rna_sr.py gets Killed during "assign_reads" step

### ISSUE THREAD

**Issue by bfpedro** [gpertea/stringtie#299]
Hello,

I am trying out Stringtie2 and everything is running fine in the create_rna_sr.py script. The only part where I'm stuck is when the script calls assign_reads. It runs for a few minutes, then crashes. I tried running it separately, with different number of threads available, but it always gets killed after a while.
Below is an example of the run with 2 threads (tried with 2, 4, 6, and 8):

assign_reads -p 2 -w ./work1 -s sr.sam -o sr_quant.sam
Building super-read index...
Parsing SAM file...
Removing duplicates...
Parsing SR file...
Index built, assigning reads...
Killed

Any suggestions on how to proceed? 

Pedro

**Comment by bfpedro** [comment]
Update (a day later):

I tried several "-b" options in assign_reads, and every time it reaches the memory limit, then gets killed.
I also tried to change the JF_SIZE parameter a few times to no avail.

My data is roughly: A 4.5B bp genome, 50M paired-end (100M reads total) Illumina reads. I am trying to run the script in a 8-core Intel i7 with 16G RAM laptop.

Every step runs successfully except for the assign_reads step.
Is it not possible to run on a laptop such as mine?

Any suggestions or workarounds are welcome!

Pedro

**Comment by skovaka** [comment]
We haven't done very thorough profiling of the memory requirements for super-read construction, but we just ran tests on two human runs, each with ~50M paired-end reads, and each required 14.1-14.4GB of memory. Your genome is larger than human, and your transcriptome may have a greater sequence diversity which would require more super-reads, so it makes sense that it might require more memory. Unfortunately we can't make an accurate prediction of how much memory you'll need without actually running it, but just based on the difference in genome size I can guess you would need ~40% more memory, so 20GB? That's an extremely rough estimate, and additional memory would not hurt. Sorry we can't offer better guidelines, we may try more thorough profiling in the future.

**Comment by bfpedro** [comment]
Thank you for the reply Sam.
I tried increasing my swap memory (it was too low), and it worked! In the end, total memory requirement was of ~19G with default parameters.
I will close the issue now.
