### ISSUE TITLE
Error setting up Ballgown coverage data (lmin should never change!) !

### ISSUE THREAD

**Issue by cfblaeb** [gpertea/stringtie#31]
I get the following error:
Error setting up Ballgown coverage data (lmin should never change!) !

After running:
stringtie s1.bam -G ../genome/combined.gff -o s1/s1.gtf -p 1 -B -v
s1.bam was made by tophat.
3 extremely overexpressed genes are located on 3 plasmids.

**Comment by gpertea** [comment]
Is this happening with the last version of stringtie? I remember fixing a similar issue recently, though the fix might not have made it in the last binary release.. 
The case I fixed was essentially an user input error - the GTF/GFF file provided for the -G option had some incorrect coordinates for the transcript (mRNA) features, with the terminal exon coordinates (min and max) not matching their parent feature (i.e. mRNA/transcript) span coordinates, which triggered a sorting issue within StringTie and led to the error you encountered. 
Not sure how you built your ../genome/combined.gff (was it hand crafted?) but I suspect it has a similar problem. A quick fix would be to run this file once through **gffread** (utility found in the Cufflinks distribution) which should fix those coordinates for you, something like this:
 ``gffread ../genome/combined.gff -o fixed.gff
``
.. and then use the resulting *fixed.gff* file with StringTie instead of your original GFF file.

**Comment by cfblaeb** [comment]
Hi, Thanks for the quick reply.
So I tried using gffread and when using the resulting gff file stringtie did indeed run without issue. 

However I am not convinced that my GFF is "bad":

Its from NCBI with 9 lines added by me: (ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Cricetulus_griseus/latest_assembly_versions/GCF_000223135.1_CriGri_1.0/GCF_000223135.1_CriGri_1.0_genomic.gff.gz) 

Gffread, doesnt change those 9 lines much. See below: 
My added 9 lines: 
neoR_contig	laeb	gene	1	1257	.	+	.	ID=NeoRKanR_gene;gene=NeoRKanR;product=NeoRKanR;transcript_id=NeoRKanR;gene_id=5
neoR_contig	laeb	mRNA	1	1257	.	+	.	ID=NeoRKanR_mRNA;Parent=NeoRKanR_gene;gene=NeoRKanR;product=NeoRKanR;transcript_id=NeoRKanR;gene_id=5
neoR_contig	laeb	exon	1	1257	.	+	.	ID=NeoRKanR_exon;Parent=NeoRKanR_mRNA;gene=NeoRKanR;product=NeoRKanR;transcript_id=NeoRKanR;gene_id=5
neoR_contig	laeb	CDS	155	949	.	+	0	ID=NeoRKanR_CDS;Parent=NeoRKanR_mRNA;gene=NeoRKanR;product=NeoRKanR;transcript_id=NeoRKanR;gene_id=5
lightchain_contig	laeb	gene	1	1312	.	+	.	ID=lightchain_gene;gene=lightchain;product=lightchain;transcript_id=lightchain;gene_id=6
lightchain_contig	laeb	mRNA	1	1312	.	+	.	ID=lightchain_mRNA;Parent=lightchain_gene;gene=lightchain;product=lightchain;transcript_id=lightchain;gene_id=6
lightchain_contig	laeb	exon	1	1312	.	+	.	ID=lightchain_exon;Parent=lightchain_mRNA;gene=lightchain;product=lightchain;transcript_id=lightchain;gene_id=6
lightchain_contig	laeb	CDS	89	805	.	+	0	ID=lightchain_CDS;Parent=lightchain_mRNA;gene=lightchain;product=lightchain;transcript_id=lightchain;gene_id=6
heavychain_contig	laeb	gene	1	2087	.	+	.	ID=heavychain_gene;gene=heavychain;product=heavychain;transcript_id=heavychain;gene_id=7
heavychain_contig	laeb	mRNA	1	2087	.	+	.	ID=heavychain_mRNA;Parent=heavychain_gene;gene=heavychain;product=heavychain;transcript_id=heavychain;gene_id=7
heavychain_contig	laeb	exon	1	2087	.	+	.	ID=heavychain_exon;Parent=heavychain_mRNA;gene=heavychain;product=heavychain;transcript_id=heavychain;gene_id=7
heavychain_contig	laeb	CDS	234	1637	.	+	0	ID=heavychain_CDS;Parent=heavychain_mRNA;gene=heavychain;product=heavychain;transcript_id=heavychain;gene_id=7

gffread changed them into:

heavychain_contig	laeb	mRNA	1	2087	.	+	.	ID=heavychain_mRNA;geneID=7;gene_name=heavychain
heavychain_contig	laeb	exon	1	2087	.	+	.	Parent=heavychain_mRNA
heavychain_contig	laeb	CDS	234	1637	.	+	0	Parent=heavychain_mRNA
lightchain_contig	laeb	mRNA	1	1312	.	+	.	ID=lightchain_mRNA;geneID=6;gene_name=lightchain
lightchain_contig	laeb	exon	1	1312	.	+	.	Parent=lightchain_mRNA
lightchain_contig	laeb	CDS	89	805	.	+	0	Parent=lightchain_mRNA
neoR_contig	laeb	mRNA	1	1257	.	+	.	ID=NeoRKanR_mRNA;geneID=5;gene_name=NeoRKanR
neoR_contig	laeb	exon	1	1257	.	+	.	Parent=NeoRKanR_mRNA
neoR_contig	laeb	CDS	155	949	.	+	0	Parent=NeoRKanR_mRNA

**Comment by cfblaeb** [comment]
Also when I got to the cuffmerge step it failed due to duplicate ID.
It turns out that there were no duplicate ID's in my original GFF, but the one that gffread produces contains multiple duplicate ID's....

**Comment by gpertea** [comment]
You are correct, the GFF (including the lines you added) does not seem to be "bad", it just has a lot of unusual and overlapped features which seem to be confusing the parser (I'm still looking into the details right now).
Also, you are right about gffread, the 2014 version you are likely using does create duplicate IDs for some of those unusual features in that NCBI gff file, though this is no longer the case with the current version (which has not been released yet, but it will be made available soon). 

I am working on a full fix - meanwhile as an interim solution you can try converting your original GFF with the new gffread (which should no longer produce duplicate IDs for that file), which I just made available here:
 http://ccb.jhu.edu/software/stringtie/dl/gffread-0.9.4.tar.gz (source)
 http://ccb.jhu.edu/software/stringtie/dl/gffread-0.9.4.Linux_x86_64.tar.gz (linux binary)

**Comment by gpertea** [comment]
We just released version 1.2.0 of StringTie and we also provide now official downloads for the latest version of gffread at http://ccb.jhu.edu/software/stringtie/gff.shtml . It would be great if you can check if the new StringTie version fixed this problem as well.
