### ISSUE TITLE
GVec error: invalid index: 18

### ISSUE THREAD

**Issue by gianfilippo** [gpertea/stringtie#318]
Hi,

I am using stringtie 2.0 on about 450 files. On a few occasions I get the following error:
GVec error: invalid index: 18

I could not figure out the reason for the error, and, on those files I used stringtie 1.3.3, which did not produce any error.

Unfortunately I had not realized that I would end up with a problem somewhere down the line. 
Now, when I use tximport, I get an error (see below), which seems to be related to the different N of rows of the .tab file produced by stringtie.
Do you have any suggestion on how to get around the GVec error ?
Thanks

======================================================
Error in tximport(ctab_files[-c(1:30)], type = "stringtie", tx2gene = tx2gene) : 
  all(txId == raw[[txIdCol]]) is not TRUE
In addition: Warning message:
In txId == raw[[txIdCol]] :
  longer object length is not a multiple of shorter object length

**Comment by gpertea** [comment]
Are you using the latest v2.0.4 release from https://github.com/gpertea/stringtie/releases or http://ccb.jhu.edu/software/stringtie/#install ?

**Comment by gpertea** [comment]
Sorry, I meant v2.1.4, which is the current version -- the older v2.0 releases had some issues like the one you described, but those were ironed out in the later releases.

**Comment by gianfilippo** [comment]
Hi,

thanks for getting back to me so quickly!

I was using the 2.0 installed on the available cluster. After I reported
the issue I realized the now 2.1.4 is available, so I just started
reprocessing all the samples

Hopefully it will complete without issues.

Thanks
Gianfilippo

**Comment by gianfilippo** [comment]
I am having a different issue with ver 2.1.4. I am closing this and opening a new issue
Thanks
