### ISSUE TITLE
Unable to load stringtie in Linux 

### ISSUE THREAD

**Issue by kchen96** [gpertea/stringtie#326]
Hi, I installed stringtie on a linux system via: 

`    git clone https://github.com/gpertea/stringtie
     cd stringtie
     make release`

And I got a few warnings, not sure if the installation was successful

`
cd ./samtools-0.1.18 && make lib
make[1]: Entering directory `/wynton/home/jainlab/kchen96/stringtie/samtools-0.1.18'
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bgzf.c -o bgzf.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. kstring.c -o kstring.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_aux.c -o bam_aux.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam.c -o bam.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_import.c -o bam_import.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. sam.c -o sam.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_index.c -o bam_index.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_pileup.c -o bam_pileup.o
bam_pileup.c: In function ‘resolve_cigar2’:
bam_pileup.c:75:9: warning: variable ‘is_head’ set but not used [-Wunused-but-set-variable]
  int k, is_head = 0;
         ^
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_lpileup.c -o bam_lpileup.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_md.c -o bam_md.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. razf.c -o razf.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. faidx.c -o faidx.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bedidx.c -o bedidx.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_sort.c -o bam_sort.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. sam_header.c -o sam_header.o
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_reheader.c -o bam_reheader.o
bam_reheader.c: In function ‘bam_reheader’:
bam_reheader.c:11:16: warning: variable ‘old’ set but not used [-Wunused-but-set-variable]
  bam_header_t *old;
                ^
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. kprobaln.c -o kprobaln.o
kprobaln.c: In function ‘kpa_glocal’:
kprobaln.c:78:21: warning: variable ‘is_diff’ set but not used [-Wunused-but-set-variable]
  int bw, bw2, i, k, is_diff = 0, is_backward = 1, Pr;
                     ^
gcc -c -g -Wall -fsigned-char -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_cat.c -o bam_cat.o
ar -csru libbam.a bgzf.o kstring.o bam_aux.o bam.o bam_import.o sam.o bam_index.o bam_pileup.o bam_lpileup.o bam_md.o razf.o faidx.o bedidx.o bam_sort.o sam_header.o bam_reheader.o kprobaln.o bam_cat.o
make[1]: Leaving directory `/wynton/home/jainlab/kchen96/stringtie/samtools-0.1.18'
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++11 -fno-strict-aliasing -fno-exceptions -fno-rtti -pthread -c gclib/GBase.cpp -o gclib/GBase.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++11 -fno-strict-aliasing -fno-exceptions -fno-rtti -pthread -c gclib/GArgs.cpp -o gclib/GArgs.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++11 -fno-strict-aliasing -fno-exceptions -fno-rtti -pthread -c gclib/GStr.cpp -o gclib/GStr.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++11 -fno-strict-aliasing -fno-exceptions -fno-rtti -pthread -c gclib/GBam.cpp -o gclib/GBam.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++11 -fno-strict-aliasing -fno-exceptions -fno-rtti -pthread -c gclib/gdna.cpp -o gclib/gdna.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++11 -fno-strict-aliasing -fno-exceptions -fno-rtti -pthread -c gclib/codons.cpp -o gclib/codons.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++11 -fno-strict-aliasing -fno-exceptions -fno-rtti -pthread -c gclib/GFastaIndex.cpp -o gclib/GFastaIndex.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++11 -fno-strict-aliasing -fno-exceptions -fno-rtti -pthread -c gclib/GFaSeqGet.cpp -o gclib/GFaSeqGet.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++11 -fno-strict-aliasing -fno-exceptions -fno-rtti -pthread -c gclib/gff.cpp -o gclib/gff.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++11 -fno-strict-aliasing -fno-exceptions -fno-rtti -pthread -c gclib/GThreads.cpp -o gclib/GThreads.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++11 -fno-strict-aliasing -fno-exceptions -fno-rtti -pthread -c rlink.cpp -o rlink.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++11 -fno-strict-aliasing -fno-exceptions -fno-rtti -pthread -c tablemaker.cpp -o tablemaker.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++11 -fno-strict-aliasing -fno-exceptions -fno-rtti -pthread -c tmerge.cpp -o tmerge.o
g++ -g -O3 -DNDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++11 -fno-strict-aliasing -fno-exceptions -fno-rtti -pthread -c stringtie.cpp -o stringtie.o
g++ -g -L./samtools-0.1.18 -o stringtie gclib/GBase.o gclib/GArgs.o gclib/GStr.o gclib/GBam.o gclib/gdna.o gclib/codons.o gclib/GFastaIndex.o gclib/GFaSeqGet.o gclib/gff.o gclib/GThreads.o rlink.o tablemaker.o tmerge.o stringtie.o -pthread -lbam -lz
`

>

After installation, I tried to run the program on the test data. However, I got 'stringtie: command not found'.

**Comment by gpertea** [comment]
`./stringtie` should work, if you are trying to run it right after the `make` command,  or you can specify the full path to the directory where the binary was "installed" (i.e. copied -- Linux basics).
Beware that `make release` does not "install" the program, it just builds it. Proper installation usually means copying the `stringtie` binary in a directory which is in your shell's $PATH
