### ISSUE TITLE
manual issue: does hisat2 support on the fly passing of --ss and --exon?

### ISSUE THREAD

**Issue by roryk** [gpertea/stringtie#34]
In the Stringtie manual it says this:

```
Our recommended workflow includes the following steps:
for each RNA-Seq sample, map the reads to the genome with HISAT2 using the --dta option. It is highly recommended to use the reference annotation information when mapping the reads, which can be either embedded in the genome index (built with the -ss and --exon options, see HISAT2 manual), or provided separately at run time (-ss and --exon options of HISAT2). The SAM output of each HISAT2 must be sorted and converted to BAM using samtools as explained above.
```

but there doesn't seem to be an option to pass `--ss` and `--exon` in `hisat2` in either the manual or the help in version 2.0.1.

**Comment by gpertea** [comment]
You are correct (thank you for finding this),  it is actually the option ``--known-splicesite-infile`` for providing reference splice sites at hisat2 run time. I fixed this error in StringTie's manual.

**Comment by roryk** [comment]
Thanks Geo, do you know if providing that file at runtime blows up the memory requirements for running hisat2? The hisat2 manual says for the index building step:

```
If you use --snp, --ss, and/or --exon, hisat2-build will need about 200GB RAM for the human genome size as index building involves a graph construction. 
Otherwise, you will be able to build an index on your desktop with 8GB RAM.
```

Does that apply for passing it on the fly as well?

**Comment by gpertea** [comment]
No, that's the main advantage of using the reference annotation info (well, just the splice sites) at run time, with a linear index: the whole pipeline (including index building) can be run on a desktop/workstation with much lower memory requirements (e.g. a desktop with 8-16GB RAM) -- @infphilo should correct me if that's not the case..

**Comment by roryk** [comment]
Thanks Geo, that is super helpful. Sorry to pollute your repo with questions about hisat2.
