### ISSUE TITLE
running with point feature file

### ISSUE THREAD

**Issue by Amhaslam** [gpertea/stringtie#347]
string-tie is crashed while using point feature

Error: invalid call to GRefPtData::add() - cannot add feature with ref id 13893200 to ref data id 282328656!
[String-tie_point_feature.txt](https://github.com/gpertea/stringtie/files/7833315/String-tie_point_feature.txt)

**Comment by gpertea** [comment]
Thank you for reporting this. This issue was caused by a GList move operator bug, fixed via b498cdd.

**Comment by Amhaslam** [comment]
thank you for fixing it
