### ISSUE TITLE
Stringtie --merge

### ISSUE THREAD

**Issue by filicado** [gpertea/stringtie#35]
So I compared the new --merge option with cuffmerge on the same set of GTF files.
Here is what I get:

Hisat 2.0.0 + Stringtie + Stringtie --merge
parsed genome node DAGs: 20343
sequence regions: 804 (total length: 235278766)
genes: 19537
mRNAs: 52981
exons: 310477

Hisat 2.0.0 + Stringtie + Cuffmerge
parsed genome node DAGs: 18122
sequence regions: 815 (total length: 235906968)
genes: 17307
mRNAs: 61860
exons: 460638

Any idea what is going on? Aren't they supposed to be equivalent? is there a reason to assume that the output from Stringtie is superior?

**Comment by filicado** [comment]
note: this was without the --dta option in hisat2

**Comment by mpertea** [comment]
If you used annotation, Cufflinks will put in the merge file all genes from the annotation file, while StringTie will not add the annotated genes in the samples for which there is no gene expression in any of the samples. 
Other than that, Cufflinks and StringTie both rely on their own algorithms to merge transcripts, and they both have their own filtering methods to eliminate assembled transcripts that they believe to be spurious. At this time, we didn't do any testing to compare which one is superior.

**Comment by roryk** [comment]
Thanks @mpertea,

It would be sweet to have an option to include all of the genes from the annotation file. We use cuffmerge to generate a GTF file with the known assembly augmented with the newly assembled transcripts and having missing transcripts from the known assembly will lead to endless questions from people.

**Comment by mpertea** [comment]
Yes, I understand. I just talked to the other developers of StringTie and we will include all annotation in v1.2.2 (coming soon).

**Comment by filicado** [comment]
Thanks. By the way, great work guys Stringtie (& co) are awesome tools.
Prime examples of the awesomeness of the General Intellect !

**Comment by gpertea** [comment]
This was added in v1.2.2, if `-G` was used with `--merge`, all reference transcripts which did not "merge" with any assembled transcripts will be appended to the output file, with the original transcript and gene IDs. 
This also happens now in without `--merge`, if the `-e` option ("estimate only") was given.
Similarly, the `-A` gene abundance file should always list all the genes from the annotation file (with 0.0 cov/FPKM/TPM if not expressed).

**Comment by santataRU** [comment]
> This was added in v1.2.2, if `-G` was used with `--merge`, all reference transcripts which did not "merge" with any assembled transcripts will be appended to the output file, with the original transcript and gene IDs. This also happens now in without `--merge`, if the `-e` option ("estimate only") was given. Similarly, the `-A` gene abundance file should always list all the genes from the annotation file (with 0.0 cov/FPKM/TPM if not expressed).

@gpertea Thank you very much! I was wondering how to create a cell-type-specific GTF annotation, and now I understand that I should not include the '-G' option in the 'stringtie --merge' command.

**Comment by santataRU** [comment]
> > This was added in v1.2.2, if `-G` was used with `--merge`, all reference transcripts which did not "merge" with any assembled transcripts will be appended to the output file, with the original transcript and gene IDs. This also happens now in without `--merge`, if the `-e` option ("estimate only") was given. Similarly, the `-A` gene abundance file should always list all the genes from the annotation file (with 0.0 cov/FPKM/TPM if not expressed).
> 
> @gpertea Thank you very much! I was wondering how to create a cell-type-specific GTF annotation, and now I understand that I should not include the '-G' option in the 'stringtie --merge' command.

@gpertea Dear Gpertea, I just realized that without the '-G' option in the 'stringtie --merge' command, the output merged GTF file only contains "MSTRG.number" annotations instead of the standard gene names or gene symbols. I understand that "MSTRG.number" annotations are used for novel transcripts, but for known transcripts, is there an option to use gene names or gene symbols instead of the "MSTRG.number" annotations?
