### ISSUE TITLE
prepDE.py error: sample file not generated by -e option

### ISSUE THREAD

**Issue by zjj19910** [gpertea/stringtie#360]
I assembled the transcripts using stringtie and re-generated the quantification file using the merged gtf file.

> cat ../accessionlist | while read id; do echo "stringtie ../${alignment_dir}/${id}.sorted.bam -p 24 -Be -G stringtie_merged.gtf -o ${id}/${id}.stringtie_merged.gtf -A ${id}.gene_abund_merged.tab"; done |sh

But when I was preparing the count matrix using prepDE.py, an error occurred named

> prepDE.py -i sample_list.txt  -g gene_count_matrix.csv  -t transcript_count_matrix.csv

`Error: sample file ./HL-PBS-1/HL-PBS-1.stringtie_merged.gtf was not generated with -e option!`

while it was indeed generated from the -e option, how did this error occur?
Thank you!

**Comment by lgg84** [comment]
me to.Have you solved it yet?

**Comment by lihong01** [comment]
me to.have anyone solved this problem,I used -e before but I still reported this error when using prepDE.py later on.thanks
