### ISSUE TITLE
strand information is missed in GTF output

### ISSUE THREAD

**Issue by Jinjie-Duan** [gpertea/stringtie#40]
My output gtf from stringtie contains 3630 gene models with "." strand (i.e. unstranded). So I followed @mpertea previous suggestion and checked my BAM file. I found the reads aligned to these gene model do have strand information, either "+" or "-". but I still got the unstranded gene model. Could anyone shed the light on this?

As I understand, once a read aligns to genome, it must have strand information, either + or -. Are there any exceptions for it without strand?

**Comment by gpertea** [comment]
As I replied in the other thread, this was supposed to be fixed in the latest version. Could you please clarify if the StringTie version that produced these un-stranded transcripts for you was v1.2.2 ?

**Comment by Jinjie-Duan** [comment]
yes, I used the latest version v1.2.2.

**Comment by gpertea** [comment]
There may be some confusion there - in the BAM file, where did you look for "strand information"? 
The _alignment strand_ information (available in the _flag_ field of a SAM record) is not the same with the transcription strand information that StringTie needs (which is generally given by the spliced aligner by looking at the splice sites and made available in the XS tag in a SAM record). So for example a single-exon read may align to the reverse (-) strand of the genome, but this has nothing to do with the transcription strand, which is generally unknown for such un-spliced reads.

So are you saying that you found reads that have the XS tag with transcription strand info in the BAM file, but StringTie assembled them into transcripts without assigning them a strand (i.e. '.' in the strand column) ?

**Comment by Jinjie-Duan** [comment]
Thanks, Geo @gpertea . I misunderstood the strand issue at the beginning. now I got it. Thank you again for the prompt explanation.
