### ISSUE TITLE
Regions not covered by long read in --mix mode

### ISSUE THREAD

**Issue by ytomofuji** [gpertea/stringtie#425]
Thank you for creating this amazing tool!

I have a question about the --mix mode in stringtie2.
In Figure 1 of your paper (https://doi.org/10.1371/journal.pcbi.1009730), it was shown that --mix mode can assemble regions that are not covered by long reads but are covered by short reads. However,in the method section, it seems that long read data is used for constructing the splice graph. Are short read data also used in constructing the splice graph? Or are regions not included in the splice graph added during the assembly step?

I would greatly appreciate your help!

**Comment by mpertea** [comment]
Both short reads and long reads are used in the construction of the splice graph. The long reads, when present are used first to guide the path from source to sink in the graph.

**Comment by ytomofuji** [comment]
I understand! Thank you for your prompt response!
