### ISSUE TITLE
Error at GBitVec: index 21319082 out of bounds (size 21319082)

### ISSUE THREAD

**Issue by el42008** [gpertea/stringtie#44]
Hi, 
I am using the stringtie-1.2.2.Linux_x86_64 and for some of the bam files I am getting this error. Any ideas to solve it?

Cheers

Elena

**Comment by gpertea** [comment]
This seems to be the same with issue #45 (or rather the other way around), closing this as we'll follow up in #45 and the fix should be ready soon in v1.2.3.
