### ISSUE TITLE
problem when convert gtf to gff

### ISSUE THREAD

**Issue by pyhuang1** [gpertea/stringtie#49]
When I try to conver the .gtf to .gff, I encountered the following error message.
Could you help me to deal with this? Thank you.

cufflinks2gff3 strtie_merge.gtf > strtie_merge.gff
>>>>>
>>>>> Use of uninitialized value $score in join or string at /home/pyh/bin/maker/bin/cufflinks2gff3 line 94, <IN> line 221531.
>>>>> Use of uninitialized value $score in join or string at /home/pyh/bin/maker/bin/cufflinks2gff3 line 94, <IN> line 221532.
>>>>> Use of uninitialized value $score in join or string at /home/pyh/bin/maker/bin/cufflinks2gff3 line 94, <IN> line 221533.
>>>>> Use of uninitialized value $score in join or string at /home/pyh/bin/maker/bin/cufflinks2gff3 line 94, <IN> line 221534.
>>>>> Use of uninitialized value $score in join or string at /home/pyh/bin/maker/bin/cufflinks2gff3 line 94, <IN> line 221535.
>>>>> Use of uninitialized value $score in join or string at /home/pyh/bin/maker/bin/cufflinks2gff3 line 94, <IN> line 221536.

**Comment by gpertea** [comment]
I hope you can understand that, especially without any additional info, I have no idea why some script  which does not seem to be related to this project (and I've never heard of it until now),  failed for you.. I don't have time to look into that script to see why exactly it failed but I can guess that it looks for some specific GTF attributes which Cufflinks produces but StringTie doesn't. 
However there are other ways to convert a GTF file to GFF3 -- one option is gffread which you can get from here: http://ccb.jhu.edu/software/stringtie/gff.shtml#gffread
An equivalent command line for your case would be:
 ```
gffread -o strtie_merge.gff strtie_merge.gtf 
```
This will discard all the non-vital GTF attributes (use -F if you really need those).
