### ISSUE TITLE
Warning: invalid mapping found for read X (position=35326, mapped length=9)

### ISSUE THREAD

**Issue by dvanic** [gpertea/stringtie#51]
I'm using cufflinks-optimised STAR for mapping, followed by stringtie for novel transcript assembly. A significant number of reads are being flagged with the following warning:

`Warning: invalid mapping found for read X (position=35326, mapped length=9)
`

Why is this occurring, and how much will it affect the results of the assembly?

**Comment by gpertea** [comment]
This warning means that StringTie encountered a very suspicious mapping -- only 9 bases of the whole read were aligned to the genome.. the rest was probably soft-clipped (?). 
What kind of reads are these? Unless they are extremely short reads alignments such as these are most likely incorrect (I blame the aligner) and StringTie discards them. 
How much this affects the assembly depends on how many of the reads are "mapped" like this.. I'd suggest realigning the reads using HISAT2 and compare the alignment rate and/or assembly quality..

**Comment by dvanic** [comment]
Thanks for the prompt answer! These are 50bp PE reads, so perhaps 9 bp mapping (with the other 50 bp of the pair mapping as well) is sufficient for STAR to call the alignment as valid.  And this is affecting 25k of 91 mln reads in the library, so .03% - so probably less of a major issue than I though it was (I posted the question before I had the final stats for the library), but definitely something I prefer having clarified since it does happen, and does trigger a warning message.
