### ISSUE TITLE
Stringtie 1.2.3 fails to generate temporary files on Linux

### ISSUE THREAD

**Issue by lucventurini** [gpertea/stringtie#55]
I think the issue is related to the fact that it tries to generate temporary file names with an over-extended set of unicode characters. Eg a typical error would be:

"Error creating output file ./tmp.XX0EV1Su/(�W�.06_07_17:37:48.tmp"

And other temporary files are weird, like

(?郈?.06_07_17:38:13.tmp

I suppose that using Chinese hanzi is not necessary to have unique file names ...

**Comment by gpertea** [comment]
Wow the first time I am seeing this (and we're using almost exclusively Linux). I don't think it is a unicode issue (you're using an English UTF8  locale there I suppose?). 
What was the command line you used when you got that error? It looks like perhaps you did not use the ``-o`` option for the output file name (which should not be a problem but we might have a bug there for the ``stdout`` case..)

**Comment by lucventurini** [comment]
This is my command line:

```stringtie -p 32 -G all.transcripts.no_estimation.gtf -e ../../../Alignments/STAR/ALL/accepted_hits.all.picard.bam```

And this is the output of locale:

```$ locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=```

**Comment by gpertea** [comment]
Wow, this was a incredibly stupid bug in an old utility string function which caused garbage file names like that to be generated only when the output was left to stdout (i.e. no ``-o`` option was used). Very strange that on my Linux systems the program does not crashe because of this, and I could only see the garbage temp names if I used the ``--keeptmp`` option. But it was a terribly crass bug indeed..

**Comment by lucventurini** [comment]
The important thing is that it's solved! Thanks
