### ISSUE TITLE
stringtie -A option calculate different FPKMs with -o file

### ISSUE THREAD

**Issue by tsznxx** [gpertea/stringtie#56]
I ran stringtie with the following options:

`stringtie test.bam -G gencodev19.gtf -e -A test.txt -p 20 -o test.gtf`

The test.txt file contains FPKM and TPM at gene level. However, the test.gtf file also has FPKM and TPM attributes for each gene and transcript. The FPKMs in two files are different. I wonder why they are different. Which one should I use?

On the other hand, I want to get all the transcript level FPKM values. Is it OK to use the FPKMs in the test.gtf file?

Thanks

**Comment by gpertea** [comment]
Indeed the -A file should only show FPKM for genes, while the output GTF shows transcript level FPKM and TPM (which, for single-transcript genes, should be the same with gene level values).
There might have been some inconsistency for gene level FPKMs in the -A file in some cases, for older versions of StringTie -- please try the last version and let us know if such discrepancies still exist.

For transcript level values, the FPKMs from the output GTF should be used, obviously.

**Comment by mouyuemouri** [comment]
I ran into the same problem in StringTie v2.1.1 . 
The fpkm of parameter “-A” is different from the fpkm of parameter ”-o”。

**Comment by mouyuemouri** [comment]
> 实际上，-A文件应仅显示基因的FPKM，而输出GTF显示转录本水平FPKM和TPM（对于单转录本基因，应与基因水平值相同）。
> 在某些情况下，对于-A文件中的基因级别FPKM可能存在一些不一致之处，对于StringTie的较旧版本-请尝试使用最新版本，并让我们知道是否仍然存在这种差异。
> 
> 对于成绩单级别值，显然应该使用来自输出GTF的FPKM。



> Indeed the -A file should only show FPKM for genes, while the output GTF shows transcript level FPKM and TPM (which, for single-transcript genes, should be the same with gene level values).
> There might have been some inconsistency for gene level FPKMs in the -A file in some cases, for older versions of StringTie -- please try the last version and let us know if such discrepancies still exist.
> 
> For transcript level values, the FPKMs from the output GTF should be used, obviously.

I ran into the same problem in StringTie v2.1.1 .
The fpkm of parameter “-A” is different from the fpkm of parameter ”-o”。
