### ISSUE TITLE
stranded libraries

### ISSUE THREAD

**Issue by damiankao** [gpertea/stringtie#59]
I am using Hisat2/Stringtie to assemble a set of reference annotations from multiple libraries. I am following the procedure laid out on the Stringtie website. 

Some of the libraries were created with stranded prep chemistry. I mapped those libraries with hisat2 using the --rna-strandness FR along with the --dta flag.

Will Stringtie take into account the libraries with strand information during the merge step?

**Comment by gpertea** [comment]
StringTie does not get (hence does not use) this library-level information *directly* -- though this information should be reflected in the spliced-alignment strand info of the alignments generated by HISAT2 --dta (the "XS"  tag) which of course StringTie uses when it assembles the read alignments into transfrags.
