### ISSUE TITLE
stringtie --merge error

### ISSUE THREAD

**Issue by soumyarao86** [gpertea/stringtie#60]
Hi,
I mapped RNA-seq reads of a fungus on it's de novo assembled genome through Hisat2. The sorted.bam files of individual samples were assembled through stringtie to create .gtf files. I tried to merge these using --merge, but got the following error:
$stringtie --merge -o test.gtf gtf_list
 Error: attempt to remove reference to null GffNames object!
Aborted

I am running it in the same directory with input .gtf files.
$head gtf_list
sample1.gtf
sample2.gtf
sample3.gtf
I am not sure what could be the problem with command or input files.

**Comment by gpertea** [comment]
That's an error I haven't encountered before, I'd like to look into it. How many input .gtf files you have in gtf_list? Do you get the error even with a subset of those files - say, the first 3 ?
Could you please make these files (or a minimum subset of them which trigger that error) available somewhere for me to download?

**Comment by soumyarao86** [comment]
I used super reads for 3 samples and  ran hisat2 followed by stringtie with a reference annotation.
Should I try using the regular paired end and unpaired reads instead of super reads?
I tried attaching some lines of the .gtf files here but gtf file format is not supported. Please find the gtf_list attached here.

The gtf files look like this:
# stringtie /home/lgpa/Documents/soumya/genome_guided_assembly/hisat2/fungus_reads_mapped/cz_super_hisat_sorted.bam.bam -o hisat_cz_super.gtf -p 20 -l cz_super_hisat_str -m 150
# StringTie version 1.2.3
scaffold1_21.4  StringTie       transcript      62382   62625   1000    .       .       gene_id "cz_super_hisat_str.1"; transcript_id "cz_super_hisat_str.1.1"; cov "4.508197"; FPKM "3.746112"; TPM "4.093173";
scaffold1_21.4  StringTie       exon    62382   62625   1000    .       .       gene_id "cz_super_hisat_str.1"; transcript_id "cz_super_hisat_str.1.1"; exon_number "1"; cov "4.508197";
scaffold1_21.4  StringTie       transcript      67276   67428   1000    .       .       gene_id "cz_super_hisat_str.2"; transcript_id "cz_super_hisat_str.2.1"; cov "2.614379"; FPKM "2.172433"; TPM "2.373699";
scaffold1_21.4  StringTie       exon    67276   67428   1000    .       .       gene_id "cz_super_hisat_str.2"; transcript_id "cz_super_hisat_str.2.1"; exon_number "1"; cov "2.614379";
scaffold1_21.4  StringTie       transcript      53566   54206   1000    +       .       gene_id "cz_super_hisat_str.3"; transcript_id "cz_super_hisat_str.3.1"; cov "3.221254"; FPKM "2.676720"; TPM "2.924705";
scaffold1_21.4  StringTie       exon    53566   53921   1000    +       .       gene_id "cz_super_hisat_str.3"; transcript_id "cz_super_hisat_str.3.1"; exon_number "1"; cov "3.867978";
scaffold1_21.4  StringTie       exon    53989   54206   1000    +       .       gene_id "cz_super_hisat_str.3"; transcript_id "cz_super_hisat_str.3.1"; exon_number "2"; cov "2.165138";
scaffold1_21.4  StringTie       transcript      52777   53460   1000    +       .       gene_id "cz_super_hisat_str.4"; transcript_id "cz_super_hisat_str.4.1"; cov "3.156549"; FPKM "2.622952"; TPM "2.865957";

**Comment by soumyarao86** [comment]
[gtf_list.txt](https://github.com/gpertea/stringtie/files/361761/gtf_list.txt)

**Comment by soumyarao86** [comment]
Sorry for the unusually large font of the commented lines of the gtf lines.
The other file looks similar.
# stringtie /home/lgpa/Documents/soumya/genome_guided_assembly/hisat2/fungus_reads_mapped/apr_super_hisat_sorted.bam -o hisat_apr_super.gtf -p 20 -l apr_super_hisat_str -m 150
# StringTie version 1.2.3
scaffold1_21.4  StringTie       transcript      56932   58024   1000    -       .       gene_id "apr_super_hisat_str.1"; transcript_id "apr_super_hisat_str.1.1"; cov "7.734164"; FPKM "1.514939"; TPM "2.806423";
scaffold1_21.4  StringTie       exon    56932   57206   1000    -       .       gene_id "apr_super_hisat_str.1"; transcript_id "apr_super_hisat_str.1.1"; exon_number "1"; cov "9.185681";
scaffold1_21.4  StringTie       exon    57262   58024   1000    -       .       gene_id "apr_super_hisat_str.1"; transcript_id "apr_super_hisat_str.1.1"; exon_number "2"; cov "7.211009";
scaffold1_21.4  StringTie       transcript      52309   54429   1000    +       .       gene_id "apr_super_hisat_str.2"; transcript_id "apr_super_hisat_str.2.1"; cov "8.506263"; FPKM "1.666175"; TPM "3.086588";
scaffold1_21.4  StringTie       exon    52309   52667   1000    +       .       gene_id "apr_super_hisat_str.2"; transcript_id "apr_super_hisat_str.2.1"; exon_number "1"; cov "9.011699";
scaffold1_21.4  StringTie       exon    52730   53104   1000    +       .       gene_id "apr_super_hisat_str.2"; transcript_id "apr_super_hisat_str.2.1"; exon_number "2"; cov "8.507733";
scaffold1_21.4  StringTie       exon    53163   53921   1000    +       .       gene_id "apr_super_hisat_str.2"; transcript_id "apr_super_hisat_str.2.1"; exon_number "3"; cov "9.152042";
scaffold1_21.4  StringTie       exon    53989   54429   1000    +       .       gene_id "apr_super_hisat_str.2"; transcript_id "apr_super_hisat_str.2.1"; exon_number "4"; cov "6.982111";

**Comment by gpertea** [comment]
Sorry, pasting text lines here is not what I had in mind, I don't think it's a good way of providing that info to me. Could you please make a zip or a tar.gz archive with the 3 gtf files and e-mail it to me at geo.pertea@gmail.com (or place it on Google drive and share the link with me) ?
Using only the super-reads might not be as accurate as providing actual paired reads alignments, as some of the read pairing information might be lost in the process -- we mostly tested and optimized StringTie for paired reads alignments. But right now let's get this working on the super-read alignments you have.

**Comment by soumyarao86** [comment]
I'm Sorry!
I ran hisat2 with PE reads and superreads with -U option. The .bam file generated in this step was input for stringtie for each sample. 
I will mail you shortly the .gtf files that I am trying to merge (with 1st 100 lines).

**Comment by gpertea** [comment]
There was a bug in one of the auxiliary classes that was causing that error and I just fixed it. Please download the latest Linux binary (or the source package) with the fix:

http://ccb.jhu.edu/software/stringtie/dl/stringtie-1.2.3b.Linux_x86_64.tar.gz
http://ccb.jhu.edu/software/stringtie/dl/stringtie-1.2.3b.tar.gz

**Comment by soumyarao86** [comment]
Okay.
I will try it and let you know.
Thanks.

**Comment by soumyarao86** [comment]
Hi
I finally got it working.
Thank you.
