### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by wangzhennan14** [gpertea/stringtie#64]
Hi,
   When I use stringtie to deal with my data,there is an error: WARNING: no reference transcripts found for genomic sequence "Contig119072"! (mismatched reference names?)
   What does that mean?Thank you!

**Comment by mpertea** [comment]
This is not an error, just an warning to make that the user checked that the input files are all in the same format (e.g. same contig names in both the alignment and annotation files). Are there any genes annotated on Contig119072? If there are then there is a problem with the format of the files I mentioned above. If there are not then you can just ignore this warning.
