### ISSUE TITLE
prepDE.py error (StringTie outputs negative coverage values?)

### ISSUE THREAD

**Issue by nongbaoting** [gpertea/stringtie#69]
I have run stringtie with -e -B successfully and i can use ballgown to generate FPKM matrix successfully, but when I used prepDE.py to genetate gene count matrix , it just get wrong

wrong massenge:
<code>
$python prepDE.py -i ballgown  -p Sympk_
<br>
0 Sympk_1D0
Traceback (most recent call last):
  File "prepDE.py", line 158, in <module>
    coverage=float(RE_COVERAGE.search(v[len(v)-1]).group(1))
AttributeError: 'NoneType' object has no attribute 'group'
</code>
and the derectory under ballgown is like so:
<code>
$ ls -l ballgown/
drwxrwxr-x 2 melody melody 4096 Sep 17 18:07 Sympk_1D0
drwxrwxr-x 2 melody melody 4096 Sep 17 17:55 Sympk_1D3_Dox_1
drwxrwxr-x 2 melody melody 4096 Sep 17 17:56 Sympk_1D3_Dox_2
drwxrwxr-x 2 melody melody 4096 Sep 17 17:56 Sympk_1D6_Dox_1
drwxrwxr-x 2 melody melody 4096 Sep 17 17:56 Sympk_1D6_Dox_2
</code>

I have tried to use many options but always get the same error! could any one help me

**Comment by tsznxx** [comment]
I tried to do it in an alternative way. Change the code to split and index, instead of regexprs search. Hope it helps.
<pre><code>
               if v[2]=="transcript":
                    **anno = v[8].split('"')**
                    if transcript_len>0:
##                        transcriptList.append((g_id, t_id, int(ceil(coverage*transcript_len/read_len))))
                        t_dict.setdefault(t_id, {})
                        t_dict[t_id].setdefault(s, int(ceil(coverage*transcript_len/read_len)))
                        **t_id=anno[3] # RE_TRANSCRIPT_ID.search(v[len(v)-1]).group(1)**
                        **g_id=anno[1] # RE_GENE_ID.search(v[len(v)-1]).group(1)**
                    coverage=float(anno[7]) # RE_COVERAGE.search(v[len(v)-1]).group(1))
</code></pre>

**Comment by zpliu** [comment]
I have encounter the same problem as nongbaoting, and I modified the prepDE.py following your suggestons. @tsznxx @nongbaoting 
> I tried to do it in an alternative way. Change the code to split and index, instead of regexprs search. Hope it helps.

Glad to see I can get count matrix results now. But another problem appears if I run :

```
$python prepDE.py -i ballgown
0 CTR1
1 CTR2
Traceback (most recent call last):
  File "prepDE.py", line 177, in <module>
    geneDict[geneIDs[i]][s]+=v[s]
KeyError: 'CTR2'

```

I have 5 samples in the ballgown folder, it seemed that only the first sample is successful. 

```
$ ls ballgown
CTR1  CTR2  STZ1  STZ2  STZ3
```

I tried to put each sample into an individual folder, like this
```
ballgown_CTR1/CTR1
ballgown_CTR2/CTR2
ballgown_STZ1/STZ1
ballgown_STZ2/STZ2
ballgown_STZ3/STZ3
```

then I run prepDE.py for each folder, it worked. But could you help to fix this?

**Comment by tsznxx** [comment]
Hi,

Since  line 175-176 has set default values to geneDict object, the key
error should be from v[s]. Then go back to line 153-156, where the s is
initialized when the transcript length >0.

On the other hand, according to the code, the gene names are initiated from
the first gtf file it encounters. It is very likely that the 1st GTF file
doesn't contain CTR2 gene or its transcript length=0.

I hope this could help. have a good week!


Sincerely,
Yunfei Wang
Department of Bioinformatics & Computational Biology
The University of Texas MD Anderson Cancer Center

**Comment by ertelad** [comment]
This appears to be an issue with stringtie 1.3.0, not prepDE.py.  I've encountered the issue, getting the error 'NoneType' object has no attribute 'group' when running prepDE.py.  This only occurs with the new stringtie 1.3.0, that for some genes generates small negative values for cov, FPKM, and TPM in the .gtf file.   prepDE.py can't handle the negative values, but works fine on .gtf results from stringtie 1.2.4.

**Comment by tsznxx** [comment]
Please stick to the latest version of stringtie. I encountered some problem
with early version (1.2.3), which reports zero FPKM values in one sample
when there are many reads in the bam file. It did report non-zeros in other
samples.

Sincerely,
Yunfei Wang
Department of Bioinformatics & Computational Biology
The University of Texas MD Anderson Cancer Center

**Comment by tsznxx** [comment]
You are right. I didn't notice this. Then a better solution would be
setting coverage to zero when it encounters negative values.

162                     try:
163                         coverage =
float(RE_COVERAGE.search(v[len(v)-1]).group(1))
164                     except:
165                         coverage = 0.0


Sincerely,
Yunfei Wang
Department of Bioinformatics & Computational Biology
The University of Texas MD Anderson Cancer Center

**Comment by eudoraleer** [comment]
Can you check if your GTF file has "chr" prefix? Also, does your reference annotation file contain "chr" prefix?

**Comment by gpertea** [comment]
Thank you everyone for these very useful observations. I haven't had time to look into the prepDE.py script issues yet but I'll take your suggestions here into consideration for the next version. Right now we're working to address the issue of small negative coverage values in StringTie v1.3.0 which was reported in this thread -- we weren't aware of it before reading it here, thank you for pointing this out!

**Comment by gpertea** [comment]
This bug (small negative coverage values) should be fixed in version 1.3.1 which has just been released.

**Comment by JudithMarsman** [comment]
I have incorporated the alterations of the prepDE.py script listed by @tsznxx and it runs fine if I run it on individual sample directories (e.g. dir1/S1/S1.gtf), but not when I put all my samples in one directory:

ballgown/S1/S1.gtf
ballgown/S2/S2.gtf
ballgown/S3/S3.gtf
etc.

This is the code I use:

python prepDE.py -i ballgown 

Which outputs the following:

0 S1
1 S2
Traceback (most recent call last):
  File "prepDE3.py", line 181, in <module>
    geneDict[geneIDs[i]][s]+=v[s]
KeyError: 'S2'

I can thus get a count matrix for each individual sample, but I was wondering if there is a way to create a count matrix that have all samples included?

**Comment by gpertea** [comment]
I want to take a closer look at what that script is doing with your data if possible -- it would be very helpful if you could pack up those 3 GTF files and e-mail them to me (gpertea@jhu.edu) for debugging, please..

As Yunfei noted earlier, this might be related to the fact that prepDE expects all transcripts and genes to be defined in the first sample GTF encountered. So, barring any other bugs in StringTie during the abundance estimation step (-e option), the user should always make sure that those GTF files are generated with the same command line options (except the sample BAM file of course), in particular the **-G** parameter is crucial to be the same (i.e. to use the exact same *merged.gtf* as reference for the abundance estimation of every sample).

**Comment by tsznxx** [comment]
Hi JudithMarsman,

My experience is if you have multiple samples, for example, 5 BAM files in
WORKDIR folder.
1. run stringtie with -o sampleID.gtf -b sampleID_bg parameters for each
sample.
2. mv the sampleID.gtf to sampleID_bg folder.
3. run prepDE.py in the WORKDIR folder. It searches all the subfolders
inside WORKDIR folder to see if they contain the ballgown files, and then
calculate the counts using the .gtf file inside.

Hope this helps.

tsznxx

Sincerely,
Yunfei Wang
Department of Bioinformatics & Computational Biology
The University of Texas MD Anderson Cancer Center

**Comment by RatneshSingh** [comment]
I am having similar problems with multiple gtf files I generated using stringtie -e and merged GTF as reference. I noticed that in each sample's gtf has different gene_id and transcript_id for a locus.  Even though the ids starts with STRG, same name (eg. STRG.6.1) represents different region on the chromosome in different samples. The prepDE.py is using these gene_id and transcript_id to find coverage in each sample. Since these ids are not comparable across samples, resulting matrix will be incorrect. The script should be using reference_id and ref_gene_id to combine the coverage across the samples since those are derived from provided reference GTF during the stringtie run.

**Comment by golrokh51** [comment]
> I have encountered the same problem as nongbaoting, and I modified the prepDE.py following your suggestion. @tsznxx @nongbaoting
> 
> > I tried to do it in an alternative way. Change the code to split and index, instead of regexprs search. Hope it helps.
> 
> Glad to see I can get count matrix results now. But another problem appears if I run :
> 
> ```
> $python prepDE.py -i ballgown
> 0 CTR1
> 1 CTR2
> Traceback (most recent call last):
>   File "prepDE.py", line 177, in <module>
>     geneDict[geneIDs[i]][s]+=v[s]
> KeyError: 'CTR2'
> ```
> 
> I have 5 samples in the ballgown folder, it seemed that only the first sample is successful.
> 
> ```
> $ ls ballgown
> CTR1  CTR2  STZ1  STZ2  STZ3
> ```
> 
> I tried to put each sample into an individual folder, like this
> 
> ```
> ballgown_CTR1/CTR1
> ballgown_CTR2/CTR2
> ballgown_STZ1/STZ1
> ballgown_STZ2/STZ2
> ballgown_STZ3/STZ3
> ```
> 
> then I run prepDE.py for each folder, it worked. But could you help to fix this?

My error solved when I gave the list of files to read -i=inputFiles.txt with the following structure:
CTR2<space><your file path>
STZ1<space><your file path>
....

**Comment by NjauWly** [comment]
This problem happens again in version 2.0. I ran the stringtie program with -e option. But the gtf outcome exists new predicted transcript.
