### ISSUE TITLE
2-pass alignment guidelines

### ISSUE THREAD

**Issue by tantrev** [gpertea/stringtie#72]
In the default Stringtie pipeline with Hisat2, it utilizes a 1-pass alignment.  Other transcript discovery methods that utilize STAR have shown improved accuracy with a 2-pass workflow.  Is there any reason to believe a 2-pass alignment (from the output of Stringtie, back into Hisat2) would help Stringtie's accuracy?  Just thought I would ask in light of Stringtie's new abundance estimation method.

**Comment by gpertea** [comment]
I don't think it would help, novel junction discovery is already performed by Hisat2 "on the fly" in the first run, and StringTie does not add any new junctions by itself, and I suspect the exon coverage would not even change (not significantly anyway) with a 2nd alignment pass.

**Comment by tantrev** [comment]
Thank you!  For what it's worth, I came across this [article](http://www.biorxiv.org/content/biorxiv/early/2015/08/11/019067.full.pdf) which agrees exactly.  I guess it can make some difference for intron discovery, but makes virtually no difference for exons.
