### ISSUE TITLE
Stringtie crash due to double free or corruption

### ISSUE THREAD

**Issue by clb1000** [gpertea/stringtie#77]
On a linux system with a clone of the current repository:

stringtie all_joined_and_not_joined_sorted.bam -o all_joined_and_not_joined_stringtie.gtf -p 10 -t -f 0.01 -c 2.0 -m 100 -a 1 -g 500

Error at GBitVec: index 12869 out of bounds (size 12869)
*** Error in `/usr/local/src/stringtie/stringtie': double free or corruption (!prev): 0x0000000001b6e410

**Comment by gpertea** [comment]
We were hoping this kind of error had been fixed a while ago. But if it happens with the current master branch.. we'd really want to take another look.
Is there any chance you could share the bundle/region which triggered that error with us? If you run with -v and -p 1 ( or without -p option at all), you should get the last bundle coordinates at stderr when it crashes.. It would be great if you can extract the alignments from that region in a separate BAM file and make it available to us for debugging.

**Comment by clb1000** [comment]
I want to try a couple things to make sure that the problem isn't due to my particular BAM files. I need a week or so to evaluate. I'll let you know the outcome.

**Comment by gpertea** [comment]
This could be (or not) related to the bug that was more "expressed" in the v1.3.1 release, which was hopefully squashed today -- so please it would be great if you can only use the new 1.3.1c version of StringTie for further testing&bug reporting, instead of any of the previous versions..
(download the last version from: http://ccb.jhu.edu/software/stringtie/#install)

**Comment by clb1000** [comment]
Hi Geo,

     After remaking my BAM files to make sure that they were formatted 
correctly, I downloaded StringTie version 1.3.1c from Github and reran 
things. Unfortunately, I am not able to get very far on any chromosome 
before StringTie fails. Most of the time it is the GBitVec error, but 
also sometimes by a KILL signal from the operating system for some 
reason that I am not able to figure out.

     Here is the command line that I am currently using: stringtie 
debug.bam -o debug.gtf -p 1 -v -t -f 0.01 -c 2.0 -m 100 -a 1 -g 200

     I created debug.bam from a stringtie bundle that caused a GBitVec 
error.

     You can download debug.bam from http://ism.ucsd.edu/~cbarrett/debug.bam

     Let me know if I can provide any other information.

                     Regards,
                     Christian

**Comment by gpertea** [comment]
Christian, indeed it looks like there is something wrong going on with our code when run on your data. Thank you for the debug.bam file, I was able to reproduce the error on our side so we have all we need in order to start investigating this.

**Comment by mpertea** [comment]
Christian, I looked at the bam file you sent, and to me it's no surprise that StringTie crashes. The alignments cover the entire first 30 million bases in chromosome X! I am curious how the alignments in this file were generated. We haven't imagined transcription occurring non-stop for such a large area so this big task is going to be a challenge for StringTie and it might require a different handling than our default approach. For sure it will require a lot of time for us to address. It would be useful to know the cases when this could happen.
