### ISSUE TITLE
Stringtie prepDE.py - gtf file error

### ISSUE THREAD

**Issue by akulan1** [gpertea/stringtie#88]
Hi,
The gtf file is in the directory but I am getting the following error when I run prepDE.py:

Error: no GTF files found under ./160315_YOSHI_C8E8CANXX.8.11987012_2581_MDD_Stringtie !

Here is the directory listing:
-rw-r----- 1 akulan ACSg 207M Jan  5 16:06 160315_YOSHI_C8E8CANXX.8.11987012_2581_MDD_Stringtie.gtf
t_data.ctab
 e_data.ctab
 e2t.ctab
 i_data.ctab
 i2t.ctab

./prepDE.py -i 160315_YOSHI_C8E8CANXX.8.11987012_2581_MDD_Stringtie

Thanks in advance!

**Comment by gpertea** [comment]
Please pay attention to the description of the directory tree structure expected by the script. I thought it was explained on the web page.
The default is
```
working_directory
     |
     +-- ballgown
            |
            +--sample1dir/sample1.gtf
            |
            +--sample2dir/sample2.gtf
            |
             ...
``` 
The gtf files are expected in the 2nd level sub-directories (sample1dir, sample2dir etc.) which correspond to your 160315_YOSHI_... directory I guess. Indeed, the script does not care if you have any gtf files directly under the 1st level sub-directory (``ballgown`` in this example).
So it should be as easy as creating a ``ballgown`` sub-directory and then moving that 160315_YOSHI_.. directory (and others like it, I guess you're using multiple samples) under that, and then run prepDE.py in the same directory which parents ``ballgown`` (of course you can call that 1st level sub-directory something else and pass it to the -i option, ``ballgown`` is just the default).
