### ISSUE TITLE
Stringtie removing gene id on some lines

### ISSUE THREAD

**Issue by Michael-w-s** [gpertea/stringtie#89]
I am trying to do differential expression analysis using stringtie followed by prepDE to EdgeR but stringtie -eB output does not have the gene_id field in all lines, which causes prepDE to fail. The error I am getting from prepDE is:

Traceback (most recent call last):
  File "/data/kelley/projects/bear_RNA/prepDE.py", line 72, in <module>
    g_id=RE_GENE_ID.search(v[len(v)-1]).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

I know that some other users had similar problems when their reference lacked the gene_id attribute but I checked my reference and the problem does not exist there. When I check the output of stringtie -eB I find around 650 lines with this error (no gene_id attribute).

**Comment by zhenyisong** [comment]
I met the same problem with  -e -B parameters (StringTie v1.3.2-pre).

**Comment by gpertea** [comment]
It's not clear to me if this disappearing gene_id bug is in the output of `stringtie -e` or it's inherited from the `stringtie --merge` step. I tinkered a bit with the code, it looks like *gene_id* should be written as long as the input has a *gene_id* assigned.. 

I tried to fix this and a few other issues and tentatively released v1.3.2. Could you please give it a try and report back if this missing gene_id bug is still there? You might have to re-run the `--merge` step as well, unless you're certain that all those transcripts have *gene_id* and it's just the `-e` steps that somehow drops them. Thanks!

Linux version here:
http://ccb.jhu.edu/software/stringtie/dl/stringtie-1.3.2.Linux_x86_64.tar.gz
(source: http://ccb.jhu.edu/software/stringtie/dl/stringtie-1.3.2.tar.gz)

**Comment by gpertea** [comment]
Closing this - lack of further feedback, I assume it's fixed in newer releases.
