### ISSUE TITLE
preDE.py - discrepancy between gene & transcript output matrices

### ISSUE THREAD

**Issue by rhugh-white** [gpertea/stringtie#94]
When using the preDE.py script, there are genes with multiple isoforms present in the transcript_count_matrix.csv file which do not have a gene level count in gene_count_matrix.csv (i.e. are completely absent from this file).

Any ideas as to possible reasons?

**Comment by gpertea** [comment]
Could it be that the gene_id is not consistently defined for all those isoforms? They should have the same gene_id. A concrete minimal example exposing the issue would make it easier to investigate this problem.
