### ISSUE TITLE
Issue in make release MacOS 10.12.2

### ISSUE THREAD

**Issue by sytrobertson** [gpertea/stringtie#96]
Hello,

I'm having problems with installation - I follow all the steps but when I get to the make release step, my command line outputs a bunch of "[-Wunused-funtion]" and "implicit conversion of NULL constant to uint32 (aka unsigned int') [-Wnull-conversion]" errors, and then when I try to run stringtie (I try from both the stringtie folder and its parent folder) it says "command not found." Does this have something to do with my computer, which is a Mac 10.12.2? Thanks!

**Comment by gpertea** [comment]
Admittedly I haven't tested the build on MacOS, which seems to fail based on your report here. 

Is there any problem using the pre-built binary for OS X that we provided for download on the website?
Until I get my hands on an updated OS X system to fix the build issue..

Could you copy&paste here the actual build output you get in your terminal there? (just for `make release` in the main stringtie directory). You mentioned some error messages that look more like warnings, but there must be an actual build error there I'd like to see.

**Comment by sytrobertson** [comment]
The binary for OS X doesn't work for me either, it doesn't even run make release saying "make: *** no rule to make target release'. Stop."

Here's the build output: $ make release
cd ./samtools-0.1.18 && make lib
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bgzf.c -o bgzf.o
bgzf.c:44:1: warning: unused function 'kh_clear_cache' [-Wunused-function]
KHASH_MAP_INIT_INT64(cache, cache_t)
^
./khash.h:510:2: note: expanded from macro 'KHASH_MAP_INIT_INT64'
        KHASH_INIT(name, khint64_t, khval_t, 1, kh_int64_hash_func, kh_i...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:179:13: note: expanded from macro 'KHASH_INIT2'
        SCOPE void kh_clear_##name(kh_##name##_t *h...
                   ^
<scratch space>:53:1: note: expanded from here
kh_clear_cache
^
1 warning generated.
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. kstring.c -o kstring.o
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_aux.c -o bam_aux.o
bam_aux.c:5:1: warning: unused function 'kh_clear_s' [-Wunused-function]
KHASH_MAP_INIT_STR(s, int)
^
./khash.h:526:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:179:13: note: expanded from macro 'KHASH_INIT2'
        SCOPE void kh_clear_##name(kh_##name##_t *h...
                   ^
<scratch space>:20:1: note: expanded from here
kh_clear_s
^
bam_aux.c:5:1: warning: unused function 'kh_del_s' [-Wunused-function]
./khash.h:526:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:298:13: note: expanded from macro 'KHASH_INIT2'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x...
                   ^
<scratch space>:34:1: note: expanded from here
kh_del_s
^
bam_aux.c:6:1: warning: unused function 'kh_init_r2l' [-Wunused-function]
KHASH_MAP_INIT_STR(r2l, str_p)
^
./khash.h:526:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:168:23: note: expanded from macro 'KHASH_INIT2'
        SCOPE kh_##name##_t *kh_init_##name() ...
                             ^
<scratch space>:41:1: note: expanded from here
kh_init_r2l
^
bam_aux.c:6:1: warning: unused function 'kh_destroy_r2l' [-Wunused-function]
./khash.h:526:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:171:13: note: expanded from macro 'KHASH_INIT2'
        SCOPE void kh_destroy_##name(kh_##name##_t *h...
                   ^
<scratch space>:46:1: note: expanded from here
kh_destroy_r2l
^
bam_aux.c:6:1: warning: unused function 'kh_clear_r2l' [-Wunused-function]
./khash.h:526:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:179:13: note: expanded from macro 'KHASH_INIT2'
        SCOPE void kh_clear_##name(kh_##name##_t *h...
                   ^
<scratch space>:49:1: note: expanded from here
kh_clear_r2l
^
bam_aux.c:6:1: warning: unused function 'kh_get_r2l' [-Wunused-function]
./khash.h:526:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:186:16: note: expanded from macro 'KHASH_INIT2'
        SCOPE khint_t kh_get_##name(const kh_##name##_t *h, khkey_t key...
                      ^
<scratch space>:52:1: note: expanded from here
kh_get_r2l
^
bam_aux.c:6:1: warning: unused function 'kh_put_r2l' [-Wunused-function]
./khash.h:526:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:260:16: note: expanded from macro 'KHASH_INIT2'
        SCOPE khint_t kh_put_##name(kh_##name##_t *h, khkey_t key, int *ret) \
                      ^
<scratch space>:58:1: note: expanded from here
kh_put_r2l
^
bam_aux.c:6:1: warning: unused function 'kh_del_r2l' [-Wunused-function]
./khash.h:526:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:298:13: note: expanded from macro 'KHASH_INIT2'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x...
                   ^
<scratch space>:63:1: note: expanded from here
kh_del_r2l
^
8 warnings generated.
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam.c -o bam.o
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_import.c -o bam_import.o
bam_import.c:18:1: warning: unused function 'kh_clear_ref' [-Wunused-function]
KHASH_MAP_INIT_STR(ref, uint64_t)
^
./khash.h:526:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:179:13: note: expanded from macro 'KHASH_INIT2'
        SCOPE void kh_clear_##name(kh_##name##_t *h...
                   ^
<scratch space>:20:1: note: expanded from here
kh_clear_ref
^
bam_import.c:18:1: warning: unused function 'kh_get_ref' [-Wunused-function]
./khash.h:526:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:186:16: note: expanded from macro 'KHASH_INIT2'
        SCOPE khint_t kh_get_##name(const kh_##name##_t *h, khkey_t key...
                      ^
<scratch space>:23:1: note: expanded from here
kh_get_ref
^
bam_import.c:18:1: warning: unused function 'kh_del_ref' [-Wunused-function]
./khash.h:526:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:298:13: note: expanded from macro 'KHASH_INIT2'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x...
                   ^
<scratch space>:34:1: note: expanded from here
kh_del_ref
^
3 warnings generated.
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. sam.c -o sam.o
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_index.c -o bam_index.o
bam_index.c:64:1: warning: unused function 'kh_clear_i' [-Wunused-function]
KHASH_MAP_INIT_INT(i, bam_binlist_t)
^
./khash.h:495:2: note: expanded from macro 'KHASH_MAP_INIT_INT'
        KHASH_INIT(name, khint32_t, khval_t, 1, kh_int_hash_func, kh_int...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:179:13: note: expanded from macro 'KHASH_INIT2'
        SCOPE void kh_clear_##name(kh_##name##_t *h...
                   ^
<scratch space>:34:1: note: expanded from here
kh_clear_i
^
bam_index.c:64:1: warning: unused function 'kh_del_i' [-Wunused-function]
./khash.h:495:2: note: expanded from macro 'KHASH_MAP_INIT_INT'
        KHASH_INIT(name, khint32_t, khval_t, 1, kh_int_hash_func, kh_int...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:298:13: note: expanded from macro 'KHASH_INIT2'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x...
                   ^
<scratch space>:48:1: note: expanded from here
kh_del_i
^
2 warnings generated.
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_pileup.c -o bam_pileup.o
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_lpileup.c -o bam_lpileup.o
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_md.c -o bam_md.o
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. razf.c -o razf.o
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. faidx.c -o faidx.o
faidx.c:14:1: warning: unused function 'kh_clear_s' [-Wunused-function]
KHASH_MAP_INIT_STR(s, faidx1_t)
^
./khash.h:526:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:179:13: note: expanded from macro 'KHASH_INIT2'
        SCOPE void kh_clear_##name(kh_##name##_t *h...
                   ^
<scratch space>:328:1: note: expanded from here
kh_clear_s
^
faidx.c:14:1: warning: unused function 'kh_del_s' [-Wunused-function]
./khash.h:526:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:298:13: note: expanded from macro 'KHASH_INIT2'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x...
                   ^
<scratch space>:342:1: note: expanded from here
kh_del_s
^
2 warnings generated.
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bedidx.c -o bedidx.o
bedidx.c:24:1: warning: unused function 'kh_clear_reg' [-Wunused-function]
KHASH_MAP_INIT_STR(reg, bed_reglist_t)
^
./khash.h:526:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:179:13: note: expanded from macro 'KHASH_INIT2'
        SCOPE void kh_clear_##name(kh_##name##_t *h...
                   ^
<scratch space>:34:1: note: expanded from here
kh_clear_reg
^
bedidx.c:24:1: warning: unused function 'kh_del_reg' [-Wunused-function]
./khash.h:526:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:298:13: note: expanded from macro 'KHASH_INIT2'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x...
                   ^
<scratch space>:48:1: note: expanded from here
kh_del_reg
^
2 warnings generated.
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_sort.c -o bam_sort.o
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. sam_header.c -o sam_header.o
sam_header.c:9:1: warning: unused function 'kh_clear_str' [-Wunused-function]
KHASH_MAP_INIT_STR(str, const char *)
^
./khash.h:526:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:179:13: note: expanded from macro 'KHASH_INIT2'
        SCOPE void kh_clear_##name(kh_##name##_t *h...
                   ^
<scratch space>:328:1: note: expanded from here
kh_clear_str
^
sam_header.c:9:1: warning: unused function 'kh_del_str' [-Wunused-function]
./khash.h:526:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:307:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static inline, khkey_t, khval_t, kh_is_map, __...
        ^
./khash.h:298:13: note: expanded from macro 'KHASH_INIT2'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x...
                   ^
<scratch space>:342:1: note: expanded from here
kh_del_str
^
2 warnings generated.
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_reheader.c -o bam_reheader.o
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. kprobaln.c -o kprobaln.o
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=0  -I. bam_cat.c -o bam_cat.o
ar -csru libbam.a bgzf.o kstring.o bam_aux.o bam.o bam_import.o sam.o bam_index.o bam_pileup.o bam_lpileup.o bam_md.o razf.o faidx.o bedidx.o bam_sort.o sam_header.o bam_reheader.o kprobaln.o bam_cat.o
g++ -O3 -DNDEBUG -g -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/GBase.cpp -o gclib/GBase.o
g++ -O3 -DNDEBUG -g -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/GArgs.cpp -o gclib/GArgs.o
g++ -O3 -DNDEBUG -g -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/GStr.cpp -o gclib/GStr.o
g++ -O3 -DNDEBUG -g -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/GBam.cpp -o gclib/GBam.o
g++ -O3 -DNDEBUG -g -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/gdna.cpp -o gclib/gdna.o
g++ -O3 -DNDEBUG -g -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/codons.cpp -o gclib/codons.o
g++ -O3 -DNDEBUG -g -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/GFaSeqGet.cpp -o gclib/GFaSeqGet.o
g++ -O3 -DNDEBUG -g -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/gff.cpp -o gclib/gff.o
g++ -O3 -DNDEBUG -g -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-exceptions -fno-rtti -c gclib/GThreads.cpp -o gclib/GThreads.o
g++ -O3 -DNDEBUG -g -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-exceptions -fno-rtti -c rlink.cpp -o rlink.o
In file included from rlink.cpp:1:
In file included from ./rlink.h:10:
./gclib/GIntHash.hh:125:20: warning: implicit conversion of NULL constant to
      'uint32' (aka 'unsigned int') [-Wnull-conversion]
       else return NULL;
            ~~~~~~ ^~~~
                   0
./gclib/GIntHash.hh:204:20: warning: implicit conversion of NULL constant to
      'uint32' (aka 'unsigned int') [-Wnull-conversion]
       else return NULL;
            ~~~~~~ ^~~~
                   0
2 warnings generated.
g++ -O3 -DNDEBUG -g -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-exceptions -fno-rtti -c tablemaker.cpp -o tablemaker.o
In file included from tablemaker.cpp:2:
In file included from ./rlink.h:10:
./gclib/GIntHash.hh:125:20: warning: implicit conversion of NULL constant to
      'uint32' (aka 'unsigned int') [-Wnull-conversion]
       else return NULL;
            ~~~~~~ ^~~~
                   0
./gclib/GIntHash.hh:204:20: warning: implicit conversion of NULL constant to
      'uint32' (aka 'unsigned int') [-Wnull-conversion]
       else return NULL;
            ~~~~~~ ^~~~
                   0
2 warnings generated.
g++ -O3 -DNDEBUG -g -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-exceptions -fno-rtti -c tmerge.cpp -o tmerge.o
In file included from tmerge.cpp:1:
In file included from ./tmerge.h:5:
In file included from ./rlink.h:10:
./gclib/GIntHash.hh:125:20: warning: implicit conversion of NULL constant to
      'uint32' (aka 'unsigned int') [-Wnull-conversion]
       else return NULL;
            ~~~~~~ ^~~~
                   0
./gclib/GIntHash.hh:204:20: warning: implicit conversion of NULL constant to
      'uint32' (aka 'unsigned int') [-Wnull-conversion]
       else return NULL;
            ~~~~~~ ^~~~
                   0
2 warnings generated.
g++ -O3 -DNDEBUG -g -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-exceptions -fno-rtti -c stringtie.cpp -o stringtie.o
In file included from stringtie.cpp:2:
In file included from ./rlink.h:10:
./gclib/GIntHash.hh:125:20: warning: implicit conversion of NULL constant to
      'uint32' (aka 'unsigned int') [-Wnull-conversion]
       else return NULL;
            ~~~~~~ ^~~~
                   0
./gclib/GIntHash.hh:204:20: warning: implicit conversion of NULL constant to
      'uint32' (aka 'unsigned int') [-Wnull-conversion]
       else return NULL;
            ~~~~~~ ^~~~
                   0
2 warnings generated.
g++ -g -L./samtools-0.1.18  -o stringtie gclib/GBase.o gclib/GArgs.o gclib/GStr.o gclib/GBam.o gclib/gdna.o gclib/codons.o gclib/GFaSeqGet.o gclib/gff.o gclib/GThreads.o rlink.o tablemaker.o tmerge.o stringtie.o -lbam -lz -lpthread

**Comment by gpertea** [comment]
The way to use the pre-built OSX binary files is to simply unpack them and run the included binary directly (./stringtie), not try to build it again using `make` (?!).  That is the whole point of providing pre-built binaries.. the user doesn't have to build it him/herself, just unpack and run..

Also, it seems there was no actual error in your build from source there, just warnings.. The executable should be named "stringtie", built in the current directory. Have you tried starting it with the command `./stringtie`  in your terminal there?

Using bioinformatics software like StringTie, samtools etc. will very hard without a basic knowledge about the Linux/Unix shell and the command-line driven environment.
