### ISSUE TITLE
GVec error: invalid index: 14

### ISSUE THREAD

**Issue by mahdi-b** [gpertea/stringtie#97]
I am running Stringtie, v1.3.2d on linux against the Mus_musculus.GRCm38.84.gtf reference (download form hisat2 site). 

Stringtie worked with 14 out of 16 of my samples, and fails with 2. The error message is the following:  

GVec error: invalid index: 14
Aborted (core dumped)

If I run stringtie with the verbose option (-v) the last message printer before the program fails is:

[02/09 15:19:47]^bundle 7:75366055-75366258(34) done (1 processed potential transcripts).
GVec error: invalid index: 14
Aborted (core dumped)

Any help troubleshooting the problem would be greatly appreciated.

All the best,

Mahdi

**Comment by gpertea** [comment]
Could you please extract the alignments from that bundle into a smaller bam file and send it to me? (`samtools -b view` should do it after you index the bam file).
Also please post here the stringtie command line you used to trigger that error (I'm hoping you did not use the `-p` option when you used `-v` to see which bundle triggered the error).
Thanks!

**Comment by gpertea** [comment]
Looking back at the error message above I realize now that the error happened *after* the bundle was already processed (unless you used multithreading for that run), so it might not be triggered by that particular bundle. However I'd still like to see what's going on there if the error persists -- could be a corrupted .bam file ?
You also mentioned that the same error happens on 2 samples, could you please show me the last few lines in the -v output for *both* samples? (again, running stringtie without -p option for the -v output). Maybe there is an unusual configuration of reference transcripts + read alignments chromosome 7 after that location..

**Comment by gpertea** [comment]
Hoping this was fixed in recent releases, closing for now.
